# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/bob_LVE.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(272, 474)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 0, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 4, 1, 1)
        self.pb_pick_file = QtWidgets.QToolButton(Dialog)
        self.pb_pick_file.setObjectName("pb_pick_file")
        self.gridLayout.addWidget(self.pb_pick_file, 0, 1, 1, 1)
        self.selected_file = QtWidgets.QLabel(Dialog)
        self.selected_file.setText("")
        self.selected_file.setObjectName("selected_file")
        self.gridLayout.addWidget(self.selected_file, 0, 3, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.inp_param_widget = QtWidgets.QWidget(Dialog)
        self.inp_param_widget.setObjectName("inp_param_widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.inp_param_widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.inp_param_widget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 222, 349))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_3 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.n_polymers = QtWidgets.QLineEdit(self.groupBox_3)
        self.n_polymers.setObjectName("n_polymers")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.n_polymers)
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setObjectName("label_6")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setObjectName("label_7")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.n_segments = QtWidgets.QLineEdit(self.groupBox_3)
        self.n_segments.setObjectName("n_segments")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.n_segments)
        self.verticalLayout_4.addLayout(self.formLayout_4)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        self.groupBox_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.alpha = QtWidgets.QLineEdit(self.groupBox_2)
        self.alpha.setObjectName("alpha")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.alpha)
        self.label = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label)
        self.m0 = QtWidgets.QLineEdit(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.m0.setFont(font)
        self.m0.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.m0.setObjectName("m0")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.m0)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.ne = QtWidgets.QLineEdit(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.ne.setFont(font)
        self.ne.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.ne.setObjectName("ne")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.ne)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.density = QtWidgets.QLineEdit(self.groupBox_2)
        self.density.setObjectName("density")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.density)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.taue = QtWidgets.QLineEdit(self.groupBox_2)
        self.taue.setObjectName("taue")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.taue)
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.temperature = QtWidgets.QLineEdit(self.groupBox_2)
        self.temperature.setObjectName("temperature")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.temperature)
        self.verticalLayout_7.addLayout(self.formLayout)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.verticalLayout_2.addWidget(self.inp_param_widget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pb_help = QtWidgets.QPushButton(Dialog)
        self.pb_help.setObjectName("pb_help")
        self.horizontalLayout.addWidget(self.pb_help)
        self.pb_cancel = QtWidgets.QPushButton(Dialog)
        self.pb_cancel.setObjectName("pb_cancel")
        self.horizontalLayout.addWidget(self.pb_cancel)
        self.pb_ok = QtWidgets.QPushButton(Dialog)
        self.pb_ok.setObjectName("pb_ok")
        self.horizontalLayout.addWidget(self.pb_ok)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Simulation Parameters"))
        self.label_11.setText(_translate("Dialog", "Selected:"))
        self.label_9.setText(_translate("Dialog", "Input polyconf"))
        self.pb_pick_file.setText(_translate("Dialog", "..."))
        self.groupBox_3.setTitle(_translate("Dialog", "Memory"))
        self.n_polymers.setToolTip(_translate("Dialog", "Maximum number of polymer"))
        self.n_polymers.setText(_translate("Dialog", "1e4"))
        self.label_6.setToolTip(_translate("Dialog", "Maximum number of polymer"))
        self.label_6.setText(_translate("Dialog", "Num. polymers"))
        self.label_7.setToolTip(_translate("Dialog", "Maximum total number of arms"))
        self.label_7.setText(_translate("Dialog", "Num. segments"))
        self.n_segments.setToolTip(_translate("Dialog", "Maximum total number of arms"))
        self.n_segments.setText(_translate("Dialog", "1e5"))
        self.groupBox_2.setTitle(_translate("Dialog", "Parameters"))
        self.label_2.setToolTip(_translate("Dialog", "Tube dilation exponent"))
        self.label_2.setText(_translate("Dialog", "alpha"))
        self.alpha.setToolTip(_translate("Dialog", "Tube dilation exponent"))
        self.alpha.setText(_translate("Dialog", "1"))
        self.label.setToolTip(_translate("Dialog", "Mass of a monomer"))
        self.label.setText(_translate("Dialog", "M0 (g/mol)"))
        self.m0.setToolTip(_translate("Dialog", "Mass of a monomer"))
        self.m0.setText(_translate("Dialog", "28"))
        self.label_4.setToolTip(_translate("Dialog", "Number of monomers in an entanglement length"))
        self.label_4.setText(_translate("Dialog", "Ne"))
        self.ne.setToolTip(_translate("Dialog", "Number of monomers in an entanglement length"))
        self.ne.setText(_translate("Dialog", "40"))
        self.label_3.setToolTip(_translate("Dialog", "Mass-density of the polymer (g/cc accepted)"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p>density (kg/m<span style=\" vertical-align:super;\">3</span>)</p></body></html>"))
        self.density.setToolTip(_translate("Dialog", "Mass-density of the polymer (g/cc accepted)"))
        self.density.setText(_translate("Dialog", "1e3"))
        self.label_5.setToolTip(_translate("Dialog", "Entanglement time"))
        self.label_5.setText(_translate("Dialog", "tau_e (s)"))
        self.taue.setToolTip(_translate("Dialog", "Entanglement time"))
        self.taue.setText(_translate("Dialog", "1e-2"))
        self.label_8.setToolTip(_translate("Dialog", "Temperature"))
        self.label_8.setText(_translate("Dialog", "T (K)"))
        self.temperature.setToolTip(_translate("Dialog", "Temperature"))
        self.temperature.setText(_translate("Dialog", "300"))
        self.pb_help.setToolTip(_translate("Dialog", "Show BoB documentation"))
        self.pb_help.setText(_translate("Dialog", "Help"))
        self.pb_cancel.setText(_translate("Dialog", "Cancel"))
        self.pb_ok.setText(_translate("Dialog", "OK"))

