# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/bob_gen_poly.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(360, 658)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.pb_pick_file = QtWidgets.QToolButton(Dialog)
        self.pb_pick_file.setObjectName("pb_pick_file")
        self.horizontalLayout.addWidget(self.pb_pick_file)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_9.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_2.addWidget(self.label_9)
        self.selected_file = QtWidgets.QLabel(Dialog)
        self.selected_file.setText("")
        self.selected_file.setObjectName("selected_file")
        self.horizontalLayout_2.addWidget(self.selected_file)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_9.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.verticalLayout_9)
        self.inp_param_widget = QtWidgets.QWidget(Dialog)
        self.inp_param_widget.setObjectName("inp_param_widget")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.inp_param_widget)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.tabWidget = QtWidgets.QTabWidget(self.inp_param_widget)
        self.tabWidget.setObjectName("tabWidget")
        self.Chemistry = QtWidgets.QWidget()
        self.Chemistry.setObjectName("Chemistry")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.Chemistry)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.scrollArea = QtWidgets.QScrollArea(self.Chemistry)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 277, 423))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.m0 = QtWidgets.QLineEdit(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.m0.setFont(font)
        self.m0.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.m0.setObjectName("m0")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.m0)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.ne = QtWidgets.QLineEdit(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.ne.setFont(font)
        self.ne.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.ne.setObjectName("ne")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.ne)
        self.verticalLayout_7.addLayout(self.formLayout)
        self.verticalLayout_6.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.component = QtWidgets.QFormLayout()
        self.component.setFieldGrowthPolicy(QtWidgets.QFormLayout.FieldsStayAtSizeHint)
        self.component.setObjectName("component")
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setObjectName("label_2")
        self.component.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.ratio = QtWidgets.QLineEdit(self.groupBox_3)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.ratio.setFont(font)
        self.ratio.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.ratio.setObjectName("ratio")
        self.component.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ratio)
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setObjectName("label_3")
        self.component.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.cb_type = QtWidgets.QComboBox(self.groupBox_3)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cb_type.setFont(font)
        self.cb_type.setObjectName("cb_type")
        self.component.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cb_type)
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.component.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.number = QtWidgets.QLineEdit(self.groupBox_3)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.number.setFont(font)
        self.number.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.number.setObjectName("number")
        self.component.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.number)
        self.ngeneration_label = QtWidgets.QLabel(self.groupBox_3)
        self.ngeneration_label.setEnabled(False)
        self.ngeneration_label.setObjectName("ngeneration_label")
        self.component.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.ngeneration_label)
        self.sb_ngeneration = QtWidgets.QSpinBox(self.groupBox_3)
        self.sb_ngeneration.setEnabled(False)
        self.sb_ngeneration.setMinimum(0)
        self.sb_ngeneration.setProperty("value", 2)
        self.sb_ngeneration.setObjectName("sb_ngeneration")
        self.component.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.sb_ngeneration)
        self.verticalLayout_2.addLayout(self.component)
        self.add_button = QtWidgets.QPushButton(self.groupBox_3)
        self.add_button.setObjectName("add_button")
        self.verticalLayout_2.addWidget(self.add_button)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_6.addWidget(self.groupBox_3)
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.polymer_tab = QtWidgets.QTabWidget(self.groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.polymer_tab.setFont(font)
        self.polymer_tab.setUsesScrollButtons(True)
        self.polymer_tab.setTabsClosable(True)
        self.polymer_tab.setObjectName("polymer_tab")
        self.verticalLayout_4.addWidget(self.polymer_tab)
        self.verticalLayout_6.addWidget(self.groupBox)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_8.addWidget(self.scrollArea)
        self.tabWidget.addTab(self.Chemistry, "")
        self.Memory = QtWidgets.QWidget()
        self.Memory.setObjectName("Memory")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.Memory)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_6 = QtWidgets.QLabel(self.Memory)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setWordWrap(False)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.n_polymers = QtWidgets.QLineEdit(self.Memory)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.n_polymers.setFont(font)
        self.n_polymers.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.n_polymers.setObjectName("n_polymers")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.n_polymers)
        self.label_7 = QtWidgets.QLabel(self.Memory)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setWordWrap(False)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.n_segments = QtWidgets.QLineEdit(self.Memory)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.n_segments.setFont(font)
        self.n_segments.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.n_segments.setObjectName("n_segments")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.n_segments)
        self.verticalLayout_5.addLayout(self.formLayout_2)
        self.tabWidget.addTab(self.Memory, "")
        self.Result = QtWidgets.QWidget()
        self.Result.setObjectName("Result")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.Result)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.splitter = QtWidgets.QSplitter(self.Result)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.text_box = QtWidgets.QTextBrowser(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.text_box.sizePolicy().hasHeightForWidth())
        self.text_box.setSizePolicy(sizePolicy)
        self.text_box.setAcceptRichText(False)
        self.text_box.setObjectName("text_box")
        self.proto_widget = QtWidgets.QWidget(self.splitter)
        self.proto_widget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.proto_widget.sizePolicy().hasHeightForWidth())
        self.proto_widget.setSizePolicy(sizePolicy)
        self.proto_widget.setObjectName("proto_widget")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.proto_widget)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.proto_label = QtWidgets.QLabel(self.proto_widget)
        self.proto_label.setEnabled(False)
        self.proto_label.setObjectName("proto_label")
        self.verticalLayout_10.addWidget(self.proto_label)
        self.proto_text = QtWidgets.QTextBrowser(self.proto_widget)
        self.proto_text.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.proto_text.sizePolicy().hasHeightForWidth())
        self.proto_text.setSizePolicy(sizePolicy)
        self.proto_text.setReadOnly(False)
        self.proto_text.setAcceptRichText(False)
        self.proto_text.setObjectName("proto_text")
        self.verticalLayout_10.addWidget(self.proto_text)
        self.verticalLayout_11.addLayout(self.verticalLayout_10)
        self.verticalLayout_12.addWidget(self.splitter)
        self.tabWidget.addTab(self.Result, "")
        self.verticalLayout_13.addWidget(self.tabWidget)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pb_help = QtWidgets.QPushButton(self.inp_param_widget)
        self.pb_help.setObjectName("pb_help")
        self.horizontalLayout_3.addWidget(self.pb_help)
        self.pb_apply = QtWidgets.QPushButton(self.inp_param_widget)
        self.pb_apply.setObjectName("pb_apply")
        self.horizontalLayout_3.addWidget(self.pb_apply)
        self.pb_ok = QtWidgets.QPushButton(self.inp_param_widget)
        self.pb_ok.setObjectName("pb_ok")
        self.horizontalLayout_3.addWidget(self.pb_ok)
        self.pb_cancel = QtWidgets.QPushButton(self.inp_param_widget)
        self.pb_cancel.setObjectName("pb_cancel")
        self.horizontalLayout_3.addWidget(self.pb_cancel)
        self.verticalLayout_13.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addWidget(self.inp_param_widget)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        self.polymer_tab.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Create Polymer Configuration"))
        self.label_8.setText(_translate("Dialog", "Pick Output Polyconf File"))
        self.pb_pick_file.setToolTip(_translate("Dialog", "Select File..."))
        self.pb_pick_file.setText(_translate("Dialog", "..."))
        self.label_9.setText(_translate("Dialog", "Selected file:"))
        self.groupBox_2.setTitle(_translate("Dialog", "Polymer"))
        self.label.setToolTip(_translate("Dialog", "Mass of a monomer"))
        self.label.setText(_translate("Dialog", "M0 (g/mol)"))
        self.m0.setToolTip(_translate("Dialog", "Mass of a monomer"))
        self.m0.setText(_translate("Dialog", "28"))
        self.label_4.setToolTip(_translate("Dialog", "Number of monomers in an entanglement length"))
        self.label_4.setText(_translate("Dialog", "Ne"))
        self.ne.setToolTip(_translate("Dialog", "Number of monomers in an entanglement length"))
        self.ne.setText(_translate("Dialog", "40"))
        self.groupBox_3.setTitle(_translate("Dialog", "Add Component"))
        self.label_2.setToolTip(_translate("Dialog", "Ratio weight fraction occupied by component"))
        self.label_2.setText(_translate("Dialog", "Ratio"))
        self.ratio.setToolTip(_translate("Dialog", "Ratio weight fraction occupied by component"))
        self.ratio.setText(_translate("Dialog", "1"))
        self.label_3.setToolTip(_translate("Dialog", "Polymer architecture type"))
        self.label_3.setText(_translate("Dialog", "Architecture"))
        self.cb_type.setToolTip(_translate("Dialog", "Polymer architecture type"))
        self.label_5.setToolTip(_translate("Dialog", "Number of polymers in current type"))
        self.label_5.setText(_translate("Dialog", "Num. of polymers"))
        self.number.setToolTip(_translate("Dialog", "Number of polymers in current type"))
        self.number.setText(_translate("Dialog", "1000"))
        self.ngeneration_label.setToolTip(_translate("Dialog", "Number of generations (Cayley type only)"))
        self.ngeneration_label.setText(_translate("Dialog", "Num. generations"))
        self.sb_ngeneration.setToolTip(_translate("Dialog", "Number of generations (Cayley type only)"))
        self.add_button.setToolTip(_translate("Dialog", "Add component to mix"))
        self.add_button.setText(_translate("Dialog", "Add"))
        self.groupBox.setTitle(_translate("Dialog", "Components"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Chemistry), _translate("Dialog", "Chemistry"))
        self.label_6.setToolTip(_translate("Dialog", "Maximum number of polymer"))
        self.label_6.setText(_translate("Dialog", "Max. num. of polymers"))
        self.n_polymers.setToolTip(_translate("Dialog", "Maximum number of polymer"))
        self.n_polymers.setText(_translate("Dialog", "1e4"))
        self.label_7.setText(_translate("Dialog", "Max. num. of segments"))
        self.n_segments.setToolTip(_translate("Dialog", "Maximum total number of arms"))
        self.n_segments.setText(_translate("Dialog", "1e5"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Memory), _translate("Dialog", "Memory"))
        self.proto_label.setText(_translate("Dialog", "Enter Polymer Prototype:"))
        self.proto_text.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.SF NS Text\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Result), _translate("Dialog", "Result"))
        self.pb_help.setText(_translate("Dialog", "Help"))
        self.pb_apply.setText(_translate("Dialog", "Apply"))
        self.pb_ok.setText(_translate("Dialog", "OK"))
        self.pb_cancel.setText(_translate("Dialog", "Cancel"))

