# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fittingoptions.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(419, 763)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Images/Images/new_icons/icons8-minimum-value.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.ls = QtWidgets.QWidget()
        self.ls.setObjectName("ls")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.ls)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox = QtWidgets.QGroupBox(self.ls)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox.setFont(font)
        self.groupBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setContentsMargins(-1, 2, -1, 2)
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setScaledContents(False)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.frame_50 = QtWidgets.QFrame(self.groupBox)
        self.frame_50.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_50.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_50.setObjectName("frame_50")
        self.horizontalLayout_49 = QtWidgets.QHBoxLayout(self.frame_50)
        self.horizontalLayout_49.setContentsMargins(-1, 2, -1, 2)
        self.horizontalLayout_49.setObjectName("horizontalLayout_49")
        self.label_3 = QtWidgets.QLabel(self.frame_50)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_49.addWidget(self.label_3)
        self.LSmethodcomboBox = QtWidgets.QComboBox(self.frame_50)
        self.LSmethodcomboBox.setObjectName("LSmethodcomboBox")
        self.LSmethodcomboBox.addItem("")
        self.LSmethodcomboBox.addItem("")
        self.LSmethodcomboBox.addItem("")
        self.horizontalLayout_49.addWidget(self.LSmethodcomboBox)
        self.verticalLayout_2.addWidget(self.frame_50)
        self.frame_29 = QtWidgets.QFrame(self.groupBox)
        self.frame_29.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_29.setObjectName("frame_29")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout(self.frame_29)
        self.horizontalLayout_30.setContentsMargins(-1, 2, -1, 2)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.label_16 = QtWidgets.QLabel(self.frame_29)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_30.addWidget(self.label_16)
        self.LSjaccomboBox = QtWidgets.QComboBox(self.frame_29)
        self.LSjaccomboBox.setObjectName("LSjaccomboBox")
        self.LSjaccomboBox.addItem("")
        self.LSjaccomboBox.addItem("")
        self.LSjaccomboBox.addItem("")
        self.horizontalLayout_30.addWidget(self.LSjaccomboBox)
        self.verticalLayout_2.addWidget(self.frame_29)
        self.frame = QtWidgets.QFrame(self.groupBox)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(-1, 2, -1, 2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.LSftolcheckBox = QtWidgets.QCheckBox(self.frame)
        self.LSftolcheckBox.setChecked(True)
        self.LSftolcheckBox.setObjectName("LSftolcheckBox")
        self.horizontalLayout_2.addWidget(self.LSftolcheckBox)
        self.LSftollineEdit = QtWidgets.QLineEdit(self.frame)
        self.LSftollineEdit.setObjectName("LSftollineEdit")
        self.horizontalLayout_2.addWidget(self.LSftollineEdit)
        self.verticalLayout_2.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.groupBox)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setContentsMargins(-1, 2, -1, 2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.LSxtolcheckBox = QtWidgets.QCheckBox(self.frame_2)
        self.LSxtolcheckBox.setChecked(True)
        self.LSxtolcheckBox.setObjectName("LSxtolcheckBox")
        self.horizontalLayout_3.addWidget(self.LSxtolcheckBox)
        self.LSxtollineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.LSxtollineEdit.setObjectName("LSxtollineEdit")
        self.horizontalLayout_3.addWidget(self.LSxtollineEdit)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.frame_45 = QtWidgets.QFrame(self.groupBox)
        self.frame_45.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_45.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_45.setObjectName("frame_45")
        self.horizontalLayout_46 = QtWidgets.QHBoxLayout(self.frame_45)
        self.horizontalLayout_46.setContentsMargins(-1, 2, -1, 2)
        self.horizontalLayout_46.setObjectName("horizontalLayout_46")
        self.LSgtolcheckBox = QtWidgets.QCheckBox(self.frame_45)
        self.LSgtolcheckBox.setChecked(True)
        self.LSgtolcheckBox.setObjectName("LSgtolcheckBox")
        self.horizontalLayout_46.addWidget(self.LSgtolcheckBox)
        self.LSgtollineEdit = QtWidgets.QLineEdit(self.frame_45)
        self.LSgtollineEdit.setObjectName("LSgtollineEdit")
        self.horizontalLayout_46.addWidget(self.LSgtollineEdit)
        self.verticalLayout_2.addWidget(self.frame_45)
        self.frame_46 = QtWidgets.QFrame(self.groupBox)
        self.frame_46.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_46.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_46.setObjectName("frame_46")
        self.horizontalLayout_47 = QtWidgets.QHBoxLayout(self.frame_46)
        self.horizontalLayout_47.setContentsMargins(-1, 2, -1, 2)
        self.horizontalLayout_47.setObjectName("horizontalLayout_47")
        self.label = QtWidgets.QLabel(self.frame_46)
        self.label.setObjectName("label")
        self.horizontalLayout_47.addWidget(self.label)
        self.LSlosscomboBox = QtWidgets.QComboBox(self.frame_46)
        self.LSlosscomboBox.setObjectName("LSlosscomboBox")
        self.LSlosscomboBox.addItem("")
        self.LSlosscomboBox.addItem("")
        self.LSlosscomboBox.addItem("")
        self.LSlosscomboBox.addItem("")
        self.LSlosscomboBox.addItem("")
        self.horizontalLayout_47.addWidget(self.LSlosscomboBox)
        self.verticalLayout_2.addWidget(self.frame_46)
        self.frame_47 = QtWidgets.QFrame(self.groupBox)
        self.frame_47.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_47.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_47.setObjectName("frame_47")
        self.horizontalLayout_48 = QtWidgets.QHBoxLayout(self.frame_47)
        self.horizontalLayout_48.setContentsMargins(-1, 2, -1, 2)
        self.horizontalLayout_48.setObjectName("horizontalLayout_48")
        self.label_2 = QtWidgets.QLabel(self.frame_47)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_48.addWidget(self.label_2)
        self.LSf_scalelineEdit = QtWidgets.QLineEdit(self.frame_47)
        self.LSf_scalelineEdit.setObjectName("LSf_scalelineEdit")
        self.horizontalLayout_48.addWidget(self.LSf_scalelineEdit)
        self.verticalLayout_2.addWidget(self.frame_47)
        self.frame_3 = QtWidgets.QFrame(self.groupBox)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setContentsMargins(-1, 2, -1, 2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.LSmax_nfevcheckBox = QtWidgets.QCheckBox(self.frame_3)
        self.LSmax_nfevcheckBox.setObjectName("LSmax_nfevcheckBox")
        self.horizontalLayout.addWidget(self.LSmax_nfevcheckBox)
        self.LSmax_nfevlineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.LSmax_nfevlineEdit.setEnabled(False)
        self.LSmax_nfevlineEdit.setObjectName("LSmax_nfevlineEdit")
        self.horizontalLayout.addWidget(self.LSmax_nfevlineEdit)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.frame_48 = QtWidgets.QFrame(self.groupBox)
        self.frame_48.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_48.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_48.setObjectName("frame_48")
        self.horizontalLayout_50 = QtWidgets.QHBoxLayout(self.frame_48)
        self.horizontalLayout_50.setContentsMargins(-1, 2, -1, 2)
        self.horizontalLayout_50.setObjectName("horizontalLayout_50")
        self.LStr_solvercheckBox = QtWidgets.QCheckBox(self.frame_48)
        self.LStr_solvercheckBox.setObjectName("LStr_solvercheckBox")
        self.horizontalLayout_50.addWidget(self.LStr_solvercheckBox)
        self.LStr_solvercomboBox = QtWidgets.QComboBox(self.frame_48)
        self.LStr_solvercomboBox.setEnabled(False)
        self.LStr_solvercomboBox.setObjectName("LStr_solvercomboBox")
        self.LStr_solvercomboBox.addItem("")
        self.LStr_solvercomboBox.addItem("")
        self.horizontalLayout_50.addWidget(self.LStr_solvercomboBox)
        self.verticalLayout_2.addWidget(self.frame_48)
        self.verticalLayout_6.addWidget(self.groupBox)
        self.tabWidget.addTab(self.ls, "")
        self.basinhopping = QtWidgets.QWidget()
        self.basinhopping.setObjectName("basinhopping")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.basinhopping)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.groupBox_8 = QtWidgets.QGroupBox(self.basinhopping)
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.groupBox_8)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_7.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.groupBox_8)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_7.addWidget(self.label_7)
        self.frame_5 = QtWidgets.QFrame(self.groupBox_8)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_17 = QtWidgets.QLabel(self.frame_5)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_4.addWidget(self.label_17)
        self.basinniterlineEdit = QtWidgets.QLineEdit(self.frame_5)
        self.basinniterlineEdit.setObjectName("basinniterlineEdit")
        self.horizontalLayout_4.addWidget(self.basinniterlineEdit)
        self.verticalLayout_7.addWidget(self.frame_5)
        self.frame_4 = QtWidgets.QFrame(self.groupBox_8)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_18 = QtWidgets.QLabel(self.frame_4)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_6.addWidget(self.label_18)
        self.basinTlineEdit = QtWidgets.QLineEdit(self.frame_4)
        self.basinTlineEdit.setObjectName("basinTlineEdit")
        self.horizontalLayout_6.addWidget(self.basinTlineEdit)
        self.verticalLayout_7.addWidget(self.frame_4)
        self.frame_6 = QtWidgets.QFrame(self.groupBox_8)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_19 = QtWidgets.QLabel(self.frame_6)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_7.addWidget(self.label_19)
        self.basinstepsizelineEdit = QtWidgets.QLineEdit(self.frame_6)
        self.basinstepsizelineEdit.setObjectName("basinstepsizelineEdit")
        self.horizontalLayout_7.addWidget(self.basinstepsizelineEdit)
        self.verticalLayout_7.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.groupBox_8)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_20 = QtWidgets.QLabel(self.frame_7)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_8.addWidget(self.label_20)
        self.basinintervallineEdit = QtWidgets.QLineEdit(self.frame_7)
        self.basinintervallineEdit.setObjectName("basinintervallineEdit")
        self.horizontalLayout_8.addWidget(self.basinintervallineEdit)
        self.verticalLayout_7.addWidget(self.frame_7)
        self.frame_8 = QtWidgets.QFrame(self.groupBox_8)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.basinniter_successcheckBox = QtWidgets.QCheckBox(self.frame_8)
        self.basinniter_successcheckBox.setObjectName("basinniter_successcheckBox")
        self.horizontalLayout_9.addWidget(self.basinniter_successcheckBox)
        self.basinniter_successlineEdit = QtWidgets.QLineEdit(self.frame_8)
        self.basinniter_successlineEdit.setEnabled(False)
        self.basinniter_successlineEdit.setObjectName("basinniter_successlineEdit")
        self.horizontalLayout_9.addWidget(self.basinniter_successlineEdit)
        self.verticalLayout_7.addWidget(self.frame_8)
        self.frame_9 = QtWidgets.QFrame(self.groupBox_8)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.basinseedcheckBox = QtWidgets.QCheckBox(self.frame_9)
        self.basinseedcheckBox.setObjectName("basinseedcheckBox")
        self.horizontalLayout_10.addWidget(self.basinseedcheckBox)
        self.basinseedlineEdit = QtWidgets.QLineEdit(self.frame_9)
        self.basinseedlineEdit.setEnabled(False)
        self.basinseedlineEdit.setObjectName("basinseedlineEdit")
        self.horizontalLayout_10.addWidget(self.basinseedlineEdit)
        self.verticalLayout_7.addWidget(self.frame_9)
        self.verticalLayout_10.addWidget(self.groupBox_8)
        self.tabWidget.addTab(self.basinhopping, "")
        self.dualannealing = QtWidgets.QWidget()
        self.dualannealing.setObjectName("dualannealing")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.dualannealing)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.groupBox_7 = QtWidgets.QGroupBox(self.dualannealing)
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_11.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_8 = QtWidgets.QLabel(self.groupBox_7)
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_11.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.groupBox_7)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_11.addWidget(self.label_9)
        self.frame_17 = QtWidgets.QFrame(self.groupBox_7)
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_17)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_21 = QtWidgets.QLabel(self.frame_17)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_11.addWidget(self.label_21)
        self.annealmaxiterlineEdit = QtWidgets.QLineEdit(self.frame_17)
        self.annealmaxiterlineEdit.setObjectName("annealmaxiterlineEdit")
        self.horizontalLayout_11.addWidget(self.annealmaxiterlineEdit)
        self.verticalLayout_11.addWidget(self.frame_17)
        self.frame_16 = QtWidgets.QFrame(self.groupBox_7)
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_16)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_22 = QtWidgets.QLabel(self.frame_16)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_12.addWidget(self.label_22)
        self.annealinitial_templineEdit = QtWidgets.QLineEdit(self.frame_16)
        self.annealinitial_templineEdit.setObjectName("annealinitial_templineEdit")
        self.horizontalLayout_12.addWidget(self.annealinitial_templineEdit)
        self.verticalLayout_11.addWidget(self.frame_16)
        self.frame_15 = QtWidgets.QFrame(self.groupBox_7)
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_23 = QtWidgets.QLabel(self.frame_15)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_13.addWidget(self.label_23)
        self.annealrestart_temp_ratiolineEdit = QtWidgets.QLineEdit(self.frame_15)
        self.annealrestart_temp_ratiolineEdit.setObjectName("annealrestart_temp_ratiolineEdit")
        self.horizontalLayout_13.addWidget(self.annealrestart_temp_ratiolineEdit)
        self.verticalLayout_11.addWidget(self.frame_15)
        self.frame_14 = QtWidgets.QFrame(self.groupBox_7)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_24 = QtWidgets.QLabel(self.frame_14)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_14.addWidget(self.label_24)
        self.annealvisitlineEdit = QtWidgets.QLineEdit(self.frame_14)
        self.annealvisitlineEdit.setObjectName("annealvisitlineEdit")
        self.horizontalLayout_14.addWidget(self.annealvisitlineEdit)
        self.verticalLayout_11.addWidget(self.frame_14)
        self.frame_13 = QtWidgets.QFrame(self.groupBox_7)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_25 = QtWidgets.QLabel(self.frame_13)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_15.addWidget(self.label_25)
        self.annealacceptlineEdit = QtWidgets.QLineEdit(self.frame_13)
        self.annealacceptlineEdit.setObjectName("annealacceptlineEdit")
        self.horizontalLayout_15.addWidget(self.annealacceptlineEdit)
        self.verticalLayout_11.addWidget(self.frame_13)
        self.frame_12 = QtWidgets.QFrame(self.groupBox_7)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_26 = QtWidgets.QLabel(self.frame_12)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_16.addWidget(self.label_26)
        self.annealmaxfunlineEdit = QtWidgets.QLineEdit(self.frame_12)
        self.annealmaxfunlineEdit.setObjectName("annealmaxfunlineEdit")
        self.horizontalLayout_16.addWidget(self.annealmaxfunlineEdit)
        self.verticalLayout_11.addWidget(self.frame_12)
        self.frame_11 = QtWidgets.QFrame(self.groupBox_7)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.annealseedcheckBox = QtWidgets.QCheckBox(self.frame_11)
        self.annealseedcheckBox.setObjectName("annealseedcheckBox")
        self.horizontalLayout_17.addWidget(self.annealseedcheckBox)
        self.annealseedlineEdit = QtWidgets.QLineEdit(self.frame_11)
        self.annealseedlineEdit.setEnabled(False)
        self.annealseedlineEdit.setObjectName("annealseedlineEdit")
        self.horizontalLayout_17.addWidget(self.annealseedlineEdit)
        self.verticalLayout_11.addWidget(self.frame_11)
        self.frame_10 = QtWidgets.QFrame(self.groupBox_7)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.annealno_local_searchcheckBox = QtWidgets.QCheckBox(self.frame_10)
        self.annealno_local_searchcheckBox.setObjectName("annealno_local_searchcheckBox")
        self.horizontalLayout_18.addWidget(self.annealno_local_searchcheckBox)
        self.verticalLayout_11.addWidget(self.frame_10)
        self.verticalLayout_9.addWidget(self.groupBox_7)
        self.tabWidget.addTab(self.dualannealing, "")
        self.differentialevolution = QtWidgets.QWidget()
        self.differentialevolution.setObjectName("differentialevolution")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.differentialevolution)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.groupBox_9 = QtWidgets.QGroupBox(self.differentialevolution)
        self.groupBox_9.setObjectName("groupBox_9")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_14.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_10 = QtWidgets.QLabel(self.groupBox_9)
        self.label_10.setWordWrap(True)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_14.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.groupBox_9)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_14.addWidget(self.label_11)
        self.frame_18 = QtWidgets.QFrame(self.groupBox_9)
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.frame_18)
        self.horizontalLayout_19.setContentsMargins(-1, 2, -1, 2)
        self.horizontalLayout_19.setSpacing(6)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_27 = QtWidgets.QLabel(self.frame_18)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_19.addWidget(self.label_27)
        self.diffevolstrategycomboBox = QtWidgets.QComboBox(self.frame_18)
        self.diffevolstrategycomboBox.setObjectName("diffevolstrategycomboBox")
        self.diffevolstrategycomboBox.addItem("")
        self.diffevolstrategycomboBox.addItem("")
        self.diffevolstrategycomboBox.addItem("")
        self.diffevolstrategycomboBox.addItem("")
        self.diffevolstrategycomboBox.addItem("")
        self.diffevolstrategycomboBox.addItem("")
        self.diffevolstrategycomboBox.addItem("")
        self.diffevolstrategycomboBox.addItem("")
        self.diffevolstrategycomboBox.addItem("")
        self.diffevolstrategycomboBox.addItem("")
        self.diffevolstrategycomboBox.addItem("")
        self.diffevolstrategycomboBox.addItem("")
        self.horizontalLayout_19.addWidget(self.diffevolstrategycomboBox)
        self.verticalLayout_14.addWidget(self.frame_18)
        self.frame_19 = QtWidgets.QFrame(self.groupBox_9)
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.frame_19)
        self.horizontalLayout_20.setContentsMargins(-1, 2, -1, 2)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_28 = QtWidgets.QLabel(self.frame_19)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_20.addWidget(self.label_28)
        self.diffevolmaxiterlineEdit = QtWidgets.QLineEdit(self.frame_19)
        self.diffevolmaxiterlineEdit.setObjectName("diffevolmaxiterlineEdit")
        self.horizontalLayout_20.addWidget(self.diffevolmaxiterlineEdit)
        self.verticalLayout_14.addWidget(self.frame_19)
        self.frame_20 = QtWidgets.QFrame(self.groupBox_9)
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.frame_20)
        self.horizontalLayout_21.setContentsMargins(-1, 2, -1, 2)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_29 = QtWidgets.QLabel(self.frame_20)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_21.addWidget(self.label_29)
        self.diffevolpopsizelineEdit = QtWidgets.QLineEdit(self.frame_20)
        self.diffevolpopsizelineEdit.setObjectName("diffevolpopsizelineEdit")
        self.horizontalLayout_21.addWidget(self.diffevolpopsizelineEdit)
        self.verticalLayout_14.addWidget(self.frame_20)
        self.frame_21 = QtWidgets.QFrame(self.groupBox_9)
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.frame_21)
        self.horizontalLayout_22.setContentsMargins(-1, 2, -1, 2)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_30 = QtWidgets.QLabel(self.frame_21)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_22.addWidget(self.label_30)
        self.diffevoltollineEdit = QtWidgets.QLineEdit(self.frame_21)
        self.diffevoltollineEdit.setObjectName("diffevoltollineEdit")
        self.horizontalLayout_22.addWidget(self.diffevoltollineEdit)
        self.verticalLayout_14.addWidget(self.frame_21)
        self.frame_22 = QtWidgets.QFrame(self.groupBox_9)
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.frame_22)
        self.horizontalLayout_23.setContentsMargins(-1, 2, -1, 2)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_31 = QtWidgets.QLabel(self.frame_22)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_23.addWidget(self.label_31)
        self.diffevolmutationAlineEdit = QtWidgets.QLineEdit(self.frame_22)
        self.diffevolmutationAlineEdit.setObjectName("diffevolmutationAlineEdit")
        self.horizontalLayout_23.addWidget(self.diffevolmutationAlineEdit)
        self.diffevolmutationBlineEdit = QtWidgets.QLineEdit(self.frame_22)
        self.diffevolmutationBlineEdit.setObjectName("diffevolmutationBlineEdit")
        self.horizontalLayout_23.addWidget(self.diffevolmutationBlineEdit)
        self.verticalLayout_14.addWidget(self.frame_22)
        self.frame_23 = QtWidgets.QFrame(self.groupBox_9)
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.frame_23)
        self.horizontalLayout_24.setContentsMargins(-1, 2, -1, 2)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_32 = QtWidgets.QLabel(self.frame_23)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_24.addWidget(self.label_32)
        self.diffevolrecombinationlineEdit = QtWidgets.QLineEdit(self.frame_23)
        self.diffevolrecombinationlineEdit.setObjectName("diffevolrecombinationlineEdit")
        self.horizontalLayout_24.addWidget(self.diffevolrecombinationlineEdit)
        self.verticalLayout_14.addWidget(self.frame_23)
        self.frame_24 = QtWidgets.QFrame(self.groupBox_9)
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.frame_24)
        self.horizontalLayout_25.setContentsMargins(-1, 2, -1, 2)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.diffevolseedcheckBox = QtWidgets.QCheckBox(self.frame_24)
        self.diffevolseedcheckBox.setObjectName("diffevolseedcheckBox")
        self.horizontalLayout_25.addWidget(self.diffevolseedcheckBox)
        self.diffevolseedlineEdit = QtWidgets.QLineEdit(self.frame_24)
        self.diffevolseedlineEdit.setEnabled(False)
        self.diffevolseedlineEdit.setObjectName("diffevolseedlineEdit")
        self.horizontalLayout_25.addWidget(self.diffevolseedlineEdit)
        self.verticalLayout_14.addWidget(self.frame_24)
        self.frame_25 = QtWidgets.QFrame(self.groupBox_9)
        self.frame_25.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout(self.frame_25)
        self.horizontalLayout_26.setContentsMargins(-1, 2, -1, 2)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.diffevolpolishcheckBox = QtWidgets.QCheckBox(self.frame_25)
        self.diffevolpolishcheckBox.setChecked(True)
        self.diffevolpolishcheckBox.setObjectName("diffevolpolishcheckBox")
        self.horizontalLayout_26.addWidget(self.diffevolpolishcheckBox)
        self.verticalLayout_14.addWidget(self.frame_25)
        self.frame_26 = QtWidgets.QFrame(self.groupBox_9)
        self.frame_26.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_26.setObjectName("frame_26")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(self.frame_26)
        self.horizontalLayout_27.setContentsMargins(-1, 2, -1, 2)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_33 = QtWidgets.QLabel(self.frame_26)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_27.addWidget(self.label_33)
        self.diffevolinitcomboBox = QtWidgets.QComboBox(self.frame_26)
        self.diffevolinitcomboBox.setObjectName("diffevolinitcomboBox")
        self.diffevolinitcomboBox.addItem("")
        self.diffevolinitcomboBox.addItem("")
        self.horizontalLayout_27.addWidget(self.diffevolinitcomboBox)
        self.verticalLayout_14.addWidget(self.frame_26)
        self.frame_27 = QtWidgets.QFrame(self.groupBox_9)
        self.frame_27.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_27.setObjectName("frame_27")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout(self.frame_27)
        self.horizontalLayout_28.setContentsMargins(-1, 2, -1, 2)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_34 = QtWidgets.QLabel(self.frame_27)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_28.addWidget(self.label_34)
        self.diffevolatollineEdit = QtWidgets.QLineEdit(self.frame_27)
        self.diffevolatollineEdit.setObjectName("diffevolatollineEdit")
        self.horizontalLayout_28.addWidget(self.diffevolatollineEdit)
        self.verticalLayout_14.addWidget(self.frame_27)
        self.frame_28 = QtWidgets.QFrame(self.groupBox_9)
        self.frame_28.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_28.setObjectName("frame_28")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout(self.frame_28)
        self.horizontalLayout_29.setContentsMargins(-1, 2, -1, 2)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_35 = QtWidgets.QLabel(self.frame_28)
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_29.addWidget(self.label_35)
        self.diffevolupdatingcomboBox = QtWidgets.QComboBox(self.frame_28)
        self.diffevolupdatingcomboBox.setObjectName("diffevolupdatingcomboBox")
        self.diffevolupdatingcomboBox.addItem("")
        self.diffevolupdatingcomboBox.addItem("")
        self.horizontalLayout_29.addWidget(self.diffevolupdatingcomboBox)
        self.verticalLayout_14.addWidget(self.frame_28)
        self.verticalLayout_12.addWidget(self.groupBox_9)
        self.tabWidget.addTab(self.differentialevolution, "")
        self.shgo = QtWidgets.QWidget()
        self.shgo.setObjectName("shgo")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.shgo)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.groupBox_12 = QtWidgets.QGroupBox(self.shgo)
        self.groupBox_12.setObjectName("groupBox_12")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.groupBox_12)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_12 = QtWidgets.QLabel(self.groupBox_12)
        self.label_12.setWordWrap(True)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_17.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(self.groupBox_12)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_17.addWidget(self.label_13)
        self.frame_30 = QtWidgets.QFrame(self.groupBox_12)
        self.frame_30.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_30.setObjectName("frame_30")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout(self.frame_30)
        self.horizontalLayout_31.setContentsMargins(-1, 2, -1, 2)
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.label_36 = QtWidgets.QLabel(self.frame_30)
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_31.addWidget(self.label_36)
        self.SHGOnlineEdit = QtWidgets.QLineEdit(self.frame_30)
        self.SHGOnlineEdit.setObjectName("SHGOnlineEdit")
        self.horizontalLayout_31.addWidget(self.SHGOnlineEdit)
        self.verticalLayout_17.addWidget(self.frame_30)
        self.frame_31 = QtWidgets.QFrame(self.groupBox_12)
        self.frame_31.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_31.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_31.setObjectName("frame_31")
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout(self.frame_31)
        self.horizontalLayout_32.setContentsMargins(-1, 2, -1, 2)
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.label_37 = QtWidgets.QLabel(self.frame_31)
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_32.addWidget(self.label_37)
        self.SHGOiterslineEdit = QtWidgets.QLineEdit(self.frame_31)
        self.SHGOiterslineEdit.setObjectName("SHGOiterslineEdit")
        self.horizontalLayout_32.addWidget(self.SHGOiterslineEdit)
        self.verticalLayout_17.addWidget(self.frame_31)
        self.frame_32 = QtWidgets.QFrame(self.groupBox_12)
        self.frame_32.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_32.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_32.setObjectName("frame_32")
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout(self.frame_32)
        self.horizontalLayout_33.setContentsMargins(-1, 2, -1, 2)
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.SHGOmaxfevcheckBox = QtWidgets.QCheckBox(self.frame_32)
        self.SHGOmaxfevcheckBox.setObjectName("SHGOmaxfevcheckBox")
        self.horizontalLayout_33.addWidget(self.SHGOmaxfevcheckBox)
        self.SHGOmaxfevlineEdit = QtWidgets.QLineEdit(self.frame_32)
        self.SHGOmaxfevlineEdit.setEnabled(False)
        self.SHGOmaxfevlineEdit.setObjectName("SHGOmaxfevlineEdit")
        self.horizontalLayout_33.addWidget(self.SHGOmaxfevlineEdit)
        self.verticalLayout_17.addWidget(self.frame_32)
        self.frame_33 = QtWidgets.QFrame(self.groupBox_12)
        self.frame_33.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_33.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_33.setObjectName("frame_33")
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout(self.frame_33)
        self.horizontalLayout_34.setContentsMargins(-1, 2, -1, 2)
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.SHGOf_mincheckBox = QtWidgets.QCheckBox(self.frame_33)
        self.SHGOf_mincheckBox.setObjectName("SHGOf_mincheckBox")
        self.horizontalLayout_34.addWidget(self.SHGOf_mincheckBox)
        self.SHGOf_minlineEdit = QtWidgets.QLineEdit(self.frame_33)
        self.SHGOf_minlineEdit.setEnabled(False)
        self.SHGOf_minlineEdit.setObjectName("SHGOf_minlineEdit")
        self.horizontalLayout_34.addWidget(self.SHGOf_minlineEdit)
        self.verticalLayout_17.addWidget(self.frame_33)
        self.frame_34 = QtWidgets.QFrame(self.groupBox_12)
        self.frame_34.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_34.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_34.setObjectName("frame_34")
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout(self.frame_34)
        self.horizontalLayout_35.setContentsMargins(-1, 2, -1, 2)
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.label_39 = QtWidgets.QLabel(self.frame_34)
        self.label_39.setObjectName("label_39")
        self.horizontalLayout_35.addWidget(self.label_39)
        self.SHGOf_tollineEdit = QtWidgets.QLineEdit(self.frame_34)
        self.SHGOf_tollineEdit.setObjectName("SHGOf_tollineEdit")
        self.horizontalLayout_35.addWidget(self.SHGOf_tollineEdit)
        self.verticalLayout_17.addWidget(self.frame_34)
        self.frame_35 = QtWidgets.QFrame(self.groupBox_12)
        self.frame_35.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_35.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_35.setObjectName("frame_35")
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout(self.frame_35)
        self.horizontalLayout_36.setContentsMargins(-1, 2, -1, 2)
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.SHGOmaxitercheckBox = QtWidgets.QCheckBox(self.frame_35)
        self.SHGOmaxitercheckBox.setObjectName("SHGOmaxitercheckBox")
        self.horizontalLayout_36.addWidget(self.SHGOmaxitercheckBox)
        self.SHGOmaxiterlineEdit = QtWidgets.QLineEdit(self.frame_35)
        self.SHGOmaxiterlineEdit.setEnabled(False)
        self.SHGOmaxiterlineEdit.setObjectName("SHGOmaxiterlineEdit")
        self.horizontalLayout_36.addWidget(self.SHGOmaxiterlineEdit)
        self.verticalLayout_17.addWidget(self.frame_35)
        self.frame_36 = QtWidgets.QFrame(self.groupBox_12)
        self.frame_36.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_36.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_36.setObjectName("frame_36")
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout(self.frame_36)
        self.horizontalLayout_37.setContentsMargins(-1, 2, -1, 2)
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.SHGOmaxevcheckBox = QtWidgets.QCheckBox(self.frame_36)
        self.SHGOmaxevcheckBox.setObjectName("SHGOmaxevcheckBox")
        self.horizontalLayout_37.addWidget(self.SHGOmaxevcheckBox)
        self.SHGOmaxevlineEdit = QtWidgets.QLineEdit(self.frame_36)
        self.SHGOmaxevlineEdit.setEnabled(False)
        self.SHGOmaxevlineEdit.setObjectName("SHGOmaxevlineEdit")
        self.horizontalLayout_37.addWidget(self.SHGOmaxevlineEdit)
        self.verticalLayout_17.addWidget(self.frame_36)
        self.frame_37 = QtWidgets.QFrame(self.groupBox_12)
        self.frame_37.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_37.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_37.setObjectName("frame_37")
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout(self.frame_37)
        self.horizontalLayout_38.setContentsMargins(-1, 2, -1, 2)
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.SHGOmaxtimecheckBox = QtWidgets.QCheckBox(self.frame_37)
        self.SHGOmaxtimecheckBox.setObjectName("SHGOmaxtimecheckBox")
        self.horizontalLayout_38.addWidget(self.SHGOmaxtimecheckBox)
        self.SHGOmaxtimelineEdit = QtWidgets.QLineEdit(self.frame_37)
        self.SHGOmaxtimelineEdit.setEnabled(False)
        self.SHGOmaxtimelineEdit.setObjectName("SHGOmaxtimelineEdit")
        self.horizontalLayout_38.addWidget(self.SHGOmaxtimelineEdit)
        self.verticalLayout_17.addWidget(self.frame_37)
        self.frame_38 = QtWidgets.QFrame(self.groupBox_12)
        self.frame_38.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_38.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_38.setObjectName("frame_38")
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout(self.frame_38)
        self.horizontalLayout_39.setContentsMargins(-1, 2, -1, 2)
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.SHGOminhgrdcheckBox = QtWidgets.QCheckBox(self.frame_38)
        self.SHGOminhgrdcheckBox.setObjectName("SHGOminhgrdcheckBox")
        self.horizontalLayout_39.addWidget(self.SHGOminhgrdcheckBox)
        self.SHGOminhgrdlineEdit = QtWidgets.QLineEdit(self.frame_38)
        self.SHGOminhgrdlineEdit.setEnabled(False)
        self.SHGOminhgrdlineEdit.setObjectName("SHGOminhgrdlineEdit")
        self.horizontalLayout_39.addWidget(self.SHGOminhgrdlineEdit)
        self.verticalLayout_17.addWidget(self.frame_38)
        self.frame_40 = QtWidgets.QFrame(self.groupBox_12)
        self.frame_40.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_40.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_40.setObjectName("frame_40")
        self.horizontalLayout_41 = QtWidgets.QHBoxLayout(self.frame_40)
        self.horizontalLayout_41.setContentsMargins(-1, 2, -1, 2)
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        self.SHGOminimize_every_itercheckBox = QtWidgets.QCheckBox(self.frame_40)
        self.SHGOminimize_every_itercheckBox.setObjectName("SHGOminimize_every_itercheckBox")
        self.horizontalLayout_41.addWidget(self.SHGOminimize_every_itercheckBox)
        self.verticalLayout_17.addWidget(self.frame_40)
        self.frame_41 = QtWidgets.QFrame(self.groupBox_12)
        self.frame_41.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_41.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_41.setObjectName("frame_41")
        self.horizontalLayout_42 = QtWidgets.QHBoxLayout(self.frame_41)
        self.horizontalLayout_42.setContentsMargins(-1, 2, -1, 2)
        self.horizontalLayout_42.setObjectName("horizontalLayout_42")
        self.SHGOlocal_itercheckBox = QtWidgets.QCheckBox(self.frame_41)
        self.SHGOlocal_itercheckBox.setObjectName("SHGOlocal_itercheckBox")
        self.horizontalLayout_42.addWidget(self.SHGOlocal_itercheckBox)
        self.verticalLayout_17.addWidget(self.frame_41)
        self.frame_42 = QtWidgets.QFrame(self.groupBox_12)
        self.frame_42.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_42.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_42.setObjectName("frame_42")
        self.horizontalLayout_43 = QtWidgets.QHBoxLayout(self.frame_42)
        self.horizontalLayout_43.setContentsMargins(-1, 2, -1, 2)
        self.horizontalLayout_43.setObjectName("horizontalLayout_43")
        self.SHGOinfty_constraintscheckBox = QtWidgets.QCheckBox(self.frame_42)
        self.SHGOinfty_constraintscheckBox.setChecked(True)
        self.SHGOinfty_constraintscheckBox.setObjectName("SHGOinfty_constraintscheckBox")
        self.horizontalLayout_43.addWidget(self.SHGOinfty_constraintscheckBox)
        self.verticalLayout_17.addWidget(self.frame_42)
        self.frame_43 = QtWidgets.QFrame(self.groupBox_12)
        self.frame_43.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_43.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_43.setObjectName("frame_43")
        self.horizontalLayout_44 = QtWidgets.QHBoxLayout(self.frame_43)
        self.horizontalLayout_44.setContentsMargins(-1, 2, -1, 2)
        self.horizontalLayout_44.setObjectName("horizontalLayout_44")
        self.label_38 = QtWidgets.QLabel(self.frame_43)
        self.label_38.setObjectName("label_38")
        self.horizontalLayout_44.addWidget(self.label_38)
        self.SHGOsampling_methodcomboBox = QtWidgets.QComboBox(self.frame_43)
        self.SHGOsampling_methodcomboBox.setObjectName("SHGOsampling_methodcomboBox")
        self.SHGOsampling_methodcomboBox.addItem("")
        self.SHGOsampling_methodcomboBox.addItem("")
        self.horizontalLayout_44.addWidget(self.SHGOsampling_methodcomboBox)
        self.verticalLayout_17.addWidget(self.frame_43)
        self.verticalLayout_20.addWidget(self.groupBox_12)
        self.tabWidget.addTab(self.shgo, "")
        self.brute = QtWidgets.QWidget()
        self.brute.setObjectName("brute")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.brute)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox_2 = QtWidgets.QGroupBox(self.brute)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_14 = QtWidgets.QLabel(self.groupBox_2)
        self.label_14.setWordWrap(True)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_3.addWidget(self.label_14)
        self.label_15 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_3.addWidget(self.label_15)
        self.frame_44 = QtWidgets.QFrame(self.groupBox_2)
        self.frame_44.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_44.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_44.setObjectName("frame_44")
        self.horizontalLayout_45 = QtWidgets.QHBoxLayout(self.frame_44)
        self.horizontalLayout_45.setObjectName("horizontalLayout_45")
        self.label_40 = QtWidgets.QLabel(self.frame_44)
        self.label_40.setObjectName("label_40")
        self.horizontalLayout_45.addWidget(self.label_40)
        self.BruteNslineEdit = QtWidgets.QLineEdit(self.frame_44)
        self.BruteNslineEdit.setObjectName("BruteNslineEdit")
        self.horizontalLayout_45.addWidget(self.BruteNslineEdit)
        self.verticalLayout_3.addWidget(self.frame_44)
        self.verticalLayout_5.addWidget(self.groupBox_2)
        self.tabWidget.addTab(self.brute, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushCancel = QtWidgets.QPushButton(Dialog)
        self.pushCancel.setObjectName("pushCancel")
        self.horizontalLayout_5.addWidget(self.pushCancel)
        self.pushOK = QtWidgets.QPushButton(Dialog)
        self.pushOK.setObjectName("pushOK")
        self.horizontalLayout_5.addWidget(self.pushOK)
        self.verticalLayout.addLayout(self.horizontalLayout_5)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(5)
        self.pushOK.clicked.connect(Dialog.accept)
        self.pushCancel.clicked.connect(Dialog.reject)
        self.LSftolcheckBox.toggled['bool'].connect(self.LSftollineEdit.setEnabled)
        self.LSxtolcheckBox.toggled['bool'].connect(self.LSxtollineEdit.setEnabled)
        self.LSgtolcheckBox.toggled['bool'].connect(self.LSgtollineEdit.setEnabled)
        self.LSmax_nfevcheckBox.toggled['bool'].connect(self.LSmax_nfevlineEdit.setEnabled)
        self.LStr_solvercheckBox.toggled['bool'].connect(self.LStr_solvercomboBox.setEnabled)
        self.basinniter_successcheckBox.toggled['bool'].connect(self.basinniter_successlineEdit.setEnabled)
        self.annealseedcheckBox.toggled['bool'].connect(self.annealseedlineEdit.setEnabled)
        self.diffevolseedcheckBox.toggled['bool'].connect(self.diffevolseedlineEdit.setEnabled)
        self.SHGOmaxevcheckBox.toggled['bool'].connect(self.SHGOmaxfevlineEdit.setEnabled)
        self.SHGOf_mincheckBox.toggled['bool'].connect(self.SHGOf_minlineEdit.setEnabled)
        self.SHGOmaxitercheckBox.toggled['bool'].connect(self.SHGOmaxiterlineEdit.setEnabled)
        self.SHGOmaxevcheckBox.toggled['bool'].connect(self.SHGOmaxevlineEdit.setEnabled)
        self.SHGOmaxtimecheckBox.toggled['bool'].connect(self.SHGOmaxtimelineEdit.setEnabled)
        self.SHGOminhgrdcheckBox.toggled['bool'].connect(self.SHGOminhgrdlineEdit.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Fitting Options"))
        self.groupBox.setTitle(_translate("Dialog", "Least Squares Minimization"))
        self.label_4.setText(_translate("Dialog", "Available methods are:\n"
"- Trust Region Reflective algorithm, particularly suitable for large sparse problems with bounds. Generally robust method (DEFAULT).\n"
"- ‘dogbox’ : dogleg algorithm with rectangular trust regions, typical use case is small problems with bounds. Not recommended for problems with rank-deficient Jacobian.\n"
"- ‘lm’ : Levenberg-Marquardt algorithm as implemented in MINPACK. Doesn’t handle bounds and sparse Jacobians. Usually the most efficient method for small unconstrained problems."))
        self.label_5.setText(_translate("Dialog", "Local Method"))
        self.label_3.setText(_translate("Dialog", "method"))
        self.LSmethodcomboBox.setToolTip(_translate("Dialog", "- Trust Region Reflective algorithm, particularly suitable for large sparse problems with bounds. Generally robust method (DEFAULT).\n"
"- ‘dogbox’ : dogleg algorithm with rectangular trust regions, typical use case is small problems with bounds. Not recommended for problems with rank-deficient Jacobian.\n"
"- ‘lm’ : Levenberg-Marquardt algorithm as implemented in MINPACK. Doesn’t handle bounds and sparse Jacobians. Usually the most efficient method for small unconstrained problems."))
        self.LSmethodcomboBox.setItemText(0, _translate("Dialog", "trf"))
        self.LSmethodcomboBox.setItemText(1, _translate("Dialog", "dogbox"))
        self.LSmethodcomboBox.setItemText(2, _translate("Dialog", "lm"))
        self.label_16.setToolTip(_translate("Dialog", "Finite difference scheme for numerical estimation of the Jacobian matrix: \n"
"- ‘2-point’ (default)\n"
"- ‘3-point’: more accurate, but requires twice as many operations as 2-point. \n"
"- ‘cs’ uses complex steps, and while potentially the most accurate, it is applicable only when fun correctly handles complex inputs and can be analytically continued to the complex plane. \n"
"Method ‘lm’ always uses the ‘2-point’ scheme."))
        self.label_16.setText(_translate("Dialog", "jac"))
        self.LSjaccomboBox.setToolTip(_translate("Dialog", "Finite difference scheme for numerical estimation of the Jacobian matrix: \n"
"- ‘2-point’ (default)\n"
"- ‘3-point’: more accurate, but requires twice as many operations as 2-point. \n"
"- ‘cs’ uses complex steps, and while potentially the most accurate, it is applicable only when fun correctly handles complex inputs and can be analytically continued to the complex plane. \n"
"Method ‘lm’ always uses the ‘2-point’ scheme."))
        self.LSjaccomboBox.setItemText(0, _translate("Dialog", "2-point"))
        self.LSjaccomboBox.setItemText(1, _translate("Dialog", "3-point"))
        self.LSjaccomboBox.setItemText(2, _translate("Dialog", "cs"))
        self.LSftolcheckBox.setToolTip(_translate("Dialog", "Tolerance for termination by the change of the cost function. Default is 1e-8. The optimization process is stopped when dF < ftol * F, and there was an adequate agreement between a local quadratic model and the true model in the last step."))
        self.LSftolcheckBox.setText(_translate("Dialog", "ftol"))
        self.LSftollineEdit.setToolTip(_translate("Dialog", "Tolerance for termination by the change of the cost function. Default is 1e-8. The optimization process is stopped when dF < ftol * F, and there was an adequate agreement between a local quadratic model and the true model in the last step."))
        self.LSxtolcheckBox.setToolTip(_translate("Dialog", "Tolerance for termination by the change of the independent variables. Default is 1e-8. The exact condition depends on the method used:\n"
"\n"
"For ‘trf’ and ‘dogbox’ : norm(dx) < xtol * (xtol + norm(x))\n"
"\n"
"For ‘lm’ : Delta < xtol * norm(xs), where Delta is a trust-region radius and xs is the value of x scaled according to x_scale parameter (see below)."))
        self.LSxtolcheckBox.setText(_translate("Dialog", "xtol"))
        self.LSxtollineEdit.setToolTip(_translate("Dialog", "Tolerance for termination by the change of the independent variables. Default is 1e-8. The exact condition depends on the method used:\n"
"\n"
"For ‘trf’ and ‘dogbox’ : norm(dx) < xtol * (xtol + norm(x))\n"
"\n"
"For ‘lm’ : Delta < xtol * norm(xs), where Delta is a trust-region radius and xs is the value of x scaled according to x_scale parameter (see below)."))
        self.LSgtolcheckBox.setToolTip(_translate("Dialog", "Tolerance for termination by the norm of the gradient. Default is 1e-8. The exact condition depends on a method used:\n"
"\n"
"For ‘trf’ : norm(g_scaled, ord=np.inf) < gtol, where g_scaled is the value of the gradient scaled to account for the presence of the bounds [STIR].\n"
"\n"
"For ‘dogbox’ : norm(g_free, ord=np.inf) < gtol, where g_free is the gradient with respect to the variables which are not in the optimal state on the boundary.\n"
"\n"
"For ‘lm’ : the maximum absolute value of the cosine of angles between columns of the Jacobian and the residual vector is less than gtol, or the residual vector is zero."))
        self.LSgtolcheckBox.setText(_translate("Dialog", "gtol"))
        self.LSgtollineEdit.setToolTip(_translate("Dialog", "Tolerance for termination by the norm of the gradient. Default is 1e-8. The exact condition depends on a method used:\n"
"\n"
"For ‘trf’ : norm(g_scaled, ord=np.inf) < gtol, where g_scaled is the value of the gradient scaled to account for the presence of the bounds [STIR].\n"
"\n"
"For ‘dogbox’ : norm(g_free, ord=np.inf) < gtol, where g_free is the gradient with respect to the variables which are not in the optimal state on the boundary.\n"
"\n"
"For ‘lm’ : the maximum absolute value of the cosine of angles between columns of the Jacobian and the residual vector is less than gtol, or the residual vector is zero."))
        self.label.setText(_translate("Dialog", "loss"))
        self.LSlosscomboBox.setToolTip(_translate("Dialog", "Determines the loss function. The following keyword values are allowed:\n"
"- ‘linear’ (default) : rho(z) = z. Gives a standard least-squares problem.\n"
"- ‘soft_l1’ : rho(z) = 2 * ((1 + z)**0.5 - 1). The smooth approximation of l1 (absolute value) loss. Usually a good choice for robust least squares.\n"
"- ‘huber’ : rho(z) = z if z <= 1 else 2*z^0.5 - 1. Works similarly to ‘soft_l1’. \n"
"- ‘cauchy’ : rho(z) = ln(1 + z). Severely weakens outliers influence, but may cause difficulties in optimization process.\n"
"- ‘arctan’ : rho(z) = arctan(z). Limits a maximum loss on a single residual, has properties similar to ‘cauchy’.\n"
" Method ‘lm’ supports only ‘linear’ loss."))
        self.LSlosscomboBox.setItemText(0, _translate("Dialog", "linear"))
        self.LSlosscomboBox.setItemText(1, _translate("Dialog", "soft_l1"))
        self.LSlosscomboBox.setItemText(2, _translate("Dialog", "huber"))
        self.LSlosscomboBox.setItemText(3, _translate("Dialog", "cauchy"))
        self.LSlosscomboBox.setItemText(4, _translate("Dialog", "arctan"))
        self.label_2.setText(_translate("Dialog", "f_scale"))
        self.LSf_scalelineEdit.setToolTip(_translate("Dialog", "Value of soft margin between inlier and outlier residuals, default is 1.0. The loss function is evaluated as follows rho_(f**2) = C**2 * rho(f**2 / C**2), where C is f_scale, and rho is determined by loss parameter. This parameter has no effect with loss=\'linear\', but for other loss values it is of crucial importance."))
        self.LSmax_nfevcheckBox.setToolTip(_translate("Dialog", "Maximum number of function evaluations before the termination. If None (default), the value is chosen automatically:\n"
"\n"
"For ‘trf’ and ‘dogbox’ : 100 * n.\n"
"\n"
"For ‘lm’ : 100 * n if jac is callable and 100 * n * (n + 1) otherwise (because ‘lm’ counts function calls in Jacobian estimation)."))
        self.LSmax_nfevcheckBox.setText(_translate("Dialog", "max_nfev"))
        self.LSmax_nfevlineEdit.setToolTip(_translate("Dialog", "Maximum number of function evaluations before the termination. If None (default), the value is chosen automatically:\n"
"\n"
"For ‘trf’ and ‘dogbox’ : 100 * n.\n"
"\n"
"For ‘lm’ : 100 * n if jac is callable and 100 * n * (n + 1) otherwise (because ‘lm’ counts function calls in Jacobian estimation)."))
        self.LStr_solvercheckBox.setText(_translate("Dialog", "tr_solver"))
        self.LStr_solvercomboBox.setToolTip(_translate("Dialog", "Method for solving trust-region subproblems, relevant only for ‘trf’ and ‘dogbox’ methods.\n"
"\n"
"‘exact’ is suitable for not very large problems with dense Jacobian matrices. The computational complexity per iteration is comparable to a singular value decomposition of the Jacobian matrix.\n"
"\n"
"‘lsmr’ is suitable for problems with sparse and large Jacobian matrices. It uses the iterative procedure scipy.sparse.linalg.lsmr for finding a solution of a linear least-squares problem and only requires matrix-vector product evaluations.\n"
"\n"
"If None (default) the solver is chosen based on the type of Jacobian returned on the first iteration."))
        self.LStr_solvercomboBox.setItemText(0, _translate("Dialog", "exact"))
        self.LStr_solvercomboBox.setItemText(1, _translate("Dialog", "lsmr"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ls), _translate("Dialog", "LS"))
        self.groupBox_8.setTitle(_translate("Dialog", "Basin Hopping"))
        self.label_6.setText(_translate("Dialog", "Basin-hopping is a two-phase method that combines a global stepping algorithm with local minimization at each step."))
        self.label_7.setText(_translate("Dialog", "Global Method"))
        self.label_17.setText(_translate("Dialog", "niter"))
        self.basinniterlineEdit.setToolTip(_translate("Dialog", "number of basin-hopping iterations"))
        self.label_18.setText(_translate("Dialog", "T"))
        self.basinTlineEdit.setToolTip(_translate("Dialog", "“temperature” parameter for the accept or reject criterion"))
        self.label_19.setText(_translate("Dialog", "stepsize"))
        self.basinstepsizelineEdit.setToolTip(_translate("Dialog", "Maximum step size for use in the random displacement"))
        self.label_20.setText(_translate("Dialog", "interval"))
        self.basinintervallineEdit.setToolTip(_translate("Dialog", "interval for how often to update the stepsize"))
        self.basinniter_successcheckBox.setToolTip(_translate("Dialog", "Stop the run if the global minimum candidate remains the same for this number of iterations"))
        self.basinniter_successcheckBox.setText(_translate("Dialog", "niter_success"))
        self.basinniter_successlineEdit.setToolTip(_translate("Dialog", "Stop the run if the global minimum candidate remains the same for this number of iterations"))
        self.basinseedcheckBox.setToolTip(_translate("Dialog", "seed for random numbers"))
        self.basinseedcheckBox.setText(_translate("Dialog", "seed"))
        self.basinseedlineEdit.setToolTip(_translate("Dialog", "seed for random numbers"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.basinhopping), _translate("Dialog", "Basin"))
        self.groupBox_7.setTitle(_translate("Dialog", "Dual Annealing"))
        self.label_8.setText(_translate("Dialog", "Find the global minimum of a function using Dual Annealing.\n"
"\n"
""))
        self.label_9.setText(_translate("Dialog", "Global Method"))
        self.label_21.setText(_translate("Dialog", "maxiter"))
        self.annealmaxiterlineEdit.setToolTip(_translate("Dialog", "The maximum number of global search iterations. Default value is 1000"))
        self.label_22.setText(_translate("Dialog", "initial_temp"))
        self.annealinitial_templineEdit.setToolTip(_translate("Dialog", "initial temperature, use higher values to facilitates a wider search of the energy landscape, allowing dual_annealing to escape local minima that it is trapped in. Default value is 5230. Range is (0.01, 5.e4]"))
        self.label_23.setText(_translate("Dialog", "restart_temp_ratio"))
        self.annealrestart_temp_ratiolineEdit.setToolTip(_translate("Dialog", "During the annealing process, temperature is decreasing, when it reaches initial_temp * restart_temp_ratio, the reannealing process is triggered. Default value of the ratio is 2e-5. Range is (0, 1)."))
        self.label_24.setText(_translate("Dialog", "visit"))
        self.annealvisitlineEdit.setToolTip(_translate("Dialog", "Parameter for visiting distribution. Default value is 2.62. Higher values give the visiting distribution a heavier tail, this makes the algorithm jump to a more distant region. The value range is (0, 3]."))
        self.label_25.setText(_translate("Dialog", "accept"))
        self.annealacceptlineEdit.setToolTip(_translate("Dialog", "Parameter for acceptance distribution. It is used to control the probability of acceptance. The lower the acceptance parameter, the smaller the probability of acceptance. Default value is -5.0 with a range (-1e4, -5]."))
        self.label_26.setText(_translate("Dialog", "maxfun"))
        self.annealmaxfunlineEdit.setToolTip(_translate("Dialog", "Soft limit for the number of objective function calls. If the algorithm is in the middle of a local search, this number will be exceeded, the algorithm will stop just after the local search is done. Default value is 1e7."))
        self.annealseedcheckBox.setToolTip(_translate("Dialog", "seed for random numbers"))
        self.annealseedcheckBox.setText(_translate("Dialog", "seed"))
        self.annealseedlineEdit.setToolTip(_translate("Dialog", "seed for random numbers"))
        self.annealno_local_searchcheckBox.setToolTip(_translate("Dialog", "a traditional Generalized Simulated Annealing will be performed with no local search strategy applied"))
        self.annealno_local_searchcheckBox.setText(_translate("Dialog", "no_local_search"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.dualannealing), _translate("Dialog", "Annealing"))
        self.groupBox_9.setTitle(_translate("Dialog", "Differential Evolution"))
        self.label_10.setText(_translate("Dialog", "Stochastic method to find the minimum, and can search large areas of candidate space, but often requires larger numbers of function evaluations than conventional gradient based techniques."))
        self.label_11.setText(_translate("Dialog", "Global Method"))
        self.label_27.setText(_translate("Dialog", "strategy"))
        self.diffevolstrategycomboBox.setToolTip(_translate("Dialog", "The differential evolution strategy to use. The default is ‘best1bin’."))
        self.diffevolstrategycomboBox.setItemText(0, _translate("Dialog", "best1bin"))
        self.diffevolstrategycomboBox.setItemText(1, _translate("Dialog", "best1exp"))
        self.diffevolstrategycomboBox.setItemText(2, _translate("Dialog", "rand1exp"))
        self.diffevolstrategycomboBox.setItemText(3, _translate("Dialog", "randtobest1exp"))
        self.diffevolstrategycomboBox.setItemText(4, _translate("Dialog", "currenttobest1exp"))
        self.diffevolstrategycomboBox.setItemText(5, _translate("Dialog", "best2exp"))
        self.diffevolstrategycomboBox.setItemText(6, _translate("Dialog", "rand2exp"))
        self.diffevolstrategycomboBox.setItemText(7, _translate("Dialog", "randtobest1bin"))
        self.diffevolstrategycomboBox.setItemText(8, _translate("Dialog", "currenttobest1bin"))
        self.diffevolstrategycomboBox.setItemText(9, _translate("Dialog", "best2bin"))
        self.diffevolstrategycomboBox.setItemText(10, _translate("Dialog", "rand2bin"))
        self.diffevolstrategycomboBox.setItemText(11, _translate("Dialog", "rand1bin"))
        self.label_28.setText(_translate("Dialog", "maxiter"))
        self.diffevolmaxiterlineEdit.setToolTip(_translate("Dialog", "The maximum number of generations over which the entire population is evolved. The maximum number of function evaluations (with no polishing) is: (maxiter + 1) * popsize * len(x)"))
        self.label_29.setText(_translate("Dialog", "popsize"))
        self.diffevolpopsizelineEdit.setToolTip(_translate("Dialog", "A multiplier for setting the total population size. The population has popsize * len(x) individuals"))
        self.label_30.setText(_translate("Dialog", "tol"))
        self.diffevoltollineEdit.setToolTip(_translate("Dialog", "Relative tolerance for convergence, the solving stops when np.std(pop) <= atol + tol * np.abs(np.mean(population_energies)), where and atol and tol are the absolute and relative tolerance respectively."))
        self.label_31.setText(_translate("Dialog", "mutation"))
        self.diffevolmutationAlineEdit.setToolTip(_translate("Dialog", "The mutation constant, also known as differential weight.If specified as a tuple (min, max) dithering is employed. Dithering randomly changes the mutation constant on a generation by generation basis. The mutation constant for that generation is taken from U[min, max). Dithering can help speed convergence significantly. Increasing the mutation constant increases the search radius, but will slow down convergence."))
        self.diffevolmutationBlineEdit.setToolTip(_translate("Dialog", "The mutation constant, also known as differential weight.If specified as a tuple (min, max) dithering is employed. Dithering randomly changes the mutation constant on a generation by generation basis. The mutation constant for that generation is taken from U[min, max). Dithering can help speed convergence significantly. Increasing the mutation constant increases the search radius, but will slow down convergence."))
        self.label_32.setText(_translate("Dialog", "recombination"))
        self.diffevolrecombinationlineEdit.setToolTip(_translate("Dialog", "The recombination constant, also known as the crossover probability, in the range [0, 1]. Increasing this value allows a larger number of mutants to progress into the next generation, but at the risk of population stability."))
        self.diffevolseedcheckBox.setToolTip(_translate("Dialog", "Seed for random numbers"))
        self.diffevolseedcheckBox.setText(_translate("Dialog", "seed"))
        self.diffevolseedlineEdit.setToolTip(_translate("Dialog", "Seed for random numbers"))
        self.diffevolpolishcheckBox.setToolTip(_translate("Dialog", "If True (default), then scipy.optimize.minimize with the L-BFGS-B method is used to polish the best population member at the end, which can improve the minimization slightly. If a constrained problem is being studied then the trust-constr method is used instead."))
        self.diffevolpolishcheckBox.setText(_translate("Dialog", "polish"))
        self.label_33.setText(_translate("Dialog", "init"))
        self.diffevolinitcomboBox.setToolTip(_translate("Dialog", "Specify which type of population initialization is performed. The default is ‘latinhypercube’. Latin Hypercube sampling tries to maximize coverage of the available parameter space. ‘random’ initializes the population randomly - this has the drawback that clustering can occur, preventing the whole of parameter space being covered."))
        self.diffevolinitcomboBox.setItemText(0, _translate("Dialog", "latinhypercube"))
        self.diffevolinitcomboBox.setItemText(1, _translate("Dialog", "random"))
        self.label_34.setText(_translate("Dialog", "atol"))
        self.diffevolatollineEdit.setToolTip(_translate("Dialog", "Absolute tolerance for convergence, the solving stops when np.std(pop) <= atol + tol * np.abs(np.mean(population_energies)), where and atol and tol are the absolute and relative tolerance respectively."))
        self.label_35.setText(_translate("Dialog", "updating"))
        self.diffevolupdatingcomboBox.setToolTip(_translate("Dialog", "If \'immediate\', the best solution vector is continuously updated within a single generation. This can lead to faster convergence as trial vectors can take advantage of continuous improvements in the best solution. With \'deferred\', the best solution vector is updated once per generation."))
        self.diffevolupdatingcomboBox.setItemText(0, _translate("Dialog", "immediate"))
        self.diffevolupdatingcomboBox.setItemText(1, _translate("Dialog", "deferred"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.differentialevolution), _translate("Dialog", "Evolution"))
        self.groupBox_12.setTitle(_translate("Dialog", "SHGO"))
        self.label_12.setText(_translate("Dialog", "Finds the global minimum of a function using simplicial homology global optimization."))
        self.label_13.setText(_translate("Dialog", "Global Method"))
        self.label_36.setText(_translate("Dialog", "n"))
        self.SHGOnlineEdit.setToolTip(_translate("Dialog", "Number of sampling points used in the construction of the simplicial complex. Note that this argument is only used for sobol"))
        self.label_37.setText(_translate("Dialog", "iters"))
        self.SHGOiterslineEdit.setToolTip(_translate("Dialog", "Number of iterations used in the construction of the simplicial complex."))
        self.SHGOmaxfevcheckBox.setText(_translate("Dialog", "maxfev"))
        self.SHGOmaxfevlineEdit.setToolTip(_translate("Dialog", "Maximum number of function evaluations in the feasible domain."))
        self.SHGOf_mincheckBox.setToolTip(_translate("Dialog", "Specify the minimum objective function value, if it is known."))
        self.SHGOf_mincheckBox.setText(_translate("Dialog", "f_min"))
        self.SHGOf_minlineEdit.setToolTip(_translate("Dialog", "Specify the minimum objective function value, if it is known."))
        self.label_39.setText(_translate("Dialog", "f_tol"))
        self.SHGOf_tollineEdit.setToolTip(_translate("Dialog", "Precision goal for the value of f in the stopping criterion. Note that the global routine will also terminate if a sampling point in the global routine is within this tolerance.\n"
"\n"
""))
        self.SHGOmaxitercheckBox.setText(_translate("Dialog", "maxiter"))
        self.SHGOmaxiterlineEdit.setToolTip(_translate("Dialog", "Maximum number of iterations to perform."))
        self.SHGOmaxevcheckBox.setToolTip(_translate("Dialog", "Maximum number of sampling evaluations to perform (includes searching in infeasible points)."))
        self.SHGOmaxevcheckBox.setText(_translate("Dialog", "maxev"))
        self.SHGOmaxevlineEdit.setToolTip(_translate("Dialog", "Maximum number of sampling evaluations to perform (includes searching in infeasible points)."))
        self.SHGOmaxtimecheckBox.setToolTip(_translate("Dialog", "Maximum processing runtime allowed"))
        self.SHGOmaxtimecheckBox.setText(_translate("Dialog", "maxtime"))
        self.SHGOmaxtimelineEdit.setToolTip(_translate("Dialog", "Maximum processing runtime allowed"))
        self.SHGOminhgrdcheckBox.setToolTip(_translate("Dialog", "Minimum homology group rank differential. The homology group of the objective function is calculated (approximately) during every iteration. The rank of this group has a one-to-one correspondence with the number of locally convex subdomains in the objective function (after adequate sampling points each of these subdomains contain a unique global minimum). If the difference in the hgr is 0 between iterations for maxhgrd specified iterations the algorithm will terminate."))
        self.SHGOminhgrdcheckBox.setText(_translate("Dialog", "minhgrd"))
        self.SHGOminhgrdlineEdit.setToolTip(_translate("Dialog", "Minimum homology group rank differential. The homology group of the objective function is calculated (approximately) during every iteration. The rank of this group has a one-to-one correspondence with the number of locally convex subdomains in the objective function (after adequate sampling points each of these subdomains contain a unique global minimum). If the difference in the hgr is 0 between iterations for maxhgrd specified iterations the algorithm will terminate."))
        self.SHGOminimize_every_itercheckBox.setToolTip(_translate("Dialog", "If True then promising global sampling points will be passed to a local minimisation routine every iteration. If False then only the final minimiser pool will be run."))
        self.SHGOminimize_every_itercheckBox.setText(_translate("Dialog", "minimize_every_iter"))
        self.SHGOlocal_itercheckBox.setToolTip(_translate("Dialog", "Only evaluate a few of the best minimiser pool candidates every iteration. If False all potential points are passed to the local minimisation routine."))
        self.SHGOlocal_itercheckBox.setText(_translate("Dialog", "local_iter"))
        self.SHGOinfty_constraintscheckBox.setToolTip(_translate("Dialog", "If True then any sampling points generated which are outside will the feasible domain will be saved and given an objective function value of inf. If False then these points will be discarded. Using this functionality could lead to higher performance with respect to function evaluations before the global minimum is found, specifying False will use less memory at the cost of a slight decrease in performance. Defaults to True."))
        self.SHGOinfty_constraintscheckBox.setText(_translate("Dialog", "infty_constraints"))
        self.label_38.setText(_translate("Dialog", "sampling_method"))
        self.SHGOsampling_methodcomboBox.setToolTip(_translate("Dialog", "The default simplicial uses less memory and provides the theoretical guarantee of convergence to the global minimum in finite time. The sobol method is faster in terms of sampling point generation at the cost of higher memory resources and the loss of guaranteed convergence. It is more appropriate for most “easier” problems where the convergence is relatively fast. "))
        self.SHGOsampling_methodcomboBox.setItemText(0, _translate("Dialog", "simplicial"))
        self.SHGOsampling_methodcomboBox.setItemText(1, _translate("Dialog", "sobol"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.shgo), _translate("Dialog", "SHGO"))
        self.groupBox_2.setTitle(_translate("Dialog", "Brute Force"))
        self.label_14.setText(_translate("Dialog", "Minimize a function over a given range by brute force, i.e. it computes the function’s value at each point of a multidimensional grid of points, to find the global minimum of the function. It is inefficient because the number of grid points increases exponentially - the number of grid points to evaluate is Ns ** len(x). Consequently, even with coarse grid spacing, even moderately sized problems can take a long time to run, and/or run into memory limitations.\n"
"\n"
"The program finds the gridpoint at which the lowest value of the objective function occurs. When the global minimum occurs within (or not very far outside) the grid’s boundaries, and the grid is fine enough, that point will be in the neighborhood of the global minimum."))
        self.label_15.setText(_translate("Dialog", "Global Method"))
        self.label_40.setText(_translate("Dialog", "Ns"))
        self.BruteNslineEdit.setToolTip(_translate("Dialog", "Number of grid points along the axes"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.brute), _translate("Dialog", "Brute"))
        self.pushCancel.setText(_translate("Dialog", "Cancel"))
        self.pushOK.setText(_translate("Dialog", "OK"))
import Reptate_rc
