# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'markerSettings.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(355, 483)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Images/Images/new_icons/icons8-color-wheel-2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setObjectName("tabWidget")
        self.data = QtWidgets.QWidget()
        self.data.setObjectName("data")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.data)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox = QtWidgets.QGroupBox(self.data)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.cbSymbolType = QtWidgets.QComboBox(self.groupBox_3)
        self.cbSymbolType.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cbSymbolType.setFont(font)
        self.cbSymbolType.setObjectName("cbSymbolType")
        self.verticalLayout_2.addWidget(self.cbSymbolType)
        self.rbFixedSymbol = QtWidgets.QRadioButton(self.groupBox_3)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.rbFixedSymbol.setFont(font)
        self.rbFixedSymbol.setChecked(True)
        self.rbFixedSymbol.setObjectName("rbFixedSymbol")
        self.verticalLayout_2.addWidget(self.rbFixedSymbol)
        self.rbVariableSymbol = QtWidgets.QRadioButton(self.groupBox_3)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.rbVariableSymbol.setFont(font)
        self.rbVariableSymbol.setChecked(False)
        self.rbVariableSymbol.setObjectName("rbVariableSymbol")
        self.verticalLayout_2.addWidget(self.rbVariableSymbol)
        self.spinBoxLineW = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.spinBoxLineW.setFont(font)
        self.spinBoxLineW.setDecimals(1)
        self.spinBoxLineW.setMinimum(0.1)
        self.spinBoxLineW.setMaximum(10.0)
        self.spinBoxLineW.setSingleStep(0.1)
        self.spinBoxLineW.setProperty("value", 1.0)
        self.spinBoxLineW.setObjectName("spinBoxLineW")
        self.verticalLayout_2.addWidget(self.spinBoxLineW)
        self.horizontalLayout.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.spinBox = QtWidgets.QSpinBox(self.groupBox_4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spinBox.setFont(font)
        self.spinBox.setMaximum(40)
        self.spinBox.setSingleStep(3)
        self.spinBox.setProperty("value", 12)
        self.spinBox.setObjectName("spinBox")
        self.verticalLayout_3.addWidget(self.spinBox)
        self.rbEmpty = QtWidgets.QRadioButton(self.groupBox_4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.rbEmpty.setFont(font)
        self.rbEmpty.setChecked(True)
        self.rbEmpty.setObjectName("rbEmpty")
        self.verticalLayout_3.addWidget(self.rbEmpty)
        self.rbFilled = QtWidgets.QRadioButton(self.groupBox_4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.rbFilled.setFont(font)
        self.rbFilled.setObjectName("rbFilled")
        self.verticalLayout_3.addWidget(self.rbFilled)
        self.horizontalLayout.addWidget(self.groupBox_4)
        self.verticalLayout_6.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.data)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.rbFixedColor = QtWidgets.QRadioButton(self.groupBox_5)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.rbFixedColor.setFont(font)
        self.rbFixedColor.setObjectName("rbFixedColor")
        self.verticalLayout_5.addWidget(self.rbFixedColor)
        self.rbGradientColor = QtWidgets.QRadioButton(self.groupBox_5)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.rbGradientColor.setFont(font)
        self.rbGradientColor.setObjectName("rbGradientColor")
        self.verticalLayout_5.addWidget(self.rbGradientColor)
        self.rbPalette = QtWidgets.QRadioButton(self.groupBox_5)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.rbPalette.setFont(font)
        self.rbPalette.setChecked(True)
        self.rbPalette.setObjectName("rbPalette")
        self.verticalLayout_5.addWidget(self.rbPalette)
        self.horizontalLayout_3.addWidget(self.groupBox_5)
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pickColor1 = QtWidgets.QToolButton(self.groupBox_6)
        self.pickColor1.setEnabled(False)
        self.pickColor1.setObjectName("pickColor1")
        self.gridLayout.addWidget(self.pickColor1, 0, 2, 1, 1)
        self.labelPickedColor1 = QtWidgets.QLabel(self.groupBox_6)
        self.labelPickedColor1.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.labelPickedColor1.setFont(font)
        self.labelPickedColor1.setText("")
        self.labelPickedColor1.setObjectName("labelPickedColor1")
        self.gridLayout.addWidget(self.labelPickedColor1, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_6)
        self.label_4.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_6)
        self.label_5.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.labelPickedColor2 = QtWidgets.QLabel(self.groupBox_6)
        self.labelPickedColor2.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.labelPickedColor2.setFont(font)
        self.labelPickedColor2.setText("")
        self.labelPickedColor2.setObjectName("labelPickedColor2")
        self.horizontalLayout_4.addWidget(self.labelPickedColor2)
        self.pickColor2 = QtWidgets.QToolButton(self.groupBox_6)
        self.pickColor2.setEnabled(False)
        self.pickColor2.setObjectName("pickColor2")
        self.horizontalLayout_4.addWidget(self.pickColor2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.cbPalette = QtWidgets.QComboBox(self.groupBox_6)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cbPalette.setFont(font)
        self.cbPalette.setObjectName("cbPalette")
        self.verticalLayout_4.addWidget(self.cbPalette)
        self.horizontalLayout_3.addWidget(self.groupBox_6)
        self.verticalLayout_6.addWidget(self.groupBox_2)
        self.tabWidget.addTab(self.data, "")
        self.theory = QtWidgets.QWidget()
        self.theory.setObjectName("theory")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.theory)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.groupBox_8 = QtWidgets.QGroupBox(self.theory)
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.cbTheoryLine = QtWidgets.QComboBox(self.groupBox_8)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cbTheoryLine.setFont(font)
        self.cbTheoryLine.setObjectName("cbTheoryLine")
        self.verticalLayout_7.addWidget(self.cbTheoryLine)
        self.sbThLineWidth = QtWidgets.QDoubleSpinBox(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.sbThLineWidth.setFont(font)
        self.sbThLineWidth.setDecimals(1)
        self.sbThLineWidth.setMinimum(0.1)
        self.sbThLineWidth.setMaximum(10.0)
        self.sbThLineWidth.setSingleStep(0.1)
        self.sbThLineWidth.setProperty("value", 1.0)
        self.sbThLineWidth.setObjectName("sbThLineWidth")
        self.verticalLayout_7.addWidget(self.sbThLineWidth)
        self.verticalLayout_10.addWidget(self.groupBox_8)
        self.groupBox_10 = QtWidgets.QGroupBox(self.theory)
        self.groupBox_10.setObjectName("groupBox_10")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.groupBox_10)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.rbThSameColor = QtWidgets.QRadioButton(self.groupBox_10)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.rbThSameColor.setFont(font)
        self.rbThSameColor.setObjectName("rbThSameColor")
        self.verticalLayout_8.addWidget(self.rbThSameColor)
        self.rbThFixedColor = QtWidgets.QRadioButton(self.groupBox_10)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.rbThFixedColor.setFont(font)
        self.rbThFixedColor.setObjectName("rbThFixedColor")
        self.verticalLayout_8.addWidget(self.rbThFixedColor)
        self.verticalLayout_13.addLayout(self.verticalLayout_8)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.labelThcol = QtWidgets.QLabel(self.groupBox_10)
        self.labelThcol.setObjectName("labelThcol")
        self.horizontalLayout_6.addWidget(self.labelThcol)
        self.labelThPickedColor = QtWidgets.QLabel(self.groupBox_10)
        self.labelThPickedColor.setText("")
        self.labelThPickedColor.setObjectName("labelThPickedColor")
        self.horizontalLayout_6.addWidget(self.labelThPickedColor)
        self.pickThColor = QtWidgets.QToolButton(self.groupBox_10)
        self.pickThColor.setObjectName("pickThColor")
        self.horizontalLayout_6.addWidget(self.pickThColor)
        self.verticalLayout_13.addLayout(self.horizontalLayout_6)
        self.verticalLayout_10.addWidget(self.groupBox_10)
        self.tabWidget.addTab(self.theory, "")
        self.legend = QtWidgets.QWidget()
        self.legend.setObjectName("legend")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.legend)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.groupBox_7 = QtWidgets.QGroupBox(self.legend)
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_11.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frameLocation = QtWidgets.QFrame(self.groupBox_7)
        self.frameLocation.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameLocation.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameLocation.setObjectName("frameLocation")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frameLocation)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.frameLocation)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.locationComboBox = QtWidgets.QComboBox(self.frameLocation)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.locationComboBox.setFont(font)
        self.locationComboBox.setObjectName("locationComboBox")
        self.locationComboBox.addItem("")
        self.locationComboBox.addItem("")
        self.locationComboBox.addItem("")
        self.locationComboBox.addItem("")
        self.locationComboBox.addItem("")
        self.locationComboBox.addItem("")
        self.locationComboBox.addItem("")
        self.locationComboBox.addItem("")
        self.locationComboBox.addItem("")
        self.locationComboBox.addItem("")
        self.locationComboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.locationComboBox)
        self.verticalLayout_11.addWidget(self.frameLocation)
        self.frameColumns = QtWidgets.QFrame(self.groupBox_7)
        self.frameColumns.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameColumns.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameColumns.setObjectName("frameColumns")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frameColumns)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_2 = QtWidgets.QLabel(self.frameColumns)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_7.addWidget(self.label_2)
        self.colSpinBox = QtWidgets.QSpinBox(self.frameColumns)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.colSpinBox.setFont(font)
        self.colSpinBox.setMinimum(1)
        self.colSpinBox.setMaximum(10)
        self.colSpinBox.setObjectName("colSpinBox")
        self.horizontalLayout_7.addWidget(self.colSpinBox)
        self.verticalLayout_11.addWidget(self.frameColumns)
        self.frameFont = QtWidgets.QFrame(self.groupBox_7)
        self.frameFont.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameFont.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameFont.setObjectName("frameFont")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frameFont)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_3 = QtWidgets.QLabel(self.frameFont)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_8.addWidget(self.label_3)
        self.fontsizeSpinBox = QtWidgets.QSpinBox(self.frameFont)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.fontsizeSpinBox.setFont(font)
        self.fontsizeSpinBox.setMinimum(1)
        self.fontsizeSpinBox.setObjectName("fontsizeSpinBox")
        self.horizontalLayout_8.addWidget(self.fontsizeSpinBox)
        self.verticalLayout_11.addWidget(self.frameFont)
        self.frameBoolean = QtWidgets.QFrame(self.groupBox_7)
        self.frameBoolean.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameBoolean.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameBoolean.setObjectName("frameBoolean")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frameBoolean)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frameColors = QtWidgets.QFrame(self.frameBoolean)
        self.frameColors.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameColors.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameColors.setObjectName("frameColors")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frameColors)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(20)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setSpacing(0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.facecolorCheckBox = QtWidgets.QCheckBox(self.frameColors)
        self.facecolorCheckBox.setObjectName("facecolorCheckBox")
        self.horizontalLayout_17.addWidget(self.facecolorCheckBox)
        self.labelFaceColor = QtWidgets.QLabel(self.frameColors)
        self.labelFaceColor.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.labelFaceColor.setFont(font)
        self.labelFaceColor.setText("")
        self.labelFaceColor.setObjectName("labelFaceColor")
        self.horizontalLayout_17.addWidget(self.labelFaceColor)
        self.pickFaceColor = QtWidgets.QToolButton(self.frameColors)
        self.pickFaceColor.setEnabled(False)
        self.pickFaceColor.setObjectName("pickFaceColor")
        self.horizontalLayout_17.addWidget(self.pickFaceColor)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setSpacing(0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.edgecolorCheckBox = QtWidgets.QCheckBox(self.frameColors)
        self.edgecolorCheckBox.setObjectName("edgecolorCheckBox")
        self.horizontalLayout_18.addWidget(self.edgecolorCheckBox)
        self.labelEdgeColor = QtWidgets.QLabel(self.frameColors)
        self.labelEdgeColor.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.labelEdgeColor.setFont(font)
        self.labelEdgeColor.setText("")
        self.labelEdgeColor.setObjectName("labelEdgeColor")
        self.horizontalLayout_18.addWidget(self.labelEdgeColor)
        self.pickEdgeColor = QtWidgets.QToolButton(self.frameColors)
        self.pickEdgeColor.setEnabled(False)
        self.pickEdgeColor.setObjectName("pickEdgeColor")
        self.horizontalLayout_18.addWidget(self.pickEdgeColor)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_18)
        self.gridLayout_2.addWidget(self.frameColors, 7, 0, 1, 1)
        self.fancyboxCheckBox = QtWidgets.QCheckBox(self.frameBoolean)
        self.fancyboxCheckBox.setObjectName("fancyboxCheckBox")
        self.gridLayout_2.addWidget(self.fancyboxCheckBox, 2, 0, 1, 1)
        self.markerfirstCheckBox = QtWidgets.QCheckBox(self.frameBoolean)
        self.markerfirstCheckBox.setObjectName("markerfirstCheckBox")
        self.gridLayout_2.addWidget(self.markerfirstCheckBox, 0, 0, 1, 1)
        self.frameonCheckBox = QtWidgets.QCheckBox(self.frameBoolean)
        self.frameonCheckBox.setObjectName("frameonCheckBox")
        self.gridLayout_2.addWidget(self.frameonCheckBox, 1, 0, 1, 1)
        self.frameTransparency = QtWidgets.QFrame(self.frameBoolean)
        self.frameTransparency.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameTransparency.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameTransparency.setObjectName("frameTransparency")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frameTransparency)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.framealphaCheckBox = QtWidgets.QCheckBox(self.frameTransparency)
        self.framealphaCheckBox.setObjectName("framealphaCheckBox")
        self.horizontalLayout_9.addWidget(self.framealphaCheckBox)
        self.framealphaSpinBox = QtWidgets.QDoubleSpinBox(self.frameTransparency)
        self.framealphaSpinBox.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.framealphaSpinBox.setFont(font)
        self.framealphaSpinBox.setMaximum(1.0)
        self.framealphaSpinBox.setSingleStep(0.05)
        self.framealphaSpinBox.setObjectName("framealphaSpinBox")
        self.horizontalLayout_9.addWidget(self.framealphaSpinBox)
        self.gridLayout_2.addWidget(self.frameTransparency, 4, 0, 1, 1)
        self.modeCheckBox = QtWidgets.QCheckBox(self.frameBoolean)
        self.modeCheckBox.setObjectName("modeCheckBox")
        self.gridLayout_2.addWidget(self.modeCheckBox, 9, 0, 1, 1)
        self.shadowCheckBox = QtWidgets.QCheckBox(self.frameBoolean)
        self.shadowCheckBox.setObjectName("shadowCheckBox")
        self.gridLayout_2.addWidget(self.shadowCheckBox, 3, 0, 1, 1)
        self.verticalLayout_11.addWidget(self.frameBoolean)
        self.frameTitle = QtWidgets.QFrame(self.groupBox_7)
        self.frameTitle.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameTitle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameTitle.setObjectName("frameTitle")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frameTitle)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(6)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.legendtitleCheckBox = QtWidgets.QCheckBox(self.frameTitle)
        self.legendtitleCheckBox.setObjectName("legendtitleCheckBox")
        self.horizontalLayout_11.addWidget(self.legendtitleCheckBox)
        self.legendtitleStr = QtWidgets.QLineEdit(self.frameTitle)
        self.legendtitleStr.setEnabled(False)
        self.legendtitleStr.setObjectName("legendtitleStr")
        self.horizontalLayout_11.addWidget(self.legendtitleStr)
        self.verticalLayout_11.addWidget(self.frameTitle)
        self.borderpadframe = QtWidgets.QFrame(self.groupBox_7)
        self.borderpadframe.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.borderpadframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.borderpadframe.setObjectName("borderpadframe")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.borderpadframe)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.borderpadCheckBox = QtWidgets.QCheckBox(self.borderpadframe)
        self.borderpadCheckBox.setObjectName("borderpadCheckBox")
        self.horizontalLayout_13.addWidget(self.borderpadCheckBox)
        self.borderpadSpinBox = QtWidgets.QDoubleSpinBox(self.borderpadframe)
        self.borderpadSpinBox.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.borderpadSpinBox.setFont(font)
        self.borderpadSpinBox.setMaximum(1.0)
        self.borderpadSpinBox.setSingleStep(0.05)
        self.borderpadSpinBox.setObjectName("borderpadSpinBox")
        self.horizontalLayout_13.addWidget(self.borderpadSpinBox)
        self.verticalLayout_11.addWidget(self.borderpadframe)
        self.frame = QtWidgets.QFrame(self.groupBox_7)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.labelspacingCheckBox = QtWidgets.QCheckBox(self.frame)
        self.labelspacingCheckBox.setObjectName("labelspacingCheckBox")
        self.horizontalLayout_14.addWidget(self.labelspacingCheckBox)
        self.labelspacingSpinBox = QtWidgets.QDoubleSpinBox(self.frame)
        self.labelspacingSpinBox.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.labelspacingSpinBox.setFont(font)
        self.labelspacingSpinBox.setMaximum(2.0)
        self.labelspacingSpinBox.setSingleStep(0.1)
        self.labelspacingSpinBox.setObjectName("labelspacingSpinBox")
        self.horizontalLayout_14.addWidget(self.labelspacingSpinBox)
        self.verticalLayout_11.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.groupBox_7)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.handletextpadCheckBox = QtWidgets.QCheckBox(self.frame_2)
        self.handletextpadCheckBox.setObjectName("handletextpadCheckBox")
        self.horizontalLayout_15.addWidget(self.handletextpadCheckBox)
        self.handletextpadSpinBox = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.handletextpadSpinBox.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.handletextpadSpinBox.setFont(font)
        self.handletextpadSpinBox.setMaximum(4.0)
        self.handletextpadSpinBox.setSingleStep(0.1)
        self.handletextpadSpinBox.setObjectName("handletextpadSpinBox")
        self.horizontalLayout_15.addWidget(self.handletextpadSpinBox)
        self.verticalLayout_11.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.groupBox_7)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.columnspacingCheckBox = QtWidgets.QCheckBox(self.frame_3)
        self.columnspacingCheckBox.setObjectName("columnspacingCheckBox")
        self.horizontalLayout_16.addWidget(self.columnspacingCheckBox)
        self.columnspacingSpinBox = QtWidgets.QDoubleSpinBox(self.frame_3)
        self.columnspacingSpinBox.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.columnspacingSpinBox.setFont(font)
        self.columnspacingSpinBox.setMaximum(10.0)
        self.columnspacingSpinBox.setSingleStep(0.25)
        self.columnspacingSpinBox.setObjectName("columnspacingSpinBox")
        self.horizontalLayout_16.addWidget(self.columnspacingSpinBox)
        self.verticalLayout_11.addWidget(self.frame_3)
        self.frameLabelString = QtWidgets.QFrame(self.groupBox_7)
        self.frameLabelString.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameLabelString.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameLabelString.setObjectName("frameLabelString")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frameLabelString)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(6)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.legendlabelCheckBox = QtWidgets.QCheckBox(self.frameLabelString)
        self.legendlabelCheckBox.setObjectName("legendlabelCheckBox")
        self.horizontalLayout_12.addWidget(self.legendlabelCheckBox)
        self.legendlabelStr = QtWidgets.QLineEdit(self.frameLabelString)
        self.legendlabelStr.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.legendlabelStr.setFont(font)
        self.legendlabelStr.setObjectName("legendlabelStr")
        self.horizontalLayout_12.addWidget(self.legendlabelStr)
        self.verticalLayout_11.addWidget(self.frameLabelString)
        self.draggableCheckBox = QtWidgets.QCheckBox(self.groupBox_7)
        self.draggableCheckBox.setObjectName("draggableCheckBox")
        self.verticalLayout_11.addWidget(self.draggableCheckBox)
        self.verticalLayout_9.addWidget(self.groupBox_7)
        self.tabWidget.addTab(self.legend, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushApply = QtWidgets.QPushButton(Dialog)
        self.pushApply.setObjectName("pushApply")
        self.horizontalLayout_5.addWidget(self.pushApply)
        self.pushCancel = QtWidgets.QPushButton(Dialog)
        self.pushCancel.setObjectName("pushCancel")
        self.horizontalLayout_5.addWidget(self.pushCancel)
        self.pushOK = QtWidgets.QPushButton(Dialog)
        self.pushOK.setObjectName("pushOK")
        self.horizontalLayout_5.addWidget(self.pushOK)
        self.verticalLayout.addLayout(self.horizontalLayout_5)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        self.pushOK.clicked.connect(Dialog.accept)
        self.pushCancel.clicked.connect(Dialog.reject)
        self.rbThFixedColor.clicked['bool'].connect(self.pickThColor.setEnabled)
        self.rbFixedSymbol.clicked['bool'].connect(self.cbSymbolType.setEnabled)
        self.rbGradientColor.clicked['bool'].connect(self.cbPalette.setDisabled)
        self.rbPalette.clicked['bool'].connect(self.pickColor1.setDisabled)
        self.rbPalette.clicked['bool'].connect(self.pickColor2.setDisabled)
        self.rbThFixedColor.clicked['bool'].connect(self.labelThcol.setEnabled)
        self.rbThSameColor.clicked['bool'].connect(self.labelThcol.setDisabled)
        self.rbPalette.clicked['bool'].connect(self.label_5.setDisabled)
        self.rbThFixedColor.clicked['bool'].connect(self.labelThPickedColor.setEnabled)
        self.rbThSameColor.clicked['bool'].connect(self.pickThColor.setDisabled)
        self.rbVariableSymbol.clicked['bool'].connect(self.cbSymbolType.setDisabled)
        self.rbThSameColor.clicked['bool'].connect(self.labelThPickedColor.setDisabled)
        self.rbFixedColor.clicked['bool'].connect(self.pickColor2.setDisabled)
        self.rbFixedColor.clicked['bool'].connect(self.cbPalette.setDisabled)
        self.rbFixedColor.clicked['bool'].connect(self.pickColor1.setEnabled)
        self.rbGradientColor.clicked['bool'].connect(self.pickColor1.setEnabled)
        self.rbFixedColor.clicked['bool'].connect(self.labelPickedColor2.setDisabled)
        self.rbGradientColor.clicked['bool'].connect(self.pickColor2.setEnabled)
        self.rbGradientColor.clicked['bool'].connect(self.labelPickedColor2.setEnabled)
        self.rbGradientColor.clicked['bool'].connect(self.labelPickedColor1.setEnabled)
        self.rbGradientColor.clicked['bool'].connect(self.label_4.setEnabled)
        self.rbPalette.clicked['bool'].connect(self.label_4.setDisabled)
        self.rbPalette.clicked['bool'].connect(self.labelPickedColor1.setDisabled)
        self.rbFixedColor.clicked['bool'].connect(self.label_4.setEnabled)
        self.rbPalette.clicked['bool'].connect(self.cbPalette.setEnabled)
        self.rbFixedColor.clicked['bool'].connect(self.label_5.setDisabled)
        self.rbPalette.clicked['bool'].connect(self.labelPickedColor2.setDisabled)
        self.rbGradientColor.clicked['bool'].connect(self.label_5.setEnabled)
        self.rbFixedColor.clicked['bool'].connect(self.labelPickedColor1.setEnabled)
        self.facecolorCheckBox.clicked['bool'].connect(self.labelFaceColor.setEnabled)
        self.facecolorCheckBox.clicked['bool'].connect(self.pickFaceColor.setEnabled)
        self.edgecolorCheckBox.clicked['bool'].connect(self.labelEdgeColor.setEnabled)
        self.edgecolorCheckBox.clicked['bool'].connect(self.pickEdgeColor.setEnabled)
        self.framealphaCheckBox.clicked['bool'].connect(self.framealphaSpinBox.setEnabled)
        self.borderpadCheckBox.clicked['bool'].connect(self.borderpadSpinBox.setEnabled)
        self.labelspacingCheckBox.clicked['bool'].connect(self.labelspacingSpinBox.setEnabled)
        self.handletextpadCheckBox.clicked['bool'].connect(self.handletextpadSpinBox.setEnabled)
        self.columnspacingCheckBox.clicked['bool'].connect(self.columnspacingSpinBox.setEnabled)
        self.legendtitleCheckBox.clicked['bool'].connect(self.legendtitleStr.setEnabled)
        self.legendlabelCheckBox.clicked['bool'].connect(self.legendlabelStr.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dataset Style"))
        self.groupBox.setTitle(_translate("Dialog", "Symbol"))
        self.groupBox_3.setTitle(_translate("Dialog", "Type"))
        self.rbFixedSymbol.setText(_translate("Dialog", "Fixed"))
        self.rbVariableSymbol.setText(_translate("Dialog", "Variable"))
        self.spinBoxLineW.setPrefix(_translate("Dialog", "Line width: "))
        self.groupBox_4.setTitle(_translate("Dialog", "Size"))
        self.rbEmpty.setText(_translate("Dialog", "Empty"))
        self.rbFilled.setText(_translate("Dialog", "Filled"))
        self.groupBox_2.setTitle(_translate("Dialog", "Color"))
        self.groupBox_5.setTitle(_translate("Dialog", "Type"))
        self.rbFixedColor.setText(_translate("Dialog", "Fixed"))
        self.rbGradientColor.setText(_translate("Dialog", "Gradient"))
        self.rbPalette.setText(_translate("Dialog", "Palette"))
        self.groupBox_6.setTitle(_translate("Dialog", "Selection"))
        self.pickColor1.setText(_translate("Dialog", "..."))
        self.label_4.setText(_translate("Dialog", "Color 1"))
        self.label_5.setText(_translate("Dialog", "Color 2"))
        self.pickColor2.setText(_translate("Dialog", "..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.data), _translate("Dialog", "Data"))
        self.groupBox_8.setTitle(_translate("Dialog", "Line Type"))
        self.sbThLineWidth.setPrefix(_translate("Dialog", "Line width: "))
        self.groupBox_10.setTitle(_translate("Dialog", "Color"))
        self.rbThSameColor.setText(_translate("Dialog", "Same as Data"))
        self.rbThFixedColor.setText(_translate("Dialog", "Fixed"))
        self.labelThcol.setText(_translate("Dialog", "Color"))
        self.pickThColor.setText(_translate("Dialog", "..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.theory), _translate("Dialog", "Theory"))
        self.groupBox_7.setTitle(_translate("Dialog", "Legend Properties"))
        self.label.setToolTip(_translate("Dialog", "The location of the legend"))
        self.label.setText(_translate("Dialog", "Location"))
        self.locationComboBox.setItemText(0, _translate("Dialog", "best"))
        self.locationComboBox.setItemText(1, _translate("Dialog", "upper right"))
        self.locationComboBox.setItemText(2, _translate("Dialog", "upper left"))
        self.locationComboBox.setItemText(3, _translate("Dialog", "lower left"))
        self.locationComboBox.setItemText(4, _translate("Dialog", "lower right"))
        self.locationComboBox.setItemText(5, _translate("Dialog", "right"))
        self.locationComboBox.setItemText(6, _translate("Dialog", "center left"))
        self.locationComboBox.setItemText(7, _translate("Dialog", "center right"))
        self.locationComboBox.setItemText(8, _translate("Dialog", "lower center"))
        self.locationComboBox.setItemText(9, _translate("Dialog", "upper center"))
        self.locationComboBox.setItemText(10, _translate("Dialog", "center"))
        self.label_2.setToolTip(_translate("Dialog", "The number of columns that the legend has"))
        self.label_2.setText(_translate("Dialog", "Number of columns"))
        self.label_3.setToolTip(_translate("Dialog", "Font size of the legend"))
        self.label_3.setText(_translate("Dialog", "Font Size"))
        self.facecolorCheckBox.setToolTip(_translate("Dialog", "Legend’s background color"))
        self.facecolorCheckBox.setText(_translate("Dialog", "Face Color"))
        self.pickFaceColor.setText(_translate("Dialog", "..."))
        self.edgecolorCheckBox.setToolTip(_translate("Dialog", "Legend’s background patch edge color"))
        self.edgecolorCheckBox.setText(_translate("Dialog", "Edge Color"))
        self.pickEdgeColor.setText(_translate("Dialog", "..."))
        self.fancyboxCheckBox.setToolTip(_translate("Dialog", "Draw legend frame with round edges?"))
        self.fancyboxCheckBox.setText(_translate("Dialog", "Francy Box"))
        self.markerfirstCheckBox.setToolTip(_translate("Dialog", "If True, legend marker is placed to the left of the legend label"))
        self.markerfirstCheckBox.setText(_translate("Dialog", "Marker First"))
        self.frameonCheckBox.setToolTip(_translate("Dialog", "Draw the legend inside a patch (frame)?"))
        self.frameonCheckBox.setText(_translate("Dialog", "Draw Frame"))
        self.framealphaCheckBox.setToolTip(_translate("Dialog", "Alpha transparency of the legend’s background"))
        self.framealphaCheckBox.setText(_translate("Dialog", "Transparency"))
        self.modeCheckBox.setToolTip(_translate("Dialog", "Expand the legend horizontally to fill the axes area?"))
        self.modeCheckBox.setText(_translate("Dialog", "Expand mode"))
        self.shadowCheckBox.setToolTip(_translate("Dialog", "Draw a shadow behind the legend?"))
        self.shadowCheckBox.setText(_translate("Dialog", "Shadow"))
        self.legendtitleCheckBox.setToolTip(_translate("Dialog", "Set Legend Title (default None)"))
        self.legendtitleCheckBox.setText(_translate("Dialog", "Legend Title"))
        self.legendtitleStr.setToolTip(_translate("Dialog", "Legend’s title (none if left empty)"))
        self.borderpadCheckBox.setToolTip(_translate("Dialog", "Fractional whitespace inside the legend border"))
        self.borderpadCheckBox.setText(_translate("Dialog", "Legend Border Pad"))
        self.labelspacingCheckBox.setText(_translate("Dialog", "Space bertween entries"))
        self.handletextpadCheckBox.setText(_translate("Dialog", "Space handle-label"))
        self.columnspacingCheckBox.setText(_translate("Dialog", "Space between columns"))
        self.legendlabelCheckBox.setToolTip(_translate("Dialog", "Set Legend label (default = all basic file parameters with values)"))
        self.legendlabelCheckBox.setText(_translate("Dialog", "Legend Labels"))
        self.legendlabelStr.setToolTip(_translate("Dialog", "default = all basic file parameters with values"))
        self.legendlabelStr.setText(_translate("Dialog", "default"))
        self.draggableCheckBox.setToolTip(_translate("Dialog", "Can the user move the legend with the mouse?"))
        self.draggableCheckBox.setText(_translate("Dialog", "Draggable Legend"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.legend), _translate("Dialog", "Legend"))
        self.pushApply.setText(_translate("Dialog", "Apply"))
        self.pushCancel.setText(_translate("Dialog", "Cancel"))
        self.pushOK.setText(_translate("Dialog", "OK"))

import Reptate_rc
