# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'markerSettings.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(451, 582)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Images/Images/new_icons/icons8-color-wheel-2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setObjectName("tabWidget")
        self.data = QtWidgets.QWidget()
        self.data.setObjectName("data")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.data)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox = QtWidgets.QGroupBox(self.data)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.cbSymbolType = QtWidgets.QComboBox(self.groupBox_3)
        self.cbSymbolType.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cbSymbolType.setFont(font)
        self.cbSymbolType.setObjectName("cbSymbolType")
        self.verticalLayout_2.addWidget(self.cbSymbolType)
        self.rbFixedSymbol = QtWidgets.QRadioButton(self.groupBox_3)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.rbFixedSymbol.setFont(font)
        self.rbFixedSymbol.setChecked(True)
        self.rbFixedSymbol.setObjectName("rbFixedSymbol")
        self.verticalLayout_2.addWidget(self.rbFixedSymbol)
        self.rbVariableSymbol = QtWidgets.QRadioButton(self.groupBox_3)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.rbVariableSymbol.setFont(font)
        self.rbVariableSymbol.setChecked(False)
        self.rbVariableSymbol.setObjectName("rbVariableSymbol")
        self.verticalLayout_2.addWidget(self.rbVariableSymbol)
        self.spinBoxLineW = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.spinBoxLineW.setFont(font)
        self.spinBoxLineW.setDecimals(1)
        self.spinBoxLineW.setMinimum(0.1)
        self.spinBoxLineW.setMaximum(10.0)
        self.spinBoxLineW.setSingleStep(0.1)
        self.spinBoxLineW.setProperty("value", 1.0)
        self.spinBoxLineW.setObjectName("spinBoxLineW")
        self.verticalLayout_2.addWidget(self.spinBoxLineW)
        self.horizontalLayout.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.spinBox = QtWidgets.QSpinBox(self.groupBox_4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spinBox.setFont(font)
        self.spinBox.setMaximum(40)
        self.spinBox.setSingleStep(3)
        self.spinBox.setProperty("value", 12)
        self.spinBox.setObjectName("spinBox")
        self.verticalLayout_3.addWidget(self.spinBox)
        self.rbEmpty = QtWidgets.QRadioButton(self.groupBox_4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.rbEmpty.setFont(font)
        self.rbEmpty.setChecked(True)
        self.rbEmpty.setObjectName("rbEmpty")
        self.verticalLayout_3.addWidget(self.rbEmpty)
        self.rbFilled = QtWidgets.QRadioButton(self.groupBox_4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.rbFilled.setFont(font)
        self.rbFilled.setObjectName("rbFilled")
        self.verticalLayout_3.addWidget(self.rbFilled)
        self.horizontalLayout.addWidget(self.groupBox_4)
        self.verticalLayout_6.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.data)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.rbFixedColor = QtWidgets.QRadioButton(self.groupBox_5)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.rbFixedColor.setFont(font)
        self.rbFixedColor.setObjectName("rbFixedColor")
        self.verticalLayout_5.addWidget(self.rbFixedColor)
        self.rbGradientColor = QtWidgets.QRadioButton(self.groupBox_5)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.rbGradientColor.setFont(font)
        self.rbGradientColor.setObjectName("rbGradientColor")
        self.verticalLayout_5.addWidget(self.rbGradientColor)
        self.rbPalette = QtWidgets.QRadioButton(self.groupBox_5)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.rbPalette.setFont(font)
        self.rbPalette.setChecked(True)
        self.rbPalette.setObjectName("rbPalette")
        self.verticalLayout_5.addWidget(self.rbPalette)
        self.horizontalLayout_3.addWidget(self.groupBox_5)
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pickColor1 = QtWidgets.QToolButton(self.groupBox_6)
        self.pickColor1.setEnabled(False)
        self.pickColor1.setObjectName("pickColor1")
        self.gridLayout.addWidget(self.pickColor1, 0, 2, 1, 1)
        self.labelPickedColor1 = QtWidgets.QLabel(self.groupBox_6)
        self.labelPickedColor1.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.labelPickedColor1.setFont(font)
        self.labelPickedColor1.setText("")
        self.labelPickedColor1.setObjectName("labelPickedColor1")
        self.gridLayout.addWidget(self.labelPickedColor1, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_6)
        self.label_4.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_6)
        self.label_5.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.labelPickedColor2 = QtWidgets.QLabel(self.groupBox_6)
        self.labelPickedColor2.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.labelPickedColor2.setFont(font)
        self.labelPickedColor2.setText("")
        self.labelPickedColor2.setObjectName("labelPickedColor2")
        self.horizontalLayout_4.addWidget(self.labelPickedColor2)
        self.pickColor2 = QtWidgets.QToolButton(self.groupBox_6)
        self.pickColor2.setEnabled(False)
        self.pickColor2.setObjectName("pickColor2")
        self.horizontalLayout_4.addWidget(self.pickColor2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.cbPalette = QtWidgets.QComboBox(self.groupBox_6)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cbPalette.setFont(font)
        self.cbPalette.setObjectName("cbPalette")
        self.verticalLayout_4.addWidget(self.cbPalette)
        self.horizontalLayout_3.addWidget(self.groupBox_6)
        self.verticalLayout_6.addWidget(self.groupBox_2)
        self.tabWidget.addTab(self.data, "")
        self.theory = QtWidgets.QWidget()
        self.theory.setObjectName("theory")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.theory)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.groupBox_8 = QtWidgets.QGroupBox(self.theory)
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.cbTheoryLine = QtWidgets.QComboBox(self.groupBox_8)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cbTheoryLine.setFont(font)
        self.cbTheoryLine.setObjectName("cbTheoryLine")
        self.verticalLayout_7.addWidget(self.cbTheoryLine)
        self.sbThLineWidth = QtWidgets.QDoubleSpinBox(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.sbThLineWidth.setFont(font)
        self.sbThLineWidth.setDecimals(1)
        self.sbThLineWidth.setMinimum(0.1)
        self.sbThLineWidth.setMaximum(10.0)
        self.sbThLineWidth.setSingleStep(0.1)
        self.sbThLineWidth.setProperty("value", 1.0)
        self.sbThLineWidth.setObjectName("sbThLineWidth")
        self.verticalLayout_7.addWidget(self.sbThLineWidth)
        self.verticalLayout_10.addWidget(self.groupBox_8)
        self.groupBox_10 = QtWidgets.QGroupBox(self.theory)
        self.groupBox_10.setObjectName("groupBox_10")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.groupBox_10)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.rbThSameColor = QtWidgets.QRadioButton(self.groupBox_10)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.rbThSameColor.setFont(font)
        self.rbThSameColor.setObjectName("rbThSameColor")
        self.verticalLayout_8.addWidget(self.rbThSameColor)
        self.rbThFixedColor = QtWidgets.QRadioButton(self.groupBox_10)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.rbThFixedColor.setFont(font)
        self.rbThFixedColor.setObjectName("rbThFixedColor")
        self.verticalLayout_8.addWidget(self.rbThFixedColor)
        self.verticalLayout_13.addLayout(self.verticalLayout_8)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.labelThcol = QtWidgets.QLabel(self.groupBox_10)
        self.labelThcol.setObjectName("labelThcol")
        self.horizontalLayout_6.addWidget(self.labelThcol)
        self.labelThPickedColor = QtWidgets.QLabel(self.groupBox_10)
        self.labelThPickedColor.setText("")
        self.labelThPickedColor.setObjectName("labelThPickedColor")
        self.horizontalLayout_6.addWidget(self.labelThPickedColor)
        self.pickThColor = QtWidgets.QToolButton(self.groupBox_10)
        self.pickThColor.setObjectName("pickThColor")
        self.horizontalLayout_6.addWidget(self.pickThColor)
        self.verticalLayout_13.addLayout(self.horizontalLayout_6)
        self.verticalLayout_10.addWidget(self.groupBox_10)
        self.tabWidget.addTab(self.theory, "")
        self.legend = QtWidgets.QWidget()
        self.legend.setObjectName("legend")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.legend)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.cb_show_legend = QtWidgets.QCheckBox(self.legend)
        self.cb_show_legend.setChecked(False)
        self.cb_show_legend.setTristate(False)
        self.cb_show_legend.setObjectName("cb_show_legend")
        self.verticalLayout_9.addWidget(self.cb_show_legend)
        self.groupBox_7 = QtWidgets.QGroupBox(self.legend)
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_11.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frameLocation = QtWidgets.QFrame(self.groupBox_7)
        self.frameLocation.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameLocation.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameLocation.setObjectName("frameLocation")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frameLocation)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.frameLocation)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.locationComboBox = QtWidgets.QComboBox(self.frameLocation)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.locationComboBox.setFont(font)
        self.locationComboBox.setObjectName("locationComboBox")
        self.locationComboBox.addItem("")
        self.locationComboBox.addItem("")
        self.locationComboBox.addItem("")
        self.locationComboBox.addItem("")
        self.locationComboBox.addItem("")
        self.locationComboBox.addItem("")
        self.locationComboBox.addItem("")
        self.locationComboBox.addItem("")
        self.locationComboBox.addItem("")
        self.locationComboBox.addItem("")
        self.locationComboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.locationComboBox)
        self.verticalLayout_11.addWidget(self.frameLocation)
        self.frameColumns = QtWidgets.QFrame(self.groupBox_7)
        self.frameColumns.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameColumns.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameColumns.setObjectName("frameColumns")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frameColumns)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_2 = QtWidgets.QLabel(self.frameColumns)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_7.addWidget(self.label_2)
        self.colSpinBox = QtWidgets.QSpinBox(self.frameColumns)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.colSpinBox.setFont(font)
        self.colSpinBox.setMinimum(1)
        self.colSpinBox.setMaximum(10)
        self.colSpinBox.setObjectName("colSpinBox")
        self.horizontalLayout_7.addWidget(self.colSpinBox)
        self.verticalLayout_11.addWidget(self.frameColumns)
        self.frameFont = QtWidgets.QFrame(self.groupBox_7)
        self.frameFont.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameFont.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameFont.setObjectName("frameFont")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frameFont)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_3 = QtWidgets.QLabel(self.frameFont)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_8.addWidget(self.label_3)
        self.fontsizeSpinBox = QtWidgets.QSpinBox(self.frameFont)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.fontsizeSpinBox.setFont(font)
        self.fontsizeSpinBox.setMinimum(1)
        self.fontsizeSpinBox.setObjectName("fontsizeSpinBox")
        self.horizontalLayout_8.addWidget(self.fontsizeSpinBox)
        self.verticalLayout_11.addWidget(self.frameFont)
        self.frameBoolean = QtWidgets.QFrame(self.groupBox_7)
        self.frameBoolean.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameBoolean.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameBoolean.setObjectName("frameBoolean")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frameBoolean)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.fancyboxCheckBox = QtWidgets.QCheckBox(self.frameBoolean)
        self.fancyboxCheckBox.setObjectName("fancyboxCheckBox")
        self.gridLayout_2.addWidget(self.fancyboxCheckBox, 2, 0, 1, 1)
        self.markerfirstCheckBox = QtWidgets.QCheckBox(self.frameBoolean)
        self.markerfirstCheckBox.setObjectName("markerfirstCheckBox")
        self.gridLayout_2.addWidget(self.markerfirstCheckBox, 0, 0, 1, 1)
        self.modeCheckBox = QtWidgets.QCheckBox(self.frameBoolean)
        self.modeCheckBox.setObjectName("modeCheckBox")
        self.gridLayout_2.addWidget(self.modeCheckBox, 9, 0, 1, 1)
        self.shadowCheckBox = QtWidgets.QCheckBox(self.frameBoolean)
        self.shadowCheckBox.setObjectName("shadowCheckBox")
        self.gridLayout_2.addWidget(self.shadowCheckBox, 3, 0, 1, 1)
        self.frameColors = QtWidgets.QFrame(self.frameBoolean)
        self.frameColors.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameColors.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameColors.setObjectName("frameColors")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frameColors)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(20)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setSpacing(0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.facecolorCheckBox = QtWidgets.QCheckBox(self.frameColors)
        self.facecolorCheckBox.setObjectName("facecolorCheckBox")
        self.horizontalLayout_17.addWidget(self.facecolorCheckBox)
        self.labelFaceColor = QtWidgets.QLabel(self.frameColors)
        self.labelFaceColor.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.labelFaceColor.setFont(font)
        self.labelFaceColor.setText("")
        self.labelFaceColor.setObjectName("labelFaceColor")
        self.horizontalLayout_17.addWidget(self.labelFaceColor)
        self.pickFaceColor = QtWidgets.QToolButton(self.frameColors)
        self.pickFaceColor.setEnabled(False)
        self.pickFaceColor.setObjectName("pickFaceColor")
        self.horizontalLayout_17.addWidget(self.pickFaceColor)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setSpacing(0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.edgecolorCheckBox = QtWidgets.QCheckBox(self.frameColors)
        self.edgecolorCheckBox.setObjectName("edgecolorCheckBox")
        self.horizontalLayout_18.addWidget(self.edgecolorCheckBox)
        self.labelEdgeColor = QtWidgets.QLabel(self.frameColors)
        self.labelEdgeColor.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.labelEdgeColor.setFont(font)
        self.labelEdgeColor.setText("")
        self.labelEdgeColor.setObjectName("labelEdgeColor")
        self.horizontalLayout_18.addWidget(self.labelEdgeColor)
        self.pickEdgeColor = QtWidgets.QToolButton(self.frameColors)
        self.pickEdgeColor.setEnabled(False)
        self.pickEdgeColor.setObjectName("pickEdgeColor")
        self.horizontalLayout_18.addWidget(self.pickEdgeColor)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_18)
        self.gridLayout_2.addWidget(self.frameColors, 7, 0, 1, 1)
        self.frameTransparency = QtWidgets.QFrame(self.frameBoolean)
        self.frameTransparency.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameTransparency.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameTransparency.setObjectName("frameTransparency")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frameTransparency)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.framealphaCheckBox = QtWidgets.QCheckBox(self.frameTransparency)
        self.framealphaCheckBox.setObjectName("framealphaCheckBox")
        self.horizontalLayout_9.addWidget(self.framealphaCheckBox)
        self.framealphaSpinBox = QtWidgets.QDoubleSpinBox(self.frameTransparency)
        self.framealphaSpinBox.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.framealphaSpinBox.setFont(font)
        self.framealphaSpinBox.setMaximum(1.0)
        self.framealphaSpinBox.setSingleStep(0.05)
        self.framealphaSpinBox.setObjectName("framealphaSpinBox")
        self.horizontalLayout_9.addWidget(self.framealphaSpinBox)
        self.gridLayout_2.addWidget(self.frameTransparency, 4, 0, 1, 1)
        self.frameonCheckBox = QtWidgets.QCheckBox(self.frameBoolean)
        self.frameonCheckBox.setObjectName("frameonCheckBox")
        self.gridLayout_2.addWidget(self.frameonCheckBox, 1, 0, 1, 1)
        self.verticalLayout_11.addWidget(self.frameBoolean)
        self.frameTitle = QtWidgets.QFrame(self.groupBox_7)
        self.frameTitle.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameTitle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameTitle.setObjectName("frameTitle")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frameTitle)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.legendtitleCheckBox = QtWidgets.QCheckBox(self.frameTitle)
        self.legendtitleCheckBox.setObjectName("legendtitleCheckBox")
        self.horizontalLayout_11.addWidget(self.legendtitleCheckBox)
        self.legendtitleStr = QtWidgets.QLineEdit(self.frameTitle)
        self.legendtitleStr.setEnabled(False)
        self.legendtitleStr.setObjectName("legendtitleStr")
        self.horizontalLayout_11.addWidget(self.legendtitleStr)
        self.verticalLayout_11.addWidget(self.frameTitle)
        self.borderpadframe = QtWidgets.QFrame(self.groupBox_7)
        self.borderpadframe.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.borderpadframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.borderpadframe.setObjectName("borderpadframe")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.borderpadframe)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.borderpadCheckBox = QtWidgets.QCheckBox(self.borderpadframe)
        self.borderpadCheckBox.setObjectName("borderpadCheckBox")
        self.horizontalLayout_13.addWidget(self.borderpadCheckBox)
        self.borderpadSpinBox = QtWidgets.QDoubleSpinBox(self.borderpadframe)
        self.borderpadSpinBox.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.borderpadSpinBox.setFont(font)
        self.borderpadSpinBox.setMaximum(1.0)
        self.borderpadSpinBox.setSingleStep(0.05)
        self.borderpadSpinBox.setObjectName("borderpadSpinBox")
        self.horizontalLayout_13.addWidget(self.borderpadSpinBox)
        self.verticalLayout_11.addWidget(self.borderpadframe)
        self.frame = QtWidgets.QFrame(self.groupBox_7)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.labelspacingCheckBox = QtWidgets.QCheckBox(self.frame)
        self.labelspacingCheckBox.setObjectName("labelspacingCheckBox")
        self.horizontalLayout_14.addWidget(self.labelspacingCheckBox)
        self.labelspacingSpinBox = QtWidgets.QDoubleSpinBox(self.frame)
        self.labelspacingSpinBox.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.labelspacingSpinBox.setFont(font)
        self.labelspacingSpinBox.setMaximum(2.0)
        self.labelspacingSpinBox.setSingleStep(0.1)
        self.labelspacingSpinBox.setObjectName("labelspacingSpinBox")
        self.horizontalLayout_14.addWidget(self.labelspacingSpinBox)
        self.verticalLayout_11.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.groupBox_7)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.handletextpadCheckBox = QtWidgets.QCheckBox(self.frame_2)
        self.handletextpadCheckBox.setObjectName("handletextpadCheckBox")
        self.horizontalLayout_15.addWidget(self.handletextpadCheckBox)
        self.handletextpadSpinBox = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.handletextpadSpinBox.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.handletextpadSpinBox.setFont(font)
        self.handletextpadSpinBox.setMaximum(4.0)
        self.handletextpadSpinBox.setSingleStep(0.1)
        self.handletextpadSpinBox.setObjectName("handletextpadSpinBox")
        self.horizontalLayout_15.addWidget(self.handletextpadSpinBox)
        self.verticalLayout_11.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.groupBox_7)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.columnspacingCheckBox = QtWidgets.QCheckBox(self.frame_3)
        self.columnspacingCheckBox.setObjectName("columnspacingCheckBox")
        self.horizontalLayout_16.addWidget(self.columnspacingCheckBox)
        self.columnspacingSpinBox = QtWidgets.QDoubleSpinBox(self.frame_3)
        self.columnspacingSpinBox.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.columnspacingSpinBox.setFont(font)
        self.columnspacingSpinBox.setMaximum(10.0)
        self.columnspacingSpinBox.setSingleStep(0.25)
        self.columnspacingSpinBox.setObjectName("columnspacingSpinBox")
        self.horizontalLayout_16.addWidget(self.columnspacingSpinBox)
        self.verticalLayout_11.addWidget(self.frame_3)
        self.frameLabelString = QtWidgets.QFrame(self.groupBox_7)
        self.frameLabelString.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameLabelString.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameLabelString.setObjectName("frameLabelString")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frameLabelString)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.legendlabelCheckBox = QtWidgets.QCheckBox(self.frameLabelString)
        self.legendlabelCheckBox.setObjectName("legendlabelCheckBox")
        self.horizontalLayout_12.addWidget(self.legendlabelCheckBox)
        self.legendlabelStr = QtWidgets.QLineEdit(self.frameLabelString)
        self.legendlabelStr.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.legendlabelStr.setFont(font)
        self.legendlabelStr.setObjectName("legendlabelStr")
        self.horizontalLayout_12.addWidget(self.legendlabelStr)
        self.verticalLayout_11.addWidget(self.frameLabelString)
        self.draggableCheckBox = QtWidgets.QCheckBox(self.groupBox_7)
        self.draggableCheckBox.setObjectName("draggableCheckBox")
        self.verticalLayout_11.addWidget(self.draggableCheckBox)
        self.verticalLayout_9.addWidget(self.groupBox_7)
        self.tabWidget.addTab(self.legend, "")
        self.annotations = QtWidgets.QWidget()
        self.annotations.setObjectName("annotations")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.annotations)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.groupBox_9 = QtWidgets.QGroupBox(self.annotations)
        self.groupBox_9.setObjectName("groupBox_9")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_14.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.frame_5 = QtWidgets.QFrame(self.groupBox_9)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.frame_7 = QtWidgets.QFrame(self.frame_5)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_10 = QtWidgets.QLabel(self.frame_7)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_21.addWidget(self.label_10)
        self.rotationSpinBox = QtWidgets.QDoubleSpinBox(self.frame_7)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.rotationSpinBox.setFont(font)
        self.rotationSpinBox.setDecimals(1)
        self.rotationSpinBox.setMaximum(360.0)
        self.rotationSpinBox.setObjectName("rotationSpinBox")
        self.horizontalLayout_21.addWidget(self.rotationSpinBox)
        self.verticalLayout_15.addWidget(self.frame_7)
        self.verticalLayout_14.addWidget(self.frame_5)
        self.frame_8 = QtWidgets.QFrame(self.groupBox_9)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_11 = QtWidgets.QLabel(self.frame_8)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_16.addWidget(self.label_11)
        self.frame_9 = QtWidgets.QFrame(self.frame_8)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_12 = QtWidgets.QLabel(self.frame_9)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_22.addWidget(self.label_12)
        self.hacomboBox = QtWidgets.QComboBox(self.frame_9)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.hacomboBox.setFont(font)
        self.hacomboBox.setObjectName("hacomboBox")
        self.hacomboBox.addItem("")
        self.hacomboBox.addItem("")
        self.hacomboBox.addItem("")
        self.horizontalLayout_22.addWidget(self.hacomboBox)
        self.label_13 = QtWidgets.QLabel(self.frame_9)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_22.addWidget(self.label_13)
        self.vacomboBox = QtWidgets.QComboBox(self.frame_9)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.vacomboBox.setFont(font)
        self.vacomboBox.setObjectName("vacomboBox")
        self.vacomboBox.addItem("")
        self.vacomboBox.addItem("")
        self.vacomboBox.addItem("")
        self.vacomboBox.addItem("")
        self.horizontalLayout_22.addWidget(self.vacomboBox)
        self.verticalLayout_16.addWidget(self.frame_9)
        self.verticalLayout_14.addWidget(self.frame_8)
        self.frame_10 = QtWidgets.QFrame(self.groupBox_9)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setSpacing(0)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_7 = QtWidgets.QLabel(self.frame_10)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_23.addWidget(self.label_7)
        self.labelFontColor = QtWidgets.QLabel(self.frame_10)
        self.labelFontColor.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.labelFontColor.setFont(font)
        self.labelFontColor.setText("")
        self.labelFontColor.setObjectName("labelFontColor")
        self.horizontalLayout_23.addWidget(self.labelFontColor)
        self.pickFontColor = QtWidgets.QToolButton(self.frame_10)
        self.pickFontColor.setEnabled(True)
        self.pickFontColor.setObjectName("pickFontColor")
        self.horizontalLayout_23.addWidget(self.pickFontColor)
        self.horizontalLayout_25.addLayout(self.horizontalLayout_23)
        self.verticalLayout_14.addWidget(self.frame_10)
        self.frame_11 = QtWidgets.QFrame(self.groupBox_9)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_14 = QtWidgets.QLabel(self.frame_11)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_26.addWidget(self.label_14)
        self.fontweightComboBox = QtWidgets.QComboBox(self.frame_11)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.fontweightComboBox.setFont(font)
        self.fontweightComboBox.setObjectName("fontweightComboBox")
        self.fontweightComboBox.addItem("")
        self.fontweightComboBox.addItem("")
        self.fontweightComboBox.addItem("")
        self.fontweightComboBox.addItem("")
        self.fontweightComboBox.addItem("")
        self.fontweightComboBox.addItem("")
        self.fontweightComboBox.addItem("")
        self.fontweightComboBox.addItem("")
        self.fontweightComboBox.addItem("")
        self.fontweightComboBox.addItem("")
        self.fontweightComboBox.addItem("")
        self.fontweightComboBox.addItem("")
        self.fontweightComboBox.addItem("")
        self.fontweightComboBox.addItem("")
        self.horizontalLayout_26.addWidget(self.fontweightComboBox)
        self.label_15 = QtWidgets.QLabel(self.frame_11)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_26.addWidget(self.label_15)
        self.fontstyleComboBox = QtWidgets.QComboBox(self.frame_11)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.fontstyleComboBox.setFont(font)
        self.fontstyleComboBox.setObjectName("fontstyleComboBox")
        self.fontstyleComboBox.addItem("")
        self.fontstyleComboBox.addItem("")
        self.fontstyleComboBox.addItem("")
        self.horizontalLayout_26.addWidget(self.fontstyleComboBox)
        self.verticalLayout_14.addWidget(self.frame_11)
        self.frame_12 = QtWidgets.QFrame(self.groupBox_9)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_16 = QtWidgets.QLabel(self.frame_12)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_27.addWidget(self.label_16)
        self.fontsizeannotationSpinBox = QtWidgets.QSpinBox(self.frame_12)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.fontsizeannotationSpinBox.setFont(font)
        self.fontsizeannotationSpinBox.setMinimum(1)
        self.fontsizeannotationSpinBox.setObjectName("fontsizeannotationSpinBox")
        self.horizontalLayout_27.addWidget(self.fontsizeannotationSpinBox)
        self.verticalLayout_14.addWidget(self.frame_12)
        self.frame_13 = QtWidgets.QFrame(self.groupBox_9)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_6 = QtWidgets.QLabel(self.frame_13)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_28.addWidget(self.label_6)
        self.framealphaannotationSpinBox = QtWidgets.QDoubleSpinBox(self.frame_13)
        self.framealphaannotationSpinBox.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.framealphaannotationSpinBox.setFont(font)
        self.framealphaannotationSpinBox.setMaximum(1.0)
        self.framealphaannotationSpinBox.setSingleStep(0.05)
        self.framealphaannotationSpinBox.setObjectName("framealphaannotationSpinBox")
        self.horizontalLayout_28.addWidget(self.framealphaannotationSpinBox)
        self.verticalLayout_14.addWidget(self.frame_13)
        self.frame_14 = QtWidgets.QFrame(self.groupBox_9)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_17 = QtWidgets.QLabel(self.frame_14)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_29.addWidget(self.label_17)
        self.fontfamilyComboBox = QtWidgets.QComboBox(self.frame_14)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.fontfamilyComboBox.setFont(font)
        self.fontfamilyComboBox.setObjectName("fontfamilyComboBox")
        self.fontfamilyComboBox.addItem("")
        self.fontfamilyComboBox.addItem("")
        self.fontfamilyComboBox.addItem("")
        self.fontfamilyComboBox.addItem("")
        self.fontfamilyComboBox.addItem("")
        self.horizontalLayout_29.addWidget(self.fontfamilyComboBox)
        self.verticalLayout_14.addWidget(self.frame_14)
        self.verticalLayout_12.addWidget(self.groupBox_9)
        self.tabWidget.addTab(self.annotations, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.groupBox_12 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_12.setObjectName("groupBox_12")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.groupBox_12)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.labelFontColor_label = QtWidgets.QLabel(self.groupBox_12)
        self.labelFontColor_label.setText("")
        self.labelFontColor_label.setObjectName("labelFontColor_label")
        self.gridLayout_3.addWidget(self.labelFontColor_label, 0, 1, 1, 1)
        self.pickFontColor_label = QtWidgets.QToolButton(self.groupBox_12)
        self.pickFontColor_label.setEnabled(True)
        self.pickFontColor_label.setObjectName("pickFontColor_label")
        self.gridLayout_3.addWidget(self.pickFontColor_label, 0, 2, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.groupBox_12)
        self.label_22.setObjectName("label_22")
        self.gridLayout_3.addWidget(self.label_22, 1, 0, 1, 1)
        self.fontweightComboBox_ax = QtWidgets.QComboBox(self.groupBox_12)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.fontweightComboBox_ax.setFont(font)
        self.fontweightComboBox_ax.setObjectName("fontweightComboBox_ax")
        self.fontweightComboBox_ax.addItem("")
        self.fontweightComboBox_ax.addItem("")
        self.fontweightComboBox_ax.addItem("")
        self.fontweightComboBox_ax.addItem("")
        self.fontweightComboBox_ax.addItem("")
        self.fontweightComboBox_ax.addItem("")
        self.fontweightComboBox_ax.addItem("")
        self.fontweightComboBox_ax.addItem("")
        self.fontweightComboBox_ax.addItem("")
        self.fontweightComboBox_ax.addItem("")
        self.fontweightComboBox_ax.addItem("")
        self.fontweightComboBox_ax.addItem("")
        self.fontweightComboBox_ax.addItem("")
        self.fontweightComboBox_ax.addItem("")
        self.gridLayout_3.addWidget(self.fontweightComboBox_ax, 1, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.groupBox_12)
        self.label_25.setObjectName("label_25")
        self.gridLayout_3.addWidget(self.label_25, 4, 0, 1, 1)
        self.fontsizeSpinBox_ax = QtWidgets.QSpinBox(self.groupBox_12)
        self.fontsizeSpinBox_ax.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.fontsizeSpinBox_ax.setFont(font)
        self.fontsizeSpinBox_ax.setMinimum(1)
        self.fontsizeSpinBox_ax.setObjectName("fontsizeSpinBox_ax")
        self.gridLayout_3.addWidget(self.fontsizeSpinBox_ax, 3, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.groupBox_12)
        self.label_23.setObjectName("label_23")
        self.gridLayout_3.addWidget(self.label_23, 2, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_12)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 0, 0, 1, 1)
        self.fontstyleComboBox_ax = QtWidgets.QComboBox(self.groupBox_12)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.fontstyleComboBox_ax.setFont(font)
        self.fontstyleComboBox_ax.setObjectName("fontstyleComboBox_ax")
        self.fontstyleComboBox_ax.addItem("")
        self.fontstyleComboBox_ax.addItem("")
        self.fontstyleComboBox_ax.addItem("")
        self.gridLayout_3.addWidget(self.fontstyleComboBox_ax, 2, 1, 1, 1)
        self.label_size_auto_cb = QtWidgets.QCheckBox(self.groupBox_12)
        self.label_size_auto_cb.setChecked(True)
        self.label_size_auto_cb.setObjectName("label_size_auto_cb")
        self.gridLayout_3.addWidget(self.label_size_auto_cb, 3, 0, 1, 1)
        self.fontfamilyComboBox_ax = QtWidgets.QComboBox(self.groupBox_12)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.fontfamilyComboBox_ax.setFont(font)
        self.fontfamilyComboBox_ax.setObjectName("fontfamilyComboBox_ax")
        self.fontfamilyComboBox_ax.addItem("")
        self.fontfamilyComboBox_ax.addItem("")
        self.fontfamilyComboBox_ax.addItem("")
        self.fontfamilyComboBox_ax.addItem("")
        self.fontfamilyComboBox_ax.addItem("")
        self.gridLayout_3.addWidget(self.fontfamilyComboBox_ax, 4, 1, 1, 1)
        self.verticalLayout_17.addLayout(self.gridLayout_3)
        self.verticalLayout_20.addWidget(self.groupBox_12)
        self.groupBox_11 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_11.setObjectName("groupBox_11")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.groupBox_11)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pickFontColor_ax = QtWidgets.QToolButton(self.groupBox_11)
        self.pickFontColor_ax.setObjectName("pickFontColor_ax")
        self.gridLayout_4.addWidget(self.pickFontColor_ax, 2, 2, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.groupBox_11)
        self.label_20.setObjectName("label_20")
        self.gridLayout_4.addWidget(self.label_20, 1, 0, 1, 1)
        self.grid_cb = QtWidgets.QCheckBox(self.groupBox_11)
        self.grid_cb.setObjectName("grid_cb")
        self.gridLayout_4.addWidget(self.grid_cb, 3, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_11)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 2, 0, 1, 1)
        self.axis_thickness_cb = QtWidgets.QDoubleSpinBox(self.groupBox_11)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.axis_thickness_cb.setFont(font)
        self.axis_thickness_cb.setDecimals(1)
        self.axis_thickness_cb.setSingleStep(0.5)
        self.axis_thickness_cb.setProperty("value", 1.0)
        self.axis_thickness_cb.setObjectName("axis_thickness_cb")
        self.gridLayout_4.addWidget(self.axis_thickness_cb, 1, 1, 1, 1)
        self.labelFontColor_ax = QtWidgets.QLabel(self.groupBox_11)
        self.labelFontColor_ax.setText("")
        self.labelFontColor_ax.setObjectName("labelFontColor_ax")
        self.gridLayout_4.addWidget(self.labelFontColor_ax, 2, 1, 1, 1)
        self.tick_label_size_cb = QtWidgets.QSpinBox(self.groupBox_11)
        self.tick_label_size_cb.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.tick_label_size_cb.setFont(font)
        self.tick_label_size_cb.setObjectName("tick_label_size_cb")
        self.gridLayout_4.addWidget(self.tick_label_size_cb, 0, 1, 1, 1)
        self.tick_label_size_auto_cb = QtWidgets.QCheckBox(self.groupBox_11)
        self.tick_label_size_auto_cb.setChecked(True)
        self.tick_label_size_auto_cb.setObjectName("tick_label_size_auto_cb")
        self.gridLayout_4.addWidget(self.tick_label_size_auto_cb, 0, 0, 1, 1)
        self.verticalLayout_18.addLayout(self.gridLayout_4)
        self.verticalLayout_20.addWidget(self.groupBox_11)
        self.reset_all_pb = QtWidgets.QPushButton(self.tab)
        self.reset_all_pb.setObjectName("reset_all_pb")
        self.verticalLayout_20.addWidget(self.reset_all_pb)
        self.tabWidget.addTab(self.tab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushOK = QtWidgets.QPushButton(Dialog)
        self.pushOK.setObjectName("pushOK")
        self.horizontalLayout_5.addWidget(self.pushOK)
        self.pushCancel = QtWidgets.QPushButton(Dialog)
        self.pushCancel.setObjectName("pushCancel")
        self.horizontalLayout_5.addWidget(self.pushCancel)
        self.pushApply = QtWidgets.QPushButton(Dialog)
        self.pushApply.setObjectName("pushApply")
        self.horizontalLayout_5.addWidget(self.pushApply)
        self.verticalLayout.addLayout(self.horizontalLayout_5)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        self.pushOK.clicked.connect(Dialog.accept)
        self.pushCancel.clicked.connect(Dialog.reject)
        self.rbThFixedColor.clicked['bool'].connect(self.pickThColor.setEnabled)
        self.rbFixedSymbol.clicked['bool'].connect(self.cbSymbolType.setEnabled)
        self.rbGradientColor.clicked['bool'].connect(self.cbPalette.setDisabled)
        self.rbPalette.clicked['bool'].connect(self.pickColor1.setDisabled)
        self.rbPalette.clicked['bool'].connect(self.pickColor2.setDisabled)
        self.rbThFixedColor.clicked['bool'].connect(self.labelThcol.setEnabled)
        self.rbThSameColor.clicked['bool'].connect(self.labelThcol.setDisabled)
        self.rbPalette.clicked['bool'].connect(self.label_5.setDisabled)
        self.rbThFixedColor.clicked['bool'].connect(self.labelThPickedColor.setEnabled)
        self.rbThSameColor.clicked['bool'].connect(self.pickThColor.setDisabled)
        self.rbVariableSymbol.clicked['bool'].connect(self.cbSymbolType.setDisabled)
        self.rbThSameColor.clicked['bool'].connect(self.labelThPickedColor.setDisabled)
        self.rbFixedColor.clicked['bool'].connect(self.pickColor2.setDisabled)
        self.rbFixedColor.clicked['bool'].connect(self.cbPalette.setDisabled)
        self.rbFixedColor.clicked['bool'].connect(self.pickColor1.setEnabled)
        self.rbGradientColor.clicked['bool'].connect(self.pickColor1.setEnabled)
        self.rbFixedColor.clicked['bool'].connect(self.labelPickedColor2.setDisabled)
        self.rbGradientColor.clicked['bool'].connect(self.pickColor2.setEnabled)
        self.rbGradientColor.clicked['bool'].connect(self.labelPickedColor2.setEnabled)
        self.rbGradientColor.clicked['bool'].connect(self.labelPickedColor1.setEnabled)
        self.rbGradientColor.clicked['bool'].connect(self.label_4.setEnabled)
        self.rbPalette.clicked['bool'].connect(self.label_4.setDisabled)
        self.rbPalette.clicked['bool'].connect(self.labelPickedColor1.setDisabled)
        self.rbFixedColor.clicked['bool'].connect(self.label_4.setEnabled)
        self.rbPalette.clicked['bool'].connect(self.cbPalette.setEnabled)
        self.rbFixedColor.clicked['bool'].connect(self.label_5.setDisabled)
        self.rbPalette.clicked['bool'].connect(self.labelPickedColor2.setDisabled)
        self.rbGradientColor.clicked['bool'].connect(self.label_5.setEnabled)
        self.rbFixedColor.clicked['bool'].connect(self.labelPickedColor1.setEnabled)
        self.facecolorCheckBox.clicked['bool'].connect(self.labelFaceColor.setEnabled)
        self.facecolorCheckBox.clicked['bool'].connect(self.pickFaceColor.setEnabled)
        self.edgecolorCheckBox.clicked['bool'].connect(self.labelEdgeColor.setEnabled)
        self.edgecolorCheckBox.clicked['bool'].connect(self.pickEdgeColor.setEnabled)
        self.framealphaCheckBox.clicked['bool'].connect(self.framealphaSpinBox.setEnabled)
        self.borderpadCheckBox.clicked['bool'].connect(self.borderpadSpinBox.setEnabled)
        self.labelspacingCheckBox.clicked['bool'].connect(self.labelspacingSpinBox.setEnabled)
        self.handletextpadCheckBox.clicked['bool'].connect(self.handletextpadSpinBox.setEnabled)
        self.columnspacingCheckBox.clicked['bool'].connect(self.columnspacingSpinBox.setEnabled)
        self.legendtitleCheckBox.clicked['bool'].connect(self.legendtitleStr.setEnabled)
        self.legendlabelCheckBox.clicked['bool'].connect(self.legendlabelStr.setEnabled)
        self.label_size_auto_cb.toggled['bool'].connect(self.fontsizeSpinBox_ax.setDisabled)
        self.tick_label_size_auto_cb.toggled['bool'].connect(self.tick_label_size_cb.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Plot Style"))
        self.groupBox.setTitle(_translate("Dialog", "Symbol"))
        self.groupBox_3.setTitle(_translate("Dialog", "Type"))
        self.cbSymbolType.setToolTip(_translate("Dialog", "Empty symbol"))
        self.rbFixedSymbol.setToolTip(_translate("Dialog", "Fixed symbol shape"))
        self.rbFixedSymbol.setText(_translate("Dialog", "Fixed"))
        self.rbVariableSymbol.setToolTip(_translate("Dialog", "Variable symbol shape"))
        self.rbVariableSymbol.setText(_translate("Dialog", "Variable"))
        self.spinBoxLineW.setPrefix(_translate("Dialog", "Line width: "))
        self.groupBox_4.setTitle(_translate("Dialog", "Size"))
        self.rbEmpty.setText(_translate("Dialog", "Empty"))
        self.rbFilled.setToolTip(_translate("Dialog", "Filled symbol"))
        self.rbFilled.setText(_translate("Dialog", "Filled"))
        self.groupBox_2.setTitle(_translate("Dialog", "Color"))
        self.groupBox_5.setTitle(_translate("Dialog", "Type"))
        self.rbFixedColor.setToolTip(_translate("Dialog", "Fixed color"))
        self.rbFixedColor.setText(_translate("Dialog", "Fixed"))
        self.rbGradientColor.setToolTip(_translate("Dialog", "Gradient color between Color1 and Color2"))
        self.rbGradientColor.setText(_translate("Dialog", "Gradient"))
        self.rbPalette.setText(_translate("Dialog", "Palette"))
        self.groupBox_6.setTitle(_translate("Dialog", "Selection"))
        self.pickColor1.setText(_translate("Dialog", "..."))
        self.label_4.setText(_translate("Dialog", "Color 1"))
        self.label_5.setText(_translate("Dialog", "Color 2"))
        self.pickColor2.setText(_translate("Dialog", "..."))
        self.cbPalette.setToolTip(_translate("Dialog", "Choose color palette"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.data), _translate("Dialog", "Data"))
        self.groupBox_8.setTitle(_translate("Dialog", "Line Type"))
        self.sbThLineWidth.setPrefix(_translate("Dialog", "Line width: "))
        self.groupBox_10.setTitle(_translate("Dialog", "Color"))
        self.rbThSameColor.setToolTip(_translate("Dialog", "Same color as the data points"))
        self.rbThSameColor.setText(_translate("Dialog", "Same as Data"))
        self.rbThFixedColor.setToolTip(_translate("Dialog", "Theory in fixed color"))
        self.rbThFixedColor.setText(_translate("Dialog", "Fixed"))
        self.labelThcol.setText(_translate("Dialog", "Color"))
        self.pickThColor.setText(_translate("Dialog", "..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.theory), _translate("Dialog", "Theory"))
        self.cb_show_legend.setToolTip(_translate("Dialog", "Show Legend on Figure"))
        self.cb_show_legend.setText(_translate("Dialog", "Show Legend"))
        self.groupBox_7.setTitle(_translate("Dialog", "Legend Properties"))
        self.label.setToolTip(_translate("Dialog", "The location of the legend"))
        self.label.setText(_translate("Dialog", "Location"))
        self.locationComboBox.setItemText(0, _translate("Dialog", "best"))
        self.locationComboBox.setItemText(1, _translate("Dialog", "upper right"))
        self.locationComboBox.setItemText(2, _translate("Dialog", "upper left"))
        self.locationComboBox.setItemText(3, _translate("Dialog", "lower left"))
        self.locationComboBox.setItemText(4, _translate("Dialog", "lower right"))
        self.locationComboBox.setItemText(5, _translate("Dialog", "right"))
        self.locationComboBox.setItemText(6, _translate("Dialog", "center left"))
        self.locationComboBox.setItemText(7, _translate("Dialog", "center right"))
        self.locationComboBox.setItemText(8, _translate("Dialog", "lower center"))
        self.locationComboBox.setItemText(9, _translate("Dialog", "upper center"))
        self.locationComboBox.setItemText(10, _translate("Dialog", "center"))
        self.label_2.setToolTip(_translate("Dialog", "Number of columns in the legend"))
        self.label_2.setText(_translate("Dialog", "Number of columns"))
        self.label_3.setToolTip(_translate("Dialog", "Legend font size"))
        self.label_3.setText(_translate("Dialog", "Font Size"))
        self.fancyboxCheckBox.setToolTip(_translate("Dialog", "Draw legend frame with round edges"))
        self.fancyboxCheckBox.setText(_translate("Dialog", "Fancy Box"))
        self.markerfirstCheckBox.setToolTip(_translate("Dialog", "Place legend marker to the left of the legend label"))
        self.markerfirstCheckBox.setText(_translate("Dialog", "Marker First"))
        self.modeCheckBox.setToolTip(_translate("Dialog", "Expand the legend horizontally to fill the axes area"))
        self.modeCheckBox.setText(_translate("Dialog", "Expand Mode"))
        self.shadowCheckBox.setToolTip(_translate("Dialog", "Draw a shadow behind the legend"))
        self.shadowCheckBox.setText(_translate("Dialog", "Shadow"))
        self.facecolorCheckBox.setToolTip(_translate("Dialog", "Legend’s background color"))
        self.facecolorCheckBox.setText(_translate("Dialog", "Face Color"))
        self.pickFaceColor.setText(_translate("Dialog", "..."))
        self.edgecolorCheckBox.setToolTip(_translate("Dialog", "Legend’s background patch edge color"))
        self.edgecolorCheckBox.setText(_translate("Dialog", "Edge Color"))
        self.pickEdgeColor.setText(_translate("Dialog", "..."))
        self.framealphaCheckBox.setToolTip(_translate("Dialog", "Alpha transparency of the legend’s background"))
        self.framealphaCheckBox.setText(_translate("Dialog", "Transparency"))
        self.frameonCheckBox.setToolTip(_translate("Dialog", "Draw the legend inside a patch (frame)"))
        self.frameonCheckBox.setText(_translate("Dialog", "Draw Frame"))
        self.legendtitleCheckBox.setToolTip(_translate("Dialog", "Set Legend Title (default None)"))
        self.legendtitleCheckBox.setText(_translate("Dialog", "Legend Title"))
        self.legendtitleStr.setToolTip(_translate("Dialog", "Legend’s title (none if left empty)"))
        self.borderpadCheckBox.setToolTip(_translate("Dialog", "Fractional whitespace inside the legend border"))
        self.borderpadCheckBox.setText(_translate("Dialog", "Legend Border Pad"))
        self.labelspacingCheckBox.setText(_translate("Dialog", "Space Between Entries"))
        self.handletextpadCheckBox.setText(_translate("Dialog", "Space Handle-Label"))
        self.columnspacingCheckBox.setText(_translate("Dialog", "Space Between Columns"))
        self.legendlabelCheckBox.setToolTip(_translate("Dialog", "Set Legend label (default = all basic file parameters with values)"))
        self.legendlabelCheckBox.setText(_translate("Dialog", "Legend Labels"))
        self.legendlabelStr.setToolTip(_translate("Dialog", "default = all basic file parameters with values"))
        self.legendlabelStr.setText(_translate("Dialog", "default"))
        self.draggableCheckBox.setToolTip(_translate("Dialog", "Can the user move the legend with the mouse"))
        self.draggableCheckBox.setText(_translate("Dialog", "Draggable Legend"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.legend), _translate("Dialog", "Legend"))
        self.groupBox_9.setTitle(_translate("Dialog", "Default Annotation Properties"))
        self.label_10.setText(_translate("Dialog", "Rotation"))
        self.label_11.setText(_translate("Dialog", "Alignment"))
        self.label_12.setText(_translate("Dialog", "Horizontal"))
        self.hacomboBox.setItemText(0, _translate("Dialog", "center"))
        self.hacomboBox.setItemText(1, _translate("Dialog", "right"))
        self.hacomboBox.setItemText(2, _translate("Dialog", "left"))
        self.label_13.setText(_translate("Dialog", "Vertical"))
        self.vacomboBox.setItemText(0, _translate("Dialog", "center"))
        self.vacomboBox.setItemText(1, _translate("Dialog", "top"))
        self.vacomboBox.setItemText(2, _translate("Dialog", "bottom"))
        self.vacomboBox.setItemText(3, _translate("Dialog", "baseline"))
        self.label_7.setText(_translate("Dialog", "Font Color"))
        self.pickFontColor.setText(_translate("Dialog", "..."))
        self.label_14.setText(_translate("Dialog", "Font weight"))
        self.fontweightComboBox.setItemText(0, _translate("Dialog", "ultralight"))
        self.fontweightComboBox.setItemText(1, _translate("Dialog", "light"))
        self.fontweightComboBox.setItemText(2, _translate("Dialog", "normal"))
        self.fontweightComboBox.setItemText(3, _translate("Dialog", "regular"))
        self.fontweightComboBox.setItemText(4, _translate("Dialog", "book"))
        self.fontweightComboBox.setItemText(5, _translate("Dialog", "medium"))
        self.fontweightComboBox.setItemText(6, _translate("Dialog", "roman"))
        self.fontweightComboBox.setItemText(7, _translate("Dialog", "semibold"))
        self.fontweightComboBox.setItemText(8, _translate("Dialog", "demibold"))
        self.fontweightComboBox.setItemText(9, _translate("Dialog", "demi"))
        self.fontweightComboBox.setItemText(10, _translate("Dialog", "bold"))
        self.fontweightComboBox.setItemText(11, _translate("Dialog", "heavy"))
        self.fontweightComboBox.setItemText(12, _translate("Dialog", "extra bold"))
        self.fontweightComboBox.setItemText(13, _translate("Dialog", "black"))
        self.label_15.setText(_translate("Dialog", "Font Style"))
        self.fontstyleComboBox.setItemText(0, _translate("Dialog", "normal"))
        self.fontstyleComboBox.setItemText(1, _translate("Dialog", "italic"))
        self.fontstyleComboBox.setItemText(2, _translate("Dialog", "oblique"))
        self.label_16.setToolTip(_translate("Dialog", "Legend font size"))
        self.label_16.setText(_translate("Dialog", "Font Size"))
        self.label_6.setText(_translate("Dialog", "Opacity"))
        self.label_17.setText(_translate("Dialog", "Font Family"))
        self.fontfamilyComboBox.setItemText(0, _translate("Dialog", "serif"))
        self.fontfamilyComboBox.setItemText(1, _translate("Dialog", "sans-serif"))
        self.fontfamilyComboBox.setItemText(2, _translate("Dialog", "cursive"))
        self.fontfamilyComboBox.setItemText(3, _translate("Dialog", "fantasy"))
        self.fontfamilyComboBox.setItemText(4, _translate("Dialog", "monospace"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.annotations), _translate("Dialog", "Annotations"))
        self.groupBox_12.setTitle(_translate("Dialog", "Labels"))
        self.pickFontColor_label.setText(_translate("Dialog", "..."))
        self.label_22.setText(_translate("Dialog", "Font Weight"))
        self.fontweightComboBox_ax.setItemText(0, _translate("Dialog", "ultralight"))
        self.fontweightComboBox_ax.setItemText(1, _translate("Dialog", "light"))
        self.fontweightComboBox_ax.setItemText(2, _translate("Dialog", "normal"))
        self.fontweightComboBox_ax.setItemText(3, _translate("Dialog", "regular"))
        self.fontweightComboBox_ax.setItemText(4, _translate("Dialog", "book"))
        self.fontweightComboBox_ax.setItemText(5, _translate("Dialog", "medium"))
        self.fontweightComboBox_ax.setItemText(6, _translate("Dialog", "roman"))
        self.fontweightComboBox_ax.setItemText(7, _translate("Dialog", "semibold"))
        self.fontweightComboBox_ax.setItemText(8, _translate("Dialog", "demibold"))
        self.fontweightComboBox_ax.setItemText(9, _translate("Dialog", "demi"))
        self.fontweightComboBox_ax.setItemText(10, _translate("Dialog", "bold"))
        self.fontweightComboBox_ax.setItemText(11, _translate("Dialog", "heavy"))
        self.fontweightComboBox_ax.setItemText(12, _translate("Dialog", "extra bold"))
        self.fontweightComboBox_ax.setItemText(13, _translate("Dialog", "black"))
        self.label_25.setText(_translate("Dialog", "Font Family"))
        self.label_23.setText(_translate("Dialog", "Font Style"))
        self.label_8.setText(_translate("Dialog", "Font Color"))
        self.fontstyleComboBox_ax.setItemText(0, _translate("Dialog", "normal"))
        self.fontstyleComboBox_ax.setItemText(1, _translate("Dialog", "italic"))
        self.fontstyleComboBox_ax.setItemText(2, _translate("Dialog", "oblique"))
        self.label_size_auto_cb.setText(_translate("Dialog", "Autoscale Label Size"))
        self.fontfamilyComboBox_ax.setItemText(0, _translate("Dialog", "serif"))
        self.fontfamilyComboBox_ax.setItemText(1, _translate("Dialog", "sans-serif"))
        self.fontfamilyComboBox_ax.setItemText(2, _translate("Dialog", "cursive"))
        self.fontfamilyComboBox_ax.setItemText(3, _translate("Dialog", "fantasy"))
        self.fontfamilyComboBox_ax.setItemText(4, _translate("Dialog", "monospace"))
        self.groupBox_11.setTitle(_translate("Dialog", "Axes"))
        self.pickFontColor_ax.setText(_translate("Dialog", "..."))
        self.label_20.setText(_translate("Dialog", "Axes Thickness"))
        self.grid_cb.setText(_translate("Dialog", "Grid"))
        self.label_9.setText(_translate("Dialog", "Color"))
        self.tick_label_size_auto_cb.setText(_translate("Dialog", "Autoscale Tick Label Size"))
        self.reset_all_pb.setText(_translate("Dialog", "Default"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Axes"))
        self.pushOK.setText(_translate("Dialog", "OK"))
        self.pushCancel.setText(_translate("Dialog", "Cancel"))
        self.pushApply.setText(_translate("Dialog", "Apply"))
import Reptate_rc
