# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'QApplicationWindow.ui'
##
## Created by: Qt User Interface Compiler version 6.6.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QDockWidget, QHBoxLayout,
    QLabel, QMainWindow, QSizePolicy, QSpinBox,
    QTabWidget, QToolButton, QVBoxLayout, QWidget)
from . import Reptate_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(610, 496)
        self.actionOpen = QAction(MainWindow)
        self.actionOpen.setObjectName(u"actionOpen")
        self.actionClose = QAction(MainWindow)
        self.actionClose.setObjectName(u"actionClose")
        self.actionQuit = QAction(MainWindow)
        self.actionQuit.setObjectName(u"actionQuit")
        self.actionUndo = QAction(MainWindow)
        self.actionUndo.setObjectName(u"actionUndo")
        self.actionRedo = QAction(MainWindow)
        self.actionRedo.setObjectName(u"actionRedo")
        self.actionCopy = QAction(MainWindow)
        self.actionCopy.setObjectName(u"actionCopy")
        icon = QIcon()
        icon.addFile(u":/Images/Images/new_icons/icons8-copy.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionCopy.setIcon(icon)
        self.actionCut = QAction(MainWindow)
        self.actionCut.setObjectName(u"actionCut")
        self.actionPaste = QAction(MainWindow)
        self.actionPaste.setObjectName(u"actionPaste")
        icon1 = QIcon()
        icon1.addFile(u":/Images/Images/new_icons/icons8-paste.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionPaste.setIcon(icon1)
        self.actionSelect_All = QAction(MainWindow)
        self.actionSelect_All.setObjectName(u"actionSelect_All")
        self.actionShowFigureTools = QAction(MainWindow)
        self.actionShowFigureTools.setObjectName(u"actionShowFigureTools")
        self.actionShowFigureTools.setCheckable(True)
        icon2 = QIcon()
        icon2.addFile(u":/Images/Images/new_icons/icons8-sine-100.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionShowFigureTools.setIcon(icon2)
        self.actionShiftVertically = QAction(MainWindow)
        self.actionShiftVertically.setObjectName(u"actionShiftVertically")
        self.actionShiftVertically.setCheckable(True)
        icon3 = QIcon()
        icon3.addFile(u":/Images/Images/new_icons/icons8-vertical-timeline-slider.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionShiftVertically.setIcon(icon3)
        self.actionShiftHorizontally = QAction(MainWindow)
        self.actionShiftHorizontally.setObjectName(u"actionShiftHorizontally")
        self.actionShiftHorizontally.setCheckable(True)
        icon4 = QIcon()
        icon4.addFile(u":/Images/Images/new_icons/icons8-timeline-slider.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionShiftHorizontally.setIcon(icon4)
        self.actionNew_Empty_Dataset = QAction(MainWindow)
        self.actionNew_Empty_Dataset.setObjectName(u"actionNew_Empty_Dataset")
        icon5 = QIcon()
        icon5.addFile(u":/Images/Images/new_icons/icons8-add-row.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionNew_Empty_Dataset.setIcon(icon5)
        self.actionNew_Dataset_From_File = QAction(MainWindow)
        self.actionNew_Dataset_From_File.setObjectName(u"actionNew_Dataset_From_File")
        icon6 = QIcon()
        icon6.addFile(u":/Images/Images/new_icons/icons8-open-view-in-new-tab.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionNew_Dataset_From_File.setIcon(icon6)
        self.actionView_All_Sets = QAction(MainWindow)
        self.actionView_All_Sets.setObjectName(u"actionView_All_Sets")
        self.actionView_All_Sets.setCheckable(True)
        icon7 = QIcon()
        icon7.addFile(u":/Images/Images/new_icons/icons8-binoculars.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionView_All_Sets.setIcon(icon7)
        self.actionReload_Data = QAction(MainWindow)
        self.actionReload_Data.setObjectName(u"actionReload_Data")
        icon8 = QIcon()
        icon8.addFile(u":/Images/Images/new_icons/icons8-file-reload.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionReload_Data.setIcon(icon8)
        self.actionInspect_Data = QAction(MainWindow)
        self.actionInspect_Data.setObjectName(u"actionInspect_Data")
        self.actionInspect_Data.setCheckable(True)
        icon9 = QIcon()
        icon9.addFile(u":/Images/Images/new_icons/icons8-microscope.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionInspect_Data.setIcon(icon9)
        self.actionMarkerSettings = QAction(MainWindow)
        self.actionMarkerSettings.setObjectName(u"actionMarkerSettings")
        icon10 = QIcon()
        icon10.addFile(u":/Images/Images/new_icons/icons8-color-wheel-2.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionMarkerSettings.setIcon(icon10)
        self.actionTrack_data = QAction(MainWindow)
        self.actionTrack_data.setObjectName(u"actionTrack_data")
        self.actionTrack_data.setCheckable(True)
        icon11 = QIcon()
        icon11.addFile(u":/Images/Images/new_icons/icons8-physics.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionTrack_data.setIcon(icon11)
        self.actionAdd_Annotation = QAction(MainWindow)
        self.actionAdd_Annotation.setObjectName(u"actionAdd_Annotation")
        icon12 = QIcon()
        icon12.addFile(u":/Images/Images/new_icons/icons8-spiral-bound-booklet.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionAdd_Annotation.setIcon(icon12)
        self.actionShow_Legend = QAction(MainWindow)
        self.actionShow_Legend.setObjectName(u"actionShow_Legend")
        icon13 = QIcon()
        icon13.addFile(u":/Images/Images/new_icons/icons8-categorize.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionShow_Legend.setIcon(icon13)
        self.actionCopyChart = QAction(MainWindow)
        self.actionCopyChart.setObjectName(u"actionCopyChart")
        self.actionCopyChart.setIcon(icon)
        self.actionNew_Tool = QAction(MainWindow)
        self.actionNew_Tool.setObjectName(u"actionNew_Tool")
        icon14 = QIcon()
        icon14.addFile(u":/Images/Images/new_icons/icons8-maintenance.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionNew_Tool.setIcon(icon14)
        self.actionSave_View = QAction(MainWindow)
        self.actionSave_View.setObjectName(u"actionSave_View")
        icon15 = QIcon()
        icon15.addFile(u":/Images/Images/new_icons/icons8-saveView.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionSave_View.setIcon(icon15)
        self.actionResetShiftFactors = QAction(MainWindow)
        self.actionResetShiftFactors.setObjectName(u"actionResetShiftFactors")
        icon16 = QIcon()
        icon16.addFile(u":/Images/Images/new_icons/icons8-reset-shift.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionResetShiftFactors.setIcon(icon16)
        self.actionViewShiftFactors = QAction(MainWindow)
        self.actionViewShiftFactors.setObjectName(u"actionViewShiftFactors")
        icon17 = QIcon()
        icon17.addFile(u":/Images/Images/new_icons/icons8-view-ShiftFactors.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionViewShiftFactors.setIcon(icon17)
        self.actionSaveShiftFactors = QAction(MainWindow)
        self.actionSaveShiftFactors.setObjectName(u"actionSaveShiftFactors")
        icon18 = QIcon()
        icon18.addFile(u":/Images/Images/new_icons/icons8-save-ShiftFactors.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionSaveShiftFactors.setIcon(icon18)
        self.actionAddDummyFiles = QAction(MainWindow)
        self.actionAddDummyFiles.setObjectName(u"actionAddDummyFiles")
        self.actionAddDummyFiles.setIcon(icon12)
        self.actionView_All_SetTheories = QAction(MainWindow)
        self.actionView_All_SetTheories.setObjectName(u"actionView_All_SetTheories")
        self.actionView_All_SetTheories.setIcon(icon7)
        self.action_import_from_excel = QAction(MainWindow)
        self.action_import_from_excel.setObjectName(u"action_import_from_excel")
        icon19 = QIcon()
        icon19.addFile(u":/Images/Images/new_icons/icons8-microsoft-excel.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_import_from_excel.setIcon(icon19)
        self.actionAdd_File_With_Function = QAction(MainWindow)
        self.actionAdd_File_With_Function.setObjectName(u"actionAdd_File_With_Function")
        icon20 = QIcon()
        icon20.addFile(u":/Images/Images/new_icons/icons8-formula-fx-50.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionAdd_File_With_Function.setIcon(icon20)
        self.action_import_from_pasted = QAction(MainWindow)
        self.action_import_from_pasted.setObjectName(u"action_import_from_pasted")
        self.action_import_from_pasted.setIcon(icon1)
        self.actionSaveDataSet = QAction(MainWindow)
        self.actionSaveDataSet.setObjectName(u"actionSaveDataSet")
        icon21 = QIcon()
        icon21.addFile(u":/Images/Images/new_icons/icons8-save_DS.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionSaveDataSet.setIcon(icon21)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.verticalLayout_4 = QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.mplwidget = QWidget(self.centralwidget)
        self.mplwidget.setObjectName(u"mplwidget")
        font = QFont()
        font.setBold(True)
        self.mplwidget.setFont(font)
        self.mplwidget.setStyleSheet(u"")
        self.mplvl = QVBoxLayout(self.mplwidget)
        self.mplvl.setSpacing(0)
        self.mplvl.setObjectName(u"mplvl")
        self.mplvl.setContentsMargins(0, 0, 0, 0)

        self.verticalLayout_4.addWidget(self.mplwidget)

        MainWindow.setCentralWidget(self.centralwidget)
        self.DataInspectordockWidget = QDockWidget(MainWindow)
        self.DataInspectordockWidget.setObjectName(u"DataInspectordockWidget")
        self.DataInspectordockWidget.setFont(font)
        self.DataInspectordockWidget.setStyleSheet(u"")
        self.DataInspectordockWidget.setFeatures(QDockWidget.DockWidgetClosable)
        self.DataInspectordockWidget.setAllowedAreas(Qt.LeftDockWidgetArea)
        self.dockWidgetContents = QWidget()
        self.dockWidgetContents.setObjectName(u"dockWidgetContents")
        self.LayoutDataInspector = QVBoxLayout(self.dockWidgetContents)
        self.LayoutDataInspector.setSpacing(0)
        self.LayoutDataInspector.setObjectName(u"LayoutDataInspector")
        self.LayoutDataInspector.setContentsMargins(0, 0, 0, 0)
        self.DataInspectordockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(Qt.LeftDockWidgetArea, self.DataInspectordockWidget)
        self.ViewDataTheorydockWidget = QDockWidget(MainWindow)
        self.ViewDataTheorydockWidget.setObjectName(u"ViewDataTheorydockWidget")
        self.ViewDataTheorydockWidget.setStyleSheet(u"")
        self.ViewDataTheorydockWidget.setFeatures(QDockWidget.NoDockWidgetFeatures)
        self.ViewDataTheorydockWidget.setAllowedAreas(Qt.RightDockWidgetArea)
        self.ViewDataTheoryWidget = QWidget()
        self.ViewDataTheoryWidget.setObjectName(u"ViewDataTheoryWidget")
        self.ViewDataTheoryLayout = QVBoxLayout(self.ViewDataTheoryWidget)
        self.ViewDataTheoryLayout.setSpacing(0)
        self.ViewDataTheoryLayout.setObjectName(u"ViewDataTheoryLayout")
        self.ViewDataTheoryLayout.setContentsMargins(0, 0, 0, 0)
        self.viewLayout = QHBoxLayout()
        self.viewLayout.setSpacing(0)
        self.viewLayout.setObjectName(u"viewLayout")
        self.sp_nviews = QSpinBox(self.ViewDataTheoryWidget)
        self.sp_nviews.setObjectName(u"sp_nviews")
        self.sp_nviews.setMaximumSize(QSize(40, 16777215))
        self.sp_nviews.setMinimum(1)
        self.sp_nviews.setMaximum(4)
        self.sp_nviews.setValue(1)

        self.viewLayout.addWidget(self.sp_nviews)

        self.label = QLabel(self.ViewDataTheoryWidget)
        self.label.setObjectName(u"label")
        self.label.setMinimumSize(QSize(39, 0))
        self.label.setMaximumSize(QSize(39, 16777215))
        self.label.setFont(font)

        self.viewLayout.addWidget(self.label)

        self.viewComboBox = QComboBox(self.ViewDataTheoryWidget)
        self.viewComboBox.setObjectName(u"viewComboBox")

        self.viewLayout.addWidget(self.viewComboBox)

        self.saveViewtoolButton = QToolButton(self.ViewDataTheoryWidget)
        self.saveViewtoolButton.setObjectName(u"saveViewtoolButton")

        self.viewLayout.addWidget(self.saveViewtoolButton)


        self.ViewDataTheoryLayout.addLayout(self.viewLayout)

        self.DataSettabWidget = QTabWidget(self.ViewDataTheoryWidget)
        self.DataSettabWidget.setObjectName(u"DataSettabWidget")
        self.DataSettabWidget.setTabShape(QTabWidget.Triangular)
        self.DataSettabWidget.setUsesScrollButtons(True)
        self.DataSettabWidget.setTabsClosable(False)

        self.ViewDataTheoryLayout.addWidget(self.DataSettabWidget)

        self.ViewDataTheorydockWidget.setWidget(self.ViewDataTheoryWidget)
        MainWindow.addDockWidget(Qt.RightDockWidgetArea, self.ViewDataTheorydockWidget)

        self.retranslateUi(MainWindow)

        self.DataSettabWidget.setCurrentIndex(-1)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionOpen.setText(QCoreApplication.translate("MainWindow", u"Open", None))
        self.actionClose.setText(QCoreApplication.translate("MainWindow", u"Close", None))
        self.actionQuit.setText(QCoreApplication.translate("MainWindow", u"Quit", None))
        self.actionUndo.setText(QCoreApplication.translate("MainWindow", u"Undo", None))
        self.actionRedo.setText(QCoreApplication.translate("MainWindow", u"Redo", None))
        self.actionCopy.setText(QCoreApplication.translate("MainWindow", u"Copy", None))
        self.actionCut.setText(QCoreApplication.translate("MainWindow", u"Cut", None))
        self.actionPaste.setText(QCoreApplication.translate("MainWindow", u"Paste", None))
        self.actionSelect_All.setText(QCoreApplication.translate("MainWindow", u"Select All", None))
        self.actionShowFigureTools.setText(QCoreApplication.translate("MainWindow", u"Print", None))
#if QT_CONFIG(tooltip)
        self.actionShowFigureTools.setToolTip(QCoreApplication.translate("MainWindow", u"Show/Hide Figure Toolbar (Ctrl+F)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionShowFigureTools.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+F", None))
#endif // QT_CONFIG(shortcut)
        self.actionShiftVertically.setText(QCoreApplication.translate("MainWindow", u"ShiftVertically", None))
#if QT_CONFIG(tooltip)
        self.actionShiftVertically.setToolTip(QCoreApplication.translate("MainWindow", u"Shift the selected curve vertically", None))
#endif // QT_CONFIG(tooltip)
        self.actionShiftHorizontally.setText(QCoreApplication.translate("MainWindow", u"ShiftHorizontally", None))
#if QT_CONFIG(tooltip)
        self.actionShiftHorizontally.setToolTip(QCoreApplication.translate("MainWindow", u"Shift the selected curve horizontally", None))
#endif // QT_CONFIG(tooltip)
        self.actionNew_Empty_Dataset.setText(QCoreApplication.translate("MainWindow", u"New Empty Dataset", None))
#if QT_CONFIG(tooltip)
        self.actionNew_Empty_Dataset.setToolTip(QCoreApplication.translate("MainWindow", u"Create an empty Data set (Ctrl+N)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionNew_Empty_Dataset.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+N", None))
#endif // QT_CONFIG(shortcut)
        self.actionNew_Dataset_From_File.setText(QCoreApplication.translate("MainWindow", u"New Dataset From File", None))
#if QT_CONFIG(tooltip)
        self.actionNew_Dataset_From_File.setToolTip(QCoreApplication.translate("MainWindow", u"Open Data File (Ctrl+O)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionNew_Dataset_From_File.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.actionView_All_Sets.setText(QCoreApplication.translate("MainWindow", u"View All Sets", None))
#if QT_CONFIG(tooltip)
        self.actionView_All_Sets.setToolTip(QCoreApplication.translate("MainWindow", u"View all sets simultaneously (Ctrl+A)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionView_All_Sets.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+A", None))
#endif // QT_CONFIG(shortcut)
        self.actionReload_Data.setText(QCoreApplication.translate("MainWindow", u"Reload Data", None))
#if QT_CONFIG(tooltip)
        self.actionReload_Data.setToolTip(QCoreApplication.translate("MainWindow", u"Reload data files and theories (Ctrl+R)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionReload_Data.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+R", None))
#endif // QT_CONFIG(shortcut)
        self.actionInspect_Data.setText(QCoreApplication.translate("MainWindow", u"Inspect Data", None))
#if QT_CONFIG(tooltip)
        self.actionInspect_Data.setToolTip(QCoreApplication.translate("MainWindow", u"Inspect contents of data files (Ctrl+I)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionInspect_Data.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+I", None))
#endif // QT_CONFIG(shortcut)
        self.actionMarkerSettings.setText(QCoreApplication.translate("MainWindow", u"Select Symbols Color", None))
#if QT_CONFIG(tooltip)
        self.actionMarkerSettings.setToolTip(QCoreApplication.translate("MainWindow", u"Select Dataset Plot Style (Ctrl+M)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionMarkerSettings.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+M", None))
#endif // QT_CONFIG(shortcut)
        self.actionTrack_data.setText(QCoreApplication.translate("MainWindow", u"Track data", None))
#if QT_CONFIG(tooltip)
        self.actionTrack_data.setToolTip(QCoreApplication.translate("MainWindow", u"Track data", None))
#endif // QT_CONFIG(tooltip)
        self.actionAdd_Annotation.setText(QCoreApplication.translate("MainWindow", u"Add Annotation", None))
#if QT_CONFIG(tooltip)
        self.actionAdd_Annotation.setToolTip(QCoreApplication.translate("MainWindow", u"Add Annotation", None))
#endif // QT_CONFIG(tooltip)
        self.actionShow_Legend.setText(QCoreApplication.translate("MainWindow", u"Show Legend", None))
#if QT_CONFIG(tooltip)
        self.actionShow_Legend.setToolTip(QCoreApplication.translate("MainWindow", u"Show Legend", None))
#endif // QT_CONFIG(tooltip)
        self.actionCopyChart.setText(QCoreApplication.translate("MainWindow", u"CopyChart", None))
#if QT_CONFIG(tooltip)
        self.actionCopyChart.setToolTip(QCoreApplication.translate("MainWindow", u"Copy Chart", None))
#endif // QT_CONFIG(tooltip)
        self.actionNew_Tool.setText(QCoreApplication.translate("MainWindow", u"New Tool", None))
#if QT_CONFIG(tooltip)
        self.actionNew_Tool.setToolTip(QCoreApplication.translate("MainWindow", u"New Tool (Alt+T)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionNew_Tool.setShortcut(QCoreApplication.translate("MainWindow", u"Alt+T", None))
#endif // QT_CONFIG(shortcut)
        self.actionSave_View.setText(QCoreApplication.translate("MainWindow", u"Save View", None))
#if QT_CONFIG(tooltip)
        self.actionSave_View.setToolTip(QCoreApplication.translate("MainWindow", u"Save All Data in Current View", None))
#endif // QT_CONFIG(tooltip)
        self.actionResetShiftFactors.setText(QCoreApplication.translate("MainWindow", u"Reset Shift Factors", None))
#if QT_CONFIG(tooltip)
        self.actionResetShiftFactors.setToolTip(QCoreApplication.translate("MainWindow", u"Reset Shift Factors", None))
#endif // QT_CONFIG(tooltip)
        self.actionViewShiftFactors.setText(QCoreApplication.translate("MainWindow", u"View Shift Factors", None))
#if QT_CONFIG(tooltip)
        self.actionViewShiftFactors.setToolTip(QCoreApplication.translate("MainWindow", u"View Current Shift Factors", None))
#endif // QT_CONFIG(tooltip)
        self.actionSaveShiftFactors.setText(QCoreApplication.translate("MainWindow", u"Save Shift Factors", None))
#if QT_CONFIG(tooltip)
        self.actionSaveShiftFactors.setToolTip(QCoreApplication.translate("MainWindow", u"Save Shift Factors", None))
#endif // QT_CONFIG(tooltip)
        self.actionAddDummyFiles.setText(QCoreApplication.translate("MainWindow", u"Add Dummy Files", None))
#if QT_CONFIG(tooltip)
        self.actionAddDummyFiles.setToolTip(QCoreApplication.translate("MainWindow", u"Add Set of Empty Files to Current Dataset", None))
#endif // QT_CONFIG(tooltip)
        self.actionView_All_SetTheories.setText(QCoreApplication.translate("MainWindow", u"View All Theories (Same DataSet)", None))
#if QT_CONFIG(tooltip)
        self.actionView_All_SetTheories.setToolTip(QCoreApplication.translate("MainWindow", u"View all theories simultaneously (same Set)", None))
#endif // QT_CONFIG(tooltip)
        self.action_import_from_excel.setText(QCoreApplication.translate("MainWindow", u"Import from Excel", None))
#if QT_CONFIG(tooltip)
        self.action_import_from_excel.setToolTip(QCoreApplication.translate("MainWindow", u"Import data from Excel file", None))
#endif // QT_CONFIG(tooltip)
        self.actionAdd_File_With_Function.setText(QCoreApplication.translate("MainWindow", u"Add Dummy File using Function", None))
#if QT_CONFIG(tooltip)
        self.actionAdd_File_With_Function.setToolTip(QCoreApplication.translate("MainWindow", u"Create a Dummy File using a mathematical expression", None))
#endif // QT_CONFIG(tooltip)
        self.action_import_from_pasted.setText(QCoreApplication.translate("MainWindow", u"Paste Data", None))
#if QT_CONFIG(tooltip)
        self.action_import_from_pasted.setToolTip(QCoreApplication.translate("MainWindow", u"Import from pasted data", None))
#endif // QT_CONFIG(tooltip)
        self.actionSaveDataSet.setText(QCoreApplication.translate("MainWindow", u"Save Data Set", None))
#if QT_CONFIG(tooltip)
        self.actionSaveDataSet.setToolTip(QCoreApplication.translate("MainWindow", u"Save Current Data Set", None))
#endif // QT_CONFIG(tooltip)
        self.ViewDataTheorydockWidget.setWindowTitle(QCoreApplication.translate("MainWindow", u"Views/Data/Theory", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"View:", None))
        self.viewComboBox.setCurrentText("")
        self.saveViewtoolButton.setText(QCoreApplication.translate("MainWindow", u"...", None))
    # retranslateUi

