# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'ReptateMainWindow.ui'
##
## Created by: Qt User Interface Compiler version 6.6.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QDockWidget, QHBoxLayout, QMainWindow,
    QSizePolicy, QTabWidget, QToolBar, QVBoxLayout,
    QWidget)
import MainWindow_rc

class Ui_ReptateMainWindow(object):
    def setupUi(self, ReptateMainWindow):
        if not ReptateMainWindow.objectName():
            ReptateMainWindow.setObjectName(u"ReptateMainWindow")
        ReptateMainWindow.resize(800, 600)
        icon = QIcon()
        icon.addFile(u":/Icons/Images/Reptate64.ico", QSize(), QIcon.Normal, QIcon.Off)
        ReptateMainWindow.setWindowIcon(icon)
        self.actionQuit = QAction(ReptateMainWindow)
        self.actionQuit.setObjectName(u"actionQuit")
        icon1 = QIcon()
        icon1.addFile(u":/Icons/Images/new_icons/icons8-exit-sign.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionQuit.setIcon(icon1)
        self.actionTTS = QAction(ReptateMainWindow)
        self.actionTTS.setObjectName(u"actionTTS")
        icon2 = QIcon()
        icon2.addFile(u":/Icons/Images/new_icons/TTS.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionTTS.setIcon(icon2)
        self.actionLVE = QAction(ReptateMainWindow)
        self.actionLVE.setObjectName(u"actionLVE")
        icon3 = QIcon()
        icon3.addFile(u":/Icons/Images/new_icons/LVE.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionLVE.setIcon(icon3)
        self.actionNLVE = QAction(ReptateMainWindow)
        self.actionNLVE.setObjectName(u"actionNLVE")
        icon4 = QIcon()
        icon4.addFile(u":/Icons/Images/new_icons/NLVE.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionNLVE.setIcon(icon4)
        self.actionGt = QAction(ReptateMainWindow)
        self.actionGt.setObjectName(u"actionGt")
        icon5 = QIcon()
        icon5.addFile(u":/Icons/Images/new_icons/Gt.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionGt.setIcon(icon5)
        self.actionAbout = QAction(ReptateMainWindow)
        self.actionAbout.setObjectName(u"actionAbout")
        icon6 = QIcon()
        icon6.addFile(u":/Icons/Images/Reptate_logo_100.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionAbout.setIcon(icon6)
        self.actionMWD = QAction(ReptateMainWindow)
        self.actionMWD.setObjectName(u"actionMWD")
        icon7 = QIcon()
        icon7.addFile(u":/Icons/Images/new_icons/MWD.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionMWD.setIcon(icon7)
        self.actionCreep = QAction(ReptateMainWindow)
        self.actionCreep.setObjectName(u"actionCreep")
        icon8 = QIcon()
        icon8.addFile(u":/Icons/Images/new_icons/Creep.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionCreep.setIcon(icon8)
        self.actionSANS = QAction(ReptateMainWindow)
        self.actionSANS.setObjectName(u"actionSANS")
        icon9 = QIcon()
        icon9.addFile(u":/Icons/Images/new_icons/SANS.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionSANS.setIcon(icon9)
        self.actionAbout_Qt = QAction(ReptateMainWindow)
        self.actionAbout_Qt.setObjectName(u"actionAbout_Qt")
        icon10 = QIcon()
        icon10.addFile(u":/Icons/Images/qt_logo_128.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionAbout_Qt.setIcon(icon10)
        self.actionAbout_Qt.setIconVisibleInMenu(True)
        self.actionReact = QAction(ReptateMainWindow)
        self.actionReact.setObjectName(u"actionReact")
        icon11 = QIcon()
        icon11.addFile(u":/Icons/Images/new_icons/React.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionReact.setIcon(icon11)
        self.actionDielectric = QAction(ReptateMainWindow)
        self.actionDielectric.setObjectName(u"actionDielectric")
        icon12 = QIcon()
        icon12.addFile(u":/Icons/Images/new_icons/Dielectric.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionDielectric.setIcon(icon12)
        self.actionDynamicStructureFactor = QAction(ReptateMainWindow)
        self.actionDynamicStructureFactor.setObjectName(u"actionDynamicStructureFactor")
        icon13 = QIcon()
        icon13.addFile(u":/Icons/Images/new_icons/DynamicStructureFactor.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionDynamicStructureFactor.setIcon(icon13)
        self.actionOpenProject = QAction(ReptateMainWindow)
        self.actionOpenProject.setObjectName(u"actionOpenProject")
        icon14 = QIcon()
        icon14.addFile(u":/Icons/Images/new_icons/icons8-open.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionOpenProject.setIcon(icon14)
        self.actionSaveProject = QAction(ReptateMainWindow)
        self.actionSaveProject.setObjectName(u"actionSaveProject")
        icon15 = QIcon()
        icon15.addFile(u":/Icons/Images/new_icons/icons8-save.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionSaveProject.setIcon(icon15)
        self.actionShow_reptate_help = QAction(ReptateMainWindow)
        self.actionShow_reptate_help.setObjectName(u"actionShow_reptate_help")
        icon16 = QIcon()
        icon16.addFile(u":/Icons/Images/new_icons/icons8-user-manual.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionShow_reptate_help.setIcon(icon16)
        self.actionShow_app_help = QAction(ReptateMainWindow)
        self.actionShow_app_help.setObjectName(u"actionShow_app_help")
        icon17 = QIcon()
        icon17.addFile(u":/Icons/Images/new_icons/icons8-user-manualApp.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionShow_app_help.setIcon(icon17)
        self.actionShow_th_help = QAction(ReptateMainWindow)
        self.actionShow_th_help.setObjectName(u"actionShow_th_help")
        icon18 = QIcon()
        icon18.addFile(u":/Icons/Images/new_icons/icons8-user-manualTh.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionShow_th_help.setIcon(icon18)
        self.actionAboutMatplotlib = QAction(ReptateMainWindow)
        self.actionAboutMatplotlib.setObjectName(u"actionAboutMatplotlib")
        icon19 = QIcon()
        icon19.addFile(u":/Icons/Images/new_icons/Created_with_Matplotlib-logo2.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionAboutMatplotlib.setIcon(icon19)
        self.actionAboutMatplotlib.setIconVisibleInMenu(True)
        self.actionAboutNumpy = QAction(ReptateMainWindow)
        self.actionAboutNumpy.setObjectName(u"actionAboutNumpy")
        icon20 = QIcon()
        icon20.addFile(u":/Icons/Images/new_icons/numpylogo.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionAboutNumpy.setIcon(icon20)
        self.actionAboutNumpy.setIconVisibleInMenu(True)
        self.actionAboutScipy = QAction(ReptateMainWindow)
        self.actionAboutScipy.setObjectName(u"actionAboutScipy")
        icon21 = QIcon()
        icon21.addFile(u":/Icons/Images/new_icons/scipylogo.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionAboutScipy.setIcon(icon21)
        self.actionAboutScipy.setIconVisibleInMenu(True)
        self.actionShow_offline_help = QAction(ReptateMainWindow)
        self.actionShow_offline_help.setObjectName(u"actionShow_offline_help")
        icon22 = QIcon()
        icon22.addFile(u":/Icons/Images/new_icons/icons8-airplane-mode-on.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionShow_offline_help.setIcon(icon22)
        self.actionLAOS = QAction(ReptateMainWindow)
        self.actionLAOS.setObjectName(u"actionLAOS")
        icon23 = QIcon()
        icon23.addFile(u":/Icons/Images/new_icons/LAOS.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionLAOS.setIcon(icon23)
        self.actionTTSFactors = QAction(ReptateMainWindow)
        self.actionTTSFactors.setObjectName(u"actionTTSFactors")
        icon24 = QIcon()
        icon24.addFile(u":/Icons/Images/new_icons/TTSF.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionTTSFactors.setIcon(icon24)
        self.actionCheckRepTateVersion = QAction(ReptateMainWindow)
        self.actionCheckRepTateVersion.setObjectName(u"actionCheckRepTateVersion")
        self.actionCheckRepTateVersion.setIcon(icon6)
        self.actionCite_RepTate = QAction(ReptateMainWindow)
        self.actionCite_RepTate.setObjectName(u"actionCite_RepTate")
        icon25 = QIcon()
        icon25.addFile(u":/Icons/Images/new_icons/icons8-hot-article-96.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionCite_RepTate.setIcon(icon25)
        self.actionShow_Logger = QAction(ReptateMainWindow)
        self.actionShow_Logger.setObjectName(u"actionShow_Logger")
        self.actionShow_Logger.setCheckable(True)
        icon26 = QIcon()
        icon26.addFile(u":/Icons/Images/new_icons/icons8-library.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionShow_Logger.setIcon(icon26)
        self.actionCrystal = QAction(ReptateMainWindow)
        self.actionCrystal.setObjectName(u"actionCrystal")
        icon27 = QIcon()
        icon27.addFile(u":/Icons/Images/new_icons/Crystal.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionCrystal.setIcon(icon27)
        self.actionLogCritical = QAction(ReptateMainWindow)
        self.actionLogCritical.setObjectName(u"actionLogCritical")
        icon28 = QIcon()
        icon28.addFile(u":/Icons/Images/new_icons/icons8-fires-80.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionLogCritical.setIcon(icon28)
        self.actionLogError = QAction(ReptateMainWindow)
        self.actionLogError.setObjectName(u"actionLogError")
        icon29 = QIcon()
        icon29.addFile(u":/Icons/Images/new_icons/icons8-obstruction-lights-error-80.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionLogError.setIcon(icon29)
        self.actionLogWarning = QAction(ReptateMainWindow)
        self.actionLogWarning.setObjectName(u"actionLogWarning")
        icon30 = QIcon()
        icon30.addFile(u":/Icons/Images/new_icons/icons8-brake-warning-96.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionLogWarning.setIcon(icon30)
        self.actionLogDebug = QAction(ReptateMainWindow)
        self.actionLogDebug.setObjectName(u"actionLogDebug")
        icon31 = QIcon()
        icon31.addFile(u":/Icons/Images/new_icons/icons8-bug-80.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionLogDebug.setIcon(icon31)
        self.actionLogInfo = QAction(ReptateMainWindow)
        self.actionLogInfo.setObjectName(u"actionLogInfo")
        icon32 = QIcon()
        icon32.addFile(u":/Icons/Images/new_icons/icons8-info-80.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionLogInfo.setIcon(icon32)
        self.actionLogNotSet = QAction(ReptateMainWindow)
        self.actionLogNotSet.setObjectName(u"actionLogNotSet")
        icon33 = QIcon()
        icon33.addFile(u":/Icons/Images/new_icons/icons8-galaxy-80.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionLogNotSet.setIcon(icon33)
        self.actionCopyLogText = QAction(ReptateMainWindow)
        self.actionCopyLogText.setObjectName(u"actionCopyLogText")
        icon34 = QIcon()
        icon34.addFile(u":/Icons/Images/new_icons/icons8-copy-96.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionCopyLogText.setIcon(icon34)
        self.centralwidget = QWidget(ReptateMainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.verticalLayout = QVBoxLayout(self.centralwidget)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.ApplicationtabWidget = QTabWidget(self.centralwidget)
        self.ApplicationtabWidget.setObjectName(u"ApplicationtabWidget")
        self.ApplicationtabWidget.setTabShape(QTabWidget.Triangular)
        self.ApplicationtabWidget.setTabsClosable(True)

        self.verticalLayout.addWidget(self.ApplicationtabWidget)

        ReptateMainWindow.setCentralWidget(self.centralwidget)
        self.toolBarProject = QToolBar(ReptateMainWindow)
        self.toolBarProject.setObjectName(u"toolBarProject")
        self.toolBarProject.setMovable(True)
        self.toolBarProject.setAllowedAreas(Qt.AllToolBarAreas)
        self.toolBarProject.setIconSize(QSize(24, 24))
        self.toolBarProject.setFloatable(False)
        ReptateMainWindow.addToolBar(Qt.TopToolBarArea, self.toolBarProject)
        self.toolBarApps = QToolBar(ReptateMainWindow)
        self.toolBarApps.setObjectName(u"toolBarApps")
        self.toolBarApps.setFloatable(False)
        ReptateMainWindow.addToolBar(Qt.TopToolBarArea, self.toolBarApps)
        self.toolBarHelpAbout = QToolBar(ReptateMainWindow)
        self.toolBarHelpAbout.setObjectName(u"toolBarHelpAbout")
        self.toolBarHelpAbout.setEnabled(True)
        self.toolBarHelpAbout.setOrientation(Qt.Horizontal)
        self.toolBarHelpAbout.setToolButtonStyle(Qt.ToolButtonIconOnly)
        ReptateMainWindow.addToolBar(Qt.TopToolBarArea, self.toolBarHelpAbout)
        self.LoggerdockWidget = QDockWidget(ReptateMainWindow)
        self.LoggerdockWidget.setObjectName(u"LoggerdockWidget")
        font = QFont()
        font.setBold(True)
        self.LoggerdockWidget.setFont(font)
        self.LoggerdockWidget.setFeatures(QDockWidget.DockWidgetClosable)
        self.LoggerdockWidget.setAllowedAreas(Qt.BottomDockWidgetArea)
        self.LoggerdockWidgetContents = QWidget()
        self.LoggerdockWidgetContents.setObjectName(u"LoggerdockWidgetContents")
        self.LoggerdochorizontalLayout = QHBoxLayout(self.LoggerdockWidgetContents)
        self.LoggerdochorizontalLayout.setSpacing(0)
        self.LoggerdochorizontalLayout.setObjectName(u"LoggerdochorizontalLayout")
        self.LoggerdochorizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.LoggerdockWidget.setWidget(self.LoggerdockWidgetContents)
        ReptateMainWindow.addDockWidget(Qt.BottomDockWidgetArea, self.LoggerdockWidget)

        self.toolBarProject.addAction(self.actionOpenProject)
        self.toolBarProject.addAction(self.actionSaveProject)
        self.toolBarProject.addAction(self.actionQuit)
        self.toolBarApps.addAction(self.actionMWD)
        self.toolBarApps.addAction(self.actionLVE)
        self.toolBarApps.addAction(self.actionNLVE)
        self.toolBarApps.addAction(self.actionGt)
        self.toolBarApps.addAction(self.actionCreep)
        self.toolBarApps.addAction(self.actionSANS)
        self.toolBarApps.addAction(self.actionReact)
        self.toolBarApps.addAction(self.actionDielectric)

        self.retranslateUi(ReptateMainWindow)
        self.actionQuit.triggered.connect(ReptateMainWindow.close)

        QMetaObject.connectSlotsByName(ReptateMainWindow)
    # setupUi

    def retranslateUi(self, ReptateMainWindow):
        ReptateMainWindow.setWindowTitle(QCoreApplication.translate("ReptateMainWindow", u"RepTate", None))
        self.actionQuit.setText(QCoreApplication.translate("ReptateMainWindow", u"&Quit", None))
#if QT_CONFIG(tooltip)
        self.actionQuit.setToolTip(QCoreApplication.translate("ReptateMainWindow", u"Exit Reptate (Ctrl+Q)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionQuit.setShortcut(QCoreApplication.translate("ReptateMainWindow", u"Ctrl+Q", None))
#endif // QT_CONFIG(shortcut)
        self.actionTTS.setText(QCoreApplication.translate("ReptateMainWindow", u"TTS", None))
#if QT_CONFIG(tooltip)
        self.actionTTS.setToolTip(QCoreApplication.translate("ReptateMainWindow", u"Time-Temperature Superposition (Ctrl+2)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionTTS.setShortcut(QCoreApplication.translate("ReptateMainWindow", u"Ctrl+2", None))
#endif // QT_CONFIG(shortcut)
        self.actionLVE.setText(QCoreApplication.translate("ReptateMainWindow", u"LVE", None))
#if QT_CONFIG(tooltip)
        self.actionLVE.setToolTip(QCoreApplication.translate("ReptateMainWindow", u"Linear Viscoelasticity (Ctrl+3)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionLVE.setShortcut(QCoreApplication.translate("ReptateMainWindow", u"Ctrl+3", None))
#endif // QT_CONFIG(shortcut)
        self.actionNLVE.setText(QCoreApplication.translate("ReptateMainWindow", u"NLVE", None))
#if QT_CONFIG(tooltip)
        self.actionNLVE.setToolTip(QCoreApplication.translate("ReptateMainWindow", u"Start up of shear/extension (Ctrl+4)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionNLVE.setShortcut(QCoreApplication.translate("ReptateMainWindow", u"Ctrl+4", None))
#endif // QT_CONFIG(shortcut)
        self.actionGt.setText(QCoreApplication.translate("ReptateMainWindow", u"Gt", None))
#if QT_CONFIG(tooltip)
        self.actionGt.setToolTip(QCoreApplication.translate("ReptateMainWindow", u"Stress relaxation (Ctrl+5)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionGt.setShortcut(QCoreApplication.translate("ReptateMainWindow", u"Ctrl+5", None))
#endif // QT_CONFIG(shortcut)
        self.actionAbout.setText(QCoreApplication.translate("ReptateMainWindow", u" About Reptate", None))
        self.actionMWD.setText(QCoreApplication.translate("ReptateMainWindow", u"MWD", None))
#if QT_CONFIG(tooltip)
        self.actionMWD.setToolTip(QCoreApplication.translate("ReptateMainWindow", u"Molecular Weight Distribution (Ctrl+1)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionMWD.setShortcut(QCoreApplication.translate("ReptateMainWindow", u"Ctrl+1", None))
#endif // QT_CONFIG(shortcut)
        self.actionCreep.setText(QCoreApplication.translate("ReptateMainWindow", u"Creep", None))
#if QT_CONFIG(tooltip)
        self.actionCreep.setToolTip(QCoreApplication.translate("ReptateMainWindow", u"Creep experiments (Ctrl+6)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionCreep.setShortcut(QCoreApplication.translate("ReptateMainWindow", u"Ctrl+6", None))
#endif // QT_CONFIG(shortcut)
        self.actionSANS.setText(QCoreApplication.translate("ReptateMainWindow", u"SANS", None))
#if QT_CONFIG(tooltip)
        self.actionSANS.setToolTip(QCoreApplication.translate("ReptateMainWindow", u"Small Angle Neutron Scattering (Ctrl+7)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionSANS.setShortcut(QCoreApplication.translate("ReptateMainWindow", u"Ctrl+7", None))
#endif // QT_CONFIG(shortcut)
        self.actionAbout_Qt.setText(QCoreApplication.translate("ReptateMainWindow", u"About Qt", None))
        self.actionReact.setText(QCoreApplication.translate("ReptateMainWindow", u"React", None))
#if QT_CONFIG(tooltip)
        self.actionReact.setToolTip(QCoreApplication.translate("ReptateMainWindow", u"React module (Ctrl+8)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionReact.setShortcut(QCoreApplication.translate("ReptateMainWindow", u"Ctrl+8", None))
#endif // QT_CONFIG(shortcut)
        self.actionDielectric.setText(QCoreApplication.translate("ReptateMainWindow", u"Dielectric", None))
#if QT_CONFIG(tooltip)
        self.actionDielectric.setToolTip(QCoreApplication.translate("ReptateMainWindow", u"Dielectric spectroscopy (Ctrl+9)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionDielectric.setShortcut(QCoreApplication.translate("ReptateMainWindow", u"Ctrl+9", None))
#endif // QT_CONFIG(shortcut)
        self.actionDynamicStructureFactor.setText(QCoreApplication.translate("ReptateMainWindow", u"DynamicStructureFactor", None))
#if QT_CONFIG(tooltip)
        self.actionDynamicStructureFactor.setToolTip(QCoreApplication.translate("ReptateMainWindow", u"Dynamic Structure Factor (Ctrl+0)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionDynamicStructureFactor.setShortcut(QCoreApplication.translate("ReptateMainWindow", u"Ctrl+0", None))
#endif // QT_CONFIG(shortcut)
        self.actionOpenProject.setText(QCoreApplication.translate("ReptateMainWindow", u"OpenProject", None))
#if QT_CONFIG(tooltip)
        self.actionOpenProject.setToolTip(QCoreApplication.translate("ReptateMainWindow", u"Open RepTate Project", None))
#endif // QT_CONFIG(tooltip)
        self.actionSaveProject.setText(QCoreApplication.translate("ReptateMainWindow", u"SaveProject", None))
#if QT_CONFIG(tooltip)
        self.actionSaveProject.setToolTip(QCoreApplication.translate("ReptateMainWindow", u"Save RepTate Project", None))
#endif // QT_CONFIG(tooltip)
        self.actionShow_reptate_help.setText(QCoreApplication.translate("ReptateMainWindow", u"RepTate Documantation", None))
#if QT_CONFIG(tooltip)
        self.actionShow_reptate_help.setToolTip(QCoreApplication.translate("ReptateMainWindow", u"RepTate help", None))
#endif // QT_CONFIG(tooltip)
        self.actionShow_app_help.setText(QCoreApplication.translate("ReptateMainWindow", u"Current Application Documentation", None))
#if QT_CONFIG(tooltip)
        self.actionShow_app_help.setToolTip(QCoreApplication.translate("ReptateMainWindow", u"Current Application help", None))
#endif // QT_CONFIG(tooltip)
        self.actionShow_th_help.setText(QCoreApplication.translate("ReptateMainWindow", u"Current Theory Documentation", None))
#if QT_CONFIG(tooltip)
        self.actionShow_th_help.setToolTip(QCoreApplication.translate("ReptateMainWindow", u"Current Theory help", None))
#endif // QT_CONFIG(tooltip)
        self.actionAboutMatplotlib.setText(QCoreApplication.translate("ReptateMainWindow", u"About Matplotlib", None))
#if QT_CONFIG(tooltip)
        self.actionAboutMatplotlib.setToolTip(QCoreApplication.translate("ReptateMainWindow", u"About Matplotlib", None))
#endif // QT_CONFIG(tooltip)
        self.actionAboutNumpy.setText(QCoreApplication.translate("ReptateMainWindow", u"About Numpy", None))
#if QT_CONFIG(tooltip)
        self.actionAboutNumpy.setToolTip(QCoreApplication.translate("ReptateMainWindow", u"About Numpy", None))
#endif // QT_CONFIG(tooltip)
        self.actionAboutScipy.setText(QCoreApplication.translate("ReptateMainWindow", u"About Scipy", None))
#if QT_CONFIG(tooltip)
        self.actionAboutScipy.setToolTip(QCoreApplication.translate("ReptateMainWindow", u"About Scipy", None))
#endif // QT_CONFIG(tooltip)
        self.actionShow_offline_help.setText(QCoreApplication.translate("ReptateMainWindow", u"Offline Documentation", None))
#if QT_CONFIG(tooltip)
        self.actionShow_offline_help.setToolTip(QCoreApplication.translate("ReptateMainWindow", u"Current Theory help", None))
#endif // QT_CONFIG(tooltip)
        self.actionLAOS.setText(QCoreApplication.translate("ReptateMainWindow", u"LAOS", None))
#if QT_CONFIG(tooltip)
        self.actionLAOS.setToolTip(QCoreApplication.translate("ReptateMainWindow", u"Large Amplitude Oscillatory Shear", None))
#endif // QT_CONFIG(tooltip)
        self.actionTTSFactors.setText(QCoreApplication.translate("ReptateMainWindow", u"TTS Factors", None))
#if QT_CONFIG(tooltip)
        self.actionTTSFactors.setToolTip(QCoreApplication.translate("ReptateMainWindow", u"Time-Temperature Superposition Factors", None))
#endif // QT_CONFIG(tooltip)
        self.actionCheckRepTateVersion.setText(QCoreApplication.translate("ReptateMainWindow", u"Check for new RepTate Version", None))
#if QT_CONFIG(tooltip)
        self.actionCheckRepTateVersion.setToolTip(QCoreApplication.translate("ReptateMainWindow", u"Check Github for new versions of RepTate", None))
#endif // QT_CONFIG(tooltip)
        self.actionCite_RepTate.setText(QCoreApplication.translate("ReptateMainWindow", u"Cite RepTate", None))
#if QT_CONFIG(tooltip)
        self.actionCite_RepTate.setToolTip(QCoreApplication.translate("ReptateMainWindow", u"Cite the main RepTate papers", None))
#endif // QT_CONFIG(tooltip)
        self.actionShow_Logger.setText(QCoreApplication.translate("ReptateMainWindow", u"Show Logger", None))
#if QT_CONFIG(tooltip)
        self.actionShow_Logger.setToolTip(QCoreApplication.translate("ReptateMainWindow", u"Show Log Window", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionShow_Logger.setShortcut(QCoreApplication.translate("ReptateMainWindow", u"Ctrl+Alt+L", None))
#endif // QT_CONFIG(shortcut)
        self.actionCrystal.setText(QCoreApplication.translate("ReptateMainWindow", u"Crystal", None))
#if QT_CONFIG(tooltip)
        self.actionCrystal.setToolTip(QCoreApplication.translate("ReptateMainWindow", u"Flow Induced Crystallisation", None))
#endif // QT_CONFIG(tooltip)
        self.actionLogCritical.setText(QCoreApplication.translate("ReptateMainWindow", u"Log Critical", None))
#if QT_CONFIG(tooltip)
        self.actionLogCritical.setToolTip(QCoreApplication.translate("ReptateMainWindow", u"Set log level to CRITICAL", None))
#endif // QT_CONFIG(tooltip)
        self.actionLogError.setText(QCoreApplication.translate("ReptateMainWindow", u"Log Error", None))
#if QT_CONFIG(tooltip)
        self.actionLogError.setToolTip(QCoreApplication.translate("ReptateMainWindow", u"Set log level to ERROR", None))
#endif // QT_CONFIG(tooltip)
        self.actionLogWarning.setText(QCoreApplication.translate("ReptateMainWindow", u"Log Warning", None))
#if QT_CONFIG(tooltip)
        self.actionLogWarning.setToolTip(QCoreApplication.translate("ReptateMainWindow", u"Set log level to WARNING", None))
#endif // QT_CONFIG(tooltip)
        self.actionLogDebug.setText(QCoreApplication.translate("ReptateMainWindow", u"Log Debug", None))
#if QT_CONFIG(tooltip)
        self.actionLogDebug.setToolTip(QCoreApplication.translate("ReptateMainWindow", u"Set log level to DEBUG", None))
#endif // QT_CONFIG(tooltip)
        self.actionLogInfo.setText(QCoreApplication.translate("ReptateMainWindow", u"Log Info", None))
#if QT_CONFIG(tooltip)
        self.actionLogInfo.setToolTip(QCoreApplication.translate("ReptateMainWindow", u"Set log level to INFO", None))
#endif // QT_CONFIG(tooltip)
        self.actionLogNotSet.setText(QCoreApplication.translate("ReptateMainWindow", u"Log Not Set", None))
#if QT_CONFIG(tooltip)
        self.actionLogNotSet.setToolTip(QCoreApplication.translate("ReptateMainWindow", u"Set log level to NOTSET", None))
#endif // QT_CONFIG(tooltip)
        self.actionCopyLogText.setText(QCoreApplication.translate("ReptateMainWindow", u"Copy Log Text", None))
#if QT_CONFIG(tooltip)
        self.actionCopyLogText.setToolTip(QCoreApplication.translate("ReptateMainWindow", u"Copy Log Text to the Clipboard", None))
#endif // QT_CONFIG(tooltip)
        self.toolBarProject.setWindowTitle(QCoreApplication.translate("ReptateMainWindow", u"toolBar", None))
#if QT_CONFIG(tooltip)
        self.toolBarProject.setToolTip(QCoreApplication.translate("ReptateMainWindow", u"Project Toolbar", None))
#endif // QT_CONFIG(tooltip)
        self.toolBarApps.setWindowTitle(QCoreApplication.translate("ReptateMainWindow", u"toolBar", None))
#if QT_CONFIG(tooltip)
        self.toolBarApps.setToolTip(QCoreApplication.translate("ReptateMainWindow", u"Appications  Toolbar", None))
#endif // QT_CONFIG(tooltip)
        self.toolBarHelpAbout.setWindowTitle(QCoreApplication.translate("ReptateMainWindow", u"toolBar", None))
#if QT_CONFIG(tooltip)
        self.toolBarHelpAbout.setToolTip(QCoreApplication.translate("ReptateMainWindow", u"Help/About Toolbar", None))
#endif // QT_CONFIG(tooltip)
        self.LoggerdockWidget.setWindowTitle(QCoreApplication.translate("ReptateMainWindow", u"Log & Terminal", None))
    # retranslateUi

